import jsPDF from "jspdf";
import { format } from "date-fns";
import getCookieData from "@/utils/getCookieData";
import convertToWords from "@/utils/numberToWords";

const money = (value) => {
  if (value == null || value === "") return "";
  const numeric = Number(value);
  return Number.isNaN(numeric) ? String(value) : numeric.toFixed(2);
};

const clipText = (doc, text, maxWidth) => {
  const value = String(text ?? "");
  if (!value) return "";
  if (doc.getTextWidth(value) <= maxWidth) return value;
  let end = value.length;
  while (end > 1 && doc.getTextWidth(`${value.slice(0, end)}…`) > maxWidth) {
    end -= 1;
  }
  return `${value.slice(0, end)}…`;
};

const yieldUi = () => new Promise((resolve) => setTimeout(resolve, 0));

const label = (t, key, fallback) => {
  if (typeof t !== "function") return fallback;
  const value = t(key);
  return value && value !== key ? value : fallback;
};

const SIDE_COLS = [
  { key: "vno", w: 16, align: "center" },
  { key: "particular", w: 52, align: "left" },
  { key: "cash", w: 24.5, align: "right" },
  { key: "transfer", w: 24.5, align: "right" },
  { key: "total", w: 25, align: "right" },
];

const SIDE_W = SIDE_COLS.reduce((sum, col) => sum + col.w, 0);

const rowValues = (row) => [
  row?.Vouch_No ?? "",
  row?.Particular ?? "",
  money(row?.Cash),
  money(row?.Transfer),
  money(row?.Total),
];

const drawPageChrome = (doc, meta) => {
  const pageW = doc.internal.pageSize.getWidth();
  let y = 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(String(meta.orgName || ""), pageW / 2, y, { align: "center" });
  y += 4;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  [meta.branchName, meta.address, meta.regNo].filter(Boolean).forEach((line) => {
    doc.text(String(line), pageW / 2, y, { align: "center" });
    y += 3.4;
  });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(meta.title, pageW / 2, y, { align: "center" });
  return y + 4;
};

const drawFooter = (doc, meta) => {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const y = pageH - 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(40);
  doc.text(`${meta.generatedBy} ${meta.userName || ""}`, 6, y);
  doc.setTextColor(90);
  doc.text(meta.generatedNote, pageW / 2, y, { align: "center" });
  doc.setTextColor(40);
  doc.text(`${meta.generatedOn} ${meta.stamp}`, pageW - 6, y, { align: "right" });
  doc.setTextColor(0);
};

export const downloadDaybookPdf = async ({
  receipts = [],
  payments = [],
  denomData = [],
  toDate,
  totals,
  cashBalanceData,
  t,
  onProgress,
}) => {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  const meta = {
    orgName: getCookieData("userOrgName") || "",
    branchName: getCookieData("userBranchName") || "",
    address: getCookieData("userOrgAddress") || "",
    regNo: getCookieData("userOrgRegistration") || "",
    userName: getCookieData("userName") || "",
    stamp: format(new Date(), "dd-MM-yyyy hh:mm:ss a"),
    title: `${label(t, "report.daybook.daybookAsOn", "Daybook As On")} ${toDate || ""}`.trim(),
    generatedBy: label(t, "report.daybook.generatedBy", "Generated By :"),
    generatedOn: label(t, "report.daybook.generatedOn", "Generated On :"),
    generatedNote: label(
      t,
      "report.daybook.reportGeneratedByPrioSuite",
      "This report is generated by PrioSuite.",
    ),
  };

  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const startX = Math.max(6, (pageW - SIDE_W * 2) / 2);
  const rightX = startX + SIDE_W;
  const rowH = 5.2;
  const headH = 12;
  const subH = 6;

  const headers = {
    vNo: label(t, "report.daybook.print.vNo", "V. NO."),
    particulars: label(t, "report.daybook.print.particulars", "PARTICULARS"),
    receipts: label(t, "report.daybook.print.receipts", "RECEIPTS"),
    payments: label(t, "report.daybook.print.payments", "PAYMENTS"),
    cash: label(t, "report.daybook.print.cash", "CASH"),
    transfer: label(t, "report.daybook.print.transfer", "TRANSFER"),
    total: label(t, "report.daybook.print.total", "TOTAL"),
  };

  let y = 0;

  const drawSideHead = (x, sectionTitle) => {
    doc.setFillColor(243, 244, 246);
    doc.rect(x, y, SIDE_W, headH, "F");
    doc.setDrawColor(0);
    doc.rect(x, y, SIDE_W, headH);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6);

    let cursor = x;
    SIDE_COLS.forEach((col, index) => {
      if (index < 2) doc.line(cursor, y, cursor, y + headH);
      cursor += col.w;
    });
    doc.line(x + SIDE_W, y, x + SIDE_W, y + headH);

    const moneyX = x + SIDE_COLS[0].w + SIDE_COLS[1].w;
    doc.line(moneyX, y + subH, x + SIDE_W, y + subH);
    let splitX = moneyX;
    SIDE_COLS.slice(2).forEach((col) => {
      doc.line(splitX, y + subH, splitX, y + headH);
      splitX += col.w;
    });

    const vNoX = x + SIDE_COLS[0].w / 2;
    const partX = x + SIDE_COLS[0].w + 0.7;
    doc.text(clipText(doc, headers.vNo, SIDE_COLS[0].w - 1), vNoX, y + 7, {
      align: "center",
    });
    doc.text(
      clipText(doc, headers.particulars, SIDE_COLS[1].w - 1.4),
      partX,
      y + 7,
    );
    doc.text(sectionTitle, moneyX + (SIDE_W - SIDE_COLS[0].w - SIDE_COLS[1].w) / 2, y + 4, {
      align: "center",
    });

    const subTitles = [headers.cash, headers.transfer, headers.total];
    let subX = moneyX;
    SIDE_COLS.slice(2).forEach((col, index) => {
      const textX = col.align === "right" ? subX + col.w - 0.6 : subX + col.w / 2;
      doc.text(clipText(doc, subTitles[index], col.w - 1), textX, y + subH + 4, {
        align: col.align === "right" ? "right" : "center",
      });
      subX += col.w;
    });
  };

  const newPage = () => {
    doc.addPage();
    y = drawPageChrome(doc, meta);
    drawSideHead(startX, headers.receipts);
    drawSideHead(rightX, headers.payments);
    y += headH;
    drawFooter(doc, meta);
  };

  const ensureSpace = (height) => {
    if (y + height > pageH - 10) newPage();
  };

  const paintSide = (x, values, bold) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(6.2);
    doc.rect(x, y, SIDE_W, rowH);
    let cursor = x;
    SIDE_COLS.forEach((col, index) => {
      doc.line(cursor, y, cursor, y + rowH);
      const text = clipText(doc, values[index] ?? "", col.w - 1.1);
      const textX =
        col.align === "right"
          ? cursor + col.w - 0.6
          : col.align === "center"
            ? cursor + col.w / 2
            : cursor + 0.6;
      doc.text(text, textX, y + 3.5, {
        align: col.align === "left" ? "left" : col.align,
      });
      cursor += col.w;
    });
    doc.line(x + SIDE_W, y, x + SIDE_W, y + rowH);
  };

  const paintPair = (left, right, bold = false) => {
    ensureSpace(rowH);
    paintSide(startX, left, bold);
    paintSide(rightX, right, bold);
    y += rowH;
  };

  y = drawPageChrome(doc, meta);
  drawSideHead(startX, headers.receipts);
  drawSideHead(rightX, headers.payments);
  y += headH;
  drawFooter(doc, meta);

  const rowCount = Math.max(receipts.length, payments.length);
  for (let i = 0; i < rowCount; i += 1) {
    paintPair(
      receipts[i] ? rowValues(receipts[i]) : ["", "", "", "", ""],
      payments[i] ? rowValues(payments[i]) : ["", "", "", "", ""],
    );
    if (i > 0 && i % 250 === 0) {
      onProgress?.(i + 1, rowCount);
      await yieldUi();
    }
  }

  const opening = money(cashBalanceData?.Opening || 0);
  const closing = money(cashBalanceData?.Closing || 0);
  const receiptGrandCash = (
    parseFloat(totals?.totalCashReceived || 0) +
    parseFloat(cashBalanceData?.Opening || 0)
  ).toFixed(2);
  const receiptGrandTotal = (
    parseFloat(totals?.totalReceived || 0) +
    parseFloat(cashBalanceData?.Opening || 0)
  ).toFixed(2);
  const paymentGrandCash = (
    parseFloat(totals?.totalCashPayment || 0) +
    parseFloat(cashBalanceData?.Closing || 0)
  ).toFixed(2);
  const paymentGrandTotal = (
    parseFloat(totals?.totalPayment || 0) +
    parseFloat(cashBalanceData?.Closing || 0)
  ).toFixed(2);

  const totalLabel = label(t, "report.daybook.total", "Total");
  const openingLabel = label(t, "report.daybook.openingBalance", "Opening Balance");
  const closingLabel = label(t, "report.daybook.closingBalance", "Closing Balance");
  const grandLabel = label(t, "report.daybook.grandTotal", "Grand Total");

  paintPair(
    ["", totalLabel, money(totals?.totalCashReceived), money(totals?.totalTranferReceived), money(totals?.totalReceived)],
    ["", totalLabel, money(totals?.totalCashPayment), money(totals?.totalTranferPayment), money(totals?.totalPayment)],
    true,
  );
  paintPair(
    ["", openingLabel, opening, "", ""],
    ["", closingLabel, closing, "", ""],
    true,
  );
  paintPair(
    ["", grandLabel, receiptGrandCash, money(totals?.totalTranferReceived), receiptGrandTotal],
    ["", grandLabel, paymentGrandCash, money(totals?.totalTranferPayment), paymentGrandTotal],
    true,
  );

  const closingNumber = parseFloat(cashBalanceData?.Closing || 0);
  const words =
    closingNumber > 0
      ? `${label(t, "common.rupees", "Rupees")} ${convertToWords(closingNumber)} ${label(t, "common.only", "Only")}`
      : label(t, "report.daybook.zero", "Zero");
  const wordsLine = `${label(t, "report.daybook.closingBalanceInWords", "Closing Balance In Words:")} ${words}`;

  ensureSpace(rowH);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(6.5);
  doc.rect(startX, y, SIDE_W * 2, rowH);
  doc.text(clipText(doc, wordsLine, SIDE_W * 2 - 3), startX + SIDE_W * 2 - 1.2, y + 3.5, {
    align: "right",
  });

  doc.addPage();
  y = drawPageChrome(doc, meta);
  drawFooter(doc, meta);

  const denomCols = [
    { title: label(t, "report.daybook.print.slNo", "Sl. NO."), w: 14, align: "center" },
    { title: label(t, "report.daybook.print.denomination", "Denomination"), w: 36, align: "center" },
    { title: label(t, "report.daybook.print.quantity", "Quantity"), w: 24, align: "center" },
    { title: label(t, "report.daybook.print.value", "Value"), w: 28, align: "right" },
  ];
  const denomW = denomCols.reduce((sum, col) => sum + col.w, 0);
  const denomX = 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(
    label(t, "report.daybook.physicalDenomination", "Physical Denomination"),
    denomX + denomW / 2,
    y,
    { align: "center" },
  );
  y += 4;

  const drawDenomHead = () => {
    doc.setFillColor(243, 244, 246);
    doc.rect(denomX, y, denomW, 7, "F");
    doc.rect(denomX, y, denomW, 7);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    let x = denomX;
    denomCols.forEach((col) => {
      doc.line(x, y, x, y + 7);
      const textX = col.align === "right" ? x + col.w - 0.7 : x + col.w / 2;
      doc.text(clipText(doc, col.title, col.w - 1), textX, y + 4.4, {
        align: col.align === "right" ? "right" : "center",
      });
      x += col.w;
    });
    doc.line(denomX + denomW, y, denomX + denomW, y + 7);
    y += 7;
  };

  drawDenomHead();

  const paintDenom = (values, bold = false) => {
    if (y + rowH > pageH - 10) {
      doc.addPage();
      y = drawPageChrome(doc, meta);
      drawFooter(doc, meta);
      drawDenomHead();
    }
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(6.5);
    doc.rect(denomX, y, denomW, rowH);
    let x = denomX;
    denomCols.forEach((col, index) => {
      doc.line(x, y, x, y + rowH);
      const text = clipText(doc, values[index] ?? "", col.w - 1);
      const textX = col.align === "right" ? x + col.w - 0.6 : x + col.w / 2;
      doc.text(text, textX, y + 3.5, {
        align: col.align === "right" ? "right" : "center",
      });
      x += col.w;
    });
    doc.line(denomX + denomW, y, denomX + denomW, y + rowH);
    y += rowH;
  };

  (denomData || []).forEach((denom, index) => {
    paintDenom([
      String(index + 1),
      denom?.Denom_Label ?? "",
      denom?.Denom_Balance ?? "",
      money(denom?.Denom_Value),
    ]);
  });

  const denomTotal = (denomData || []).reduce(
    (sum, current) => sum + parseFloat(current?.Denom_Value || 0),
    0,
  );
  paintDenom(["", totalLabel, "", money(denomTotal)], true);

  doc.save(`Daybook-${toDate || "report"}.pdf`);
};
