import {
  UserPlus,
  Wallet,
  PiggyBank,
  FilePlus2,
  BellRing,
  FileBarChart,
} from "lucide-react";

export const quickActions = [
  {
    id: "add-member",
    label: "Add Member",
    description: "Register a new society member",
    icon: UserPlus,
    href: "/membership/issueMembership",
    iconBg: "bg-blue-50",
    iconColor: "text-blue-600",
  },
  {
    id: "open-account",
    label: "Open Account",
    description: "Open a new deposit account",
    icon: Wallet,
    href: "/deposit/openDepositAccount",
    iconBg: "bg-emerald-50",
    iconColor: "text-emerald-600",
  },
  {
    id: "new-deposit",
    label: "New Deposit",
    description: "Accept cash or bank deposit",
    icon: PiggyBank,
    href: "/deposit/deposit",
    iconBg: "bg-violet-50",
    iconColor: "text-violet-600",
  },
  {
    id: "new-loan",
    label: "New Loan",
    description: "Start a new loan application",
    icon: FilePlus2,
    href: "/loan/newApplication",
    iconBg: "bg-orange-50",
    iconColor: "text-orange-600",
  },
  {
    id: "send-notice",
    label: "Send Notice",
    description: "Review pending membership notices",
    icon: BellRing,
    href: "/approval/membership",
    iconBg: "bg-amber-50",
    iconColor: "text-amber-600",
  },
  {
    id: "view-reports",
    label: "View Reports",
    description: "Open daybook and reports",
    icon: FileBarChart,
    href: "/report/daybook",
    iconBg: "bg-sky-50",
    iconColor: "text-sky-600",
  },
];
