import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { format } from "date-fns";

const formatDateSafe = (dateVal, formatStr = "dd-MM-yyyy") => {
  if (!dateVal) return "";
  try {
    const parsedDate = new Date(dateVal);
    if (isNaN(parsedDate.getTime())) return "";
    return format(parsedDate, formatStr);
  } catch (error) {
    return "";
  }
};

import { useRef } from "react";
import { IoPrint } from "react-icons/io5";
import { ClipLoader } from "react-spinners";
import { useReactToPrint } from "react-to-print";
import ShareLedgerPreview from "./ShareLedgerPreview";

const ShareLedger = ({
  loading,
  showLedger,
  setShowLedger,
  fromDate,
  toDate,
  userName,
  currentDate,
  currentTime,
  totalRefund,
  totalIssue,
  ledgerHeaderData,
  ledgerTableData,
}) => {
  const printRef = useRef(null);

  const handleGeneratePDF = useReactToPrint({
    contentRef: printRef,
    documentTitle: `ShareLedger-${fromDate && formatDateSafe(fromDate, "dd-MM-yyyy")}-${
      toDate && formatDateSafe(toDate, "dd-MM-yyyy")
    }`,
    pageStyle: `
      @page {
        size: A4 portrait;
        margin: 0;
      }
      @media print {
        body {
          margin: 0;
        }
      }
    `,
  });

  return (
    <Dialog open={showLedger} onOpenChange={setShowLedger}>
      <DialogContent className="w-[calc(100vw-1rem)] sm:max-w-[1000px] h-[min(90dvh,600px)] flex items-center justify-center flex-col overflow-y-auto p-3 sm:p-6">
        <DialogHeader className={`mt-5`}>
          <DialogTitle className={`w-fit text-center`}>
            Share Ledger From{" "}
            <span className="">
              {fromDate && formatDateSafe(fromDate, "dd-MM-yyyy")}
            </span>{" "}
            to{" "}
            <span className="">
              {toDate && formatDateSafe(toDate, "dd-MM-yyyy")}
            </span>
          </DialogTitle>
        </DialogHeader>

        {loading ? (
          <div className="h-full w-full flex items-center justify-center ">
            <ClipLoader color="#00264d" size={50} speedMultiplier={0.7} />
          </div>
        ) : (
          <ScrollArea className=" rounded-md border w-[300px] sm:w-full overflow-y-hidden">
            <div className="py-4 w-full flex flex-col gap-5  px-3 lg:px-0 overflow-y-hidden">
              <div className="w-full border border-dashed border-primary bg-secondary grid grid-cols-3 gap-x-5 gap-2 p-5 text-sm">
                <div className="space-y-2">
                  <p>
                    <span className="font-bold">Admission Date : </span>
                    <span>
                      {ledgerHeaderData &&
                        formatDateSafe(
                          ledgerHeaderData?.Adm_Date,
                          "dd-MM-yyyy",
                        )}
                    </span>
                  </p>

                  <p>
                    <span className="font-bold">Ledger Folio : </span>
                    <span>{ledgerHeaderData?.Ledg_Folio}</span>
                  </p>
                </div>

                <div className="space-y-2">
                  <p>
                    <span className="font-bold">Member No : </span>
                    <span>{ledgerHeaderData?.Member_No}</span>
                  </p>

                  <p>
                    <span className="font-bold">Member Name : </span>
                    <span>{ledgerHeaderData?.Full_Name}</span>
                  </p>
                </div>

                <div className="space-y-2">
                  <p>
                    <span className="font-bold">Member Type : </span>
                    <span>{ledgerHeaderData?.Member_Type}</span>
                  </p>

                  <p>
                    <span className="font-bold">Gurdian Name : </span>
                    <span>{ledgerHeaderData?.Relation_Name}</span>
                  </p>
                </div>

                <div className="space-y-2 col-span-3">
                  <p>
                    <span className="font-bold">Address : </span>
                    <span>{ledgerHeaderData?.Address}</span>
                  </p>
                </div>
              </div>
              <div className="h-[500px]">
                <ScrollArea className="h-[500px] overflow-y-scroll">
                  <Table className="border border-primary">
                    <TableCaption>
                      <div className="w-full flex items-center justify-between text-xs px-2">
                        <p>Generated By : {userName}</p>
                        <p>
                          This is computer generated report and does not require
                          signature.
                        </p>
                        <p>
                          Generated On : {currentDate} {currentTime}
                        </p>
                      </div>
                    </TableCaption>
                    <TableHeader>
                      <TableRow className="bg-primary text-white hover:bg-primary">
                        <TableHead className=" text-white text-center w-10">
                          Serial No
                        </TableHead>
                        <TableHead className=" text-white  border-l border-white w-[120px]">
                          Date
                        </TableHead>
                        <TableHead className=" text-white border-l border-white w-fit text-center">
                          Particulars
                        </TableHead>
                        <TableHead className=" text-white border-l border-white text-center">
                          Refund
                        </TableHead>
                        <TableHead className=" text-white border-l border-white text-center">
                          Issue
                        </TableHead>
                        <TableHead className="text-white border-l border-white text-center">
                          Balance
                        </TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {ledgerTableData &&
                        ledgerTableData?.map((data, index) => (
                          <TableRow key={index}>
                            <TableCell className="font-medium border border-secondary text-center">
                              {index + 1}
                            </TableCell>
                            <TableCell className="border border-secondary">
                              {data.Trans_Date &&
                                formatDateSafe(data.Trans_Date, "dd-MM-yyyy")}
                            </TableCell>
                            <TableCell className="border border-secondary">
                              {data?.Particular}
                            </TableCell>
                            <TableCell className="border border-secondary">
                              {data?.Refund}
                            </TableCell>
                            <TableCell className="border border-secondary">
                              {data?.Issue}
                            </TableCell>
                            <TableCell className="border border-secondary">
                              {data?.Balance}
                            </TableCell>
                          </TableRow>
                        ))}
                    </TableBody>
                    <TableFooter>
                      <TableRow>
                        <TableCell colSpan={3}>Grand Total</TableCell>
                        <TableCell className="">
                          {totalRefund && totalRefund.toFixed(2)}
                        </TableCell>
                        <TableCell className="">
                          {totalIssue && totalIssue.toFixed(2)}
                        </TableCell>
                        <TableCell></TableCell>
                      </TableRow>
                    </TableFooter>
                  </Table>
                </ScrollArea>
              </div>
            </div>
            <ScrollBar orientation="horizontal" />
          </ScrollArea>
        )}

        <div className="hidden">
          <ShareLedgerPreview
            printRef={printRef}
            fromDate={fromDate}
            toDate={toDate}
            totalRefund={totalRefund}
            totalIssue={totalIssue}
            ledgerHeaderData={ledgerHeaderData}
            ledgerTableData={ledgerTableData}
          />
        </div>

        <DialogFooter className={`w-full`}>
          <div className="w-full flex items-center justify-end gap-5">
            <div
              onClick={handleGeneratePDF}
              className="p-2 rounded-full flex items-center justify-center text-center bg-primary text-white cursor-pointer text-3xl"
            >
              <IoPrint />
            </div>
            {/* <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <div className="p-2 rounded-full flex items-center justify-center text-center bg-primary text-white cursor-pointer text-3xl">
                  <IoShareSocial />
                </div>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="w-[200px]">
                <DropdownMenuLabel className="text-lg">
                  Share via
                </DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem className="cursor-pointer pl-5 py-2">
                  <p className="flex items-center gap-2 px-3">
                    <IoMail className="text-xl text-primary" /> Mail
                  </p>
                </DropdownMenuItem>
                <DropdownMenuItem className="cursor-pointer pl-5 py-2">
                  <p className="flex items-center gap-2 px-3">
                    <FaWhatsapp className="text-xl text-primary" /> Whatsapp
                  </p>
                </DropdownMenuItem>
                <DropdownMenuItem
                  className="cursor-pointer pl-5 py-2"
                  onClick={handleGeneratePDF}
                >
                  <p className="flex items-center gap-2 px-3">
                    <FaDownload className="text-xl text-primary" /> Download
                  </p>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu> */}
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
export default ShareLedger;
