import jsPDF from "jspdf";
import { format } from "date-fns";
import getCookieData from "@/utils/getCookieData";

export const money = (value) => {
  if (value == null || value === "") return "";
  const numeric = Number(value);
  return Number.isNaN(numeric) ? String(value) : numeric.toFixed(2);
};

export const clipText = (doc, text, maxWidth) => {
  const value = String(text ?? "");
  if (!value) return "";
  if (doc.getTextWidth(value) <= maxWidth) return value;
  let end = value.length;
  while (end > 1 && doc.getTextWidth(`${value.slice(0, end)}…`) > maxWidth) {
    end -= 1;
  }
  return `${value.slice(0, end)}…`;
};

export const yieldUi = () => new Promise((resolve) => setTimeout(resolve, 0));

export const label = (t, key, fallback, options) => {
  if (typeof t !== "function") return fallback;
  const value = t(key, options);
  return value && value !== key ? value : fallback;
};

export const showDate = (value) => {
  if (!value) return "";
  if (value instanceof Date && !Number.isNaN(value.getTime())) {
    return format(value, "dd-MM-yyyy");
  }
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return String(value);
  return format(parsed, "dd-MM-yyyy");
};

export const orgMeta = (title, t) => ({
  orgName: getCookieData("userOrgName") || "",
  branchName: getCookieData("userBranchName") || "",
  address: getCookieData("userOrgAddress") || "",
  regNo: getCookieData("userOrgRegistration") || "",
  userName: getCookieData("userName") || "",
  stamp: format(new Date(), "dd-MM-yyyy hh:mm:ss a"),
  title,
  generatedBy: label(t, "common.generatedBy", "Generated By"),
  generatedOn: label(t, "common.generatedOn", "Generated On"),
  generatedNote: label(
    t,
    "common.thisReportIsGeneratedByPrioSuite",
    "This report is generated by PrioSuite.",
  ),
});

export const openPdf = (orientation) =>
  new jsPDF({
    orientation,
    unit: "mm",
    format: "a4",
    compress: true,
  });

export const drawChrome = (doc, meta) => {
  const pageW = doc.internal.pageSize.getWidth();
  let y = 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(String(meta.orgName || ""), pageW / 2, y, { align: "center" });
  y += 4;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  [meta.branchName, meta.address, meta.regNo].filter(Boolean).forEach((line) => {
    doc.text(String(line), pageW / 2, y, { align: "center" });
    y += 3.4;
  });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  const lines = doc.splitTextToSize(String(meta.title || ""), pageW - 16);
  lines.forEach((line) => {
    doc.text(line, pageW / 2, y, { align: "center" });
    y += 3.6;
  });
  return y + 1.5;
};

export const drawFooter = (doc, meta) => {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const y = pageH - 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(40);
  doc.text(`${meta.generatedBy}: ${meta.userName || ""}`, 6, y);
  doc.setTextColor(90);
  doc.text(meta.generatedNote, pageW / 2, y, { align: "center" });
  doc.setTextColor(40);
  doc.text(`${meta.generatedOn}: ${meta.stamp}`, pageW - 6, y, { align: "right" });
  doc.setTextColor(0);
};

const paintCells = (doc, x, y, width, columns, values, rowH, bold) => {
  doc.setFont("helvetica", bold ? "bold" : "normal");
  doc.setFontSize(6.2);
  doc.setDrawColor(0);
  doc.rect(x, y, width, rowH);
  let cursor = x;
  columns.forEach((col, index) => {
    doc.line(cursor, y, cursor, y + rowH);
    const text = clipText(doc, values?.[index] ?? "", col.w - 1.1);
    const textX =
      col.align === "right"
        ? cursor + col.w - 0.6
        : col.align === "center"
          ? cursor + col.w / 2
          : cursor + 0.6;
    doc.text(text, textX, y + 3.5, {
      align: col.align === "left" ? "left" : col.align,
    });
    cursor += col.w;
  });
  doc.line(x + width, y, x + width, y + rowH);
};

export async function fillTable(doc, options) {
  const {
    meta,
    columns,
    rows = [],
    startX,
    drawHead,
    onProgress,
    rowH = 5.2,
  } = options;
  const width = columns.reduce((sum, col) => sum + col.w, 0);
  const pageH = doc.internal.pageSize.getHeight();
  let y = 0;

  const openPage = (fresh) => {
    if (fresh) doc.addPage();
    y = drawChrome(doc, meta);
    y = drawHead(doc, y, startX, width);
    drawFooter(doc, meta);
  };

  const ensure = (height) => {
    if (y + height > pageH - 10) openPage(true);
  };

  openPage(false);

  for (let i = 0; i < rows.length; i += 1) {
    const row = rows[i];
    ensure(rowH);
    if (row?.banner != null) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6.5);
      doc.rect(startX, y, width, rowH);
      doc.text(
        clipText(doc, row.banner, width - 2),
        row.align === "left" ? startX + 1.2 : startX + width / 2,
        y + 3.5,
        { align: row.align === "left" ? "left" : "center" },
      );
    } else {
      paintCells(doc, startX, y, width, columns, row?.values, rowH, !!row?.bold);
    }
    y += rowH;
    if (i > 0 && i % 250 === 0) {
      onProgress?.(i + 1, rows.length);
      await yieldUi();
    }
  }

  return y;
}

export async function fillPair(doc, options) {
  const {
    meta,
    columns,
    leftRows = [],
    rightRows = [],
    startX,
    drawHead,
    onProgress,
    rowH = 5.2,
  } = options;
  const width = columns.reduce((sum, col) => sum + col.w, 0);
  const rightX = startX + width;
  const pageH = doc.internal.pageSize.getHeight();
  const count = Math.max(leftRows.length, rightRows.length);
  let y = 0;

  const openPage = (fresh) => {
    if (fresh) doc.addPage();
    y = drawChrome(doc, meta);
    drawHead(doc, y, startX, rightX, width);
    y += options.headH || 7;
    drawFooter(doc, meta);
  };

  const ensure = (height) => {
    if (y + height > pageH - 10) openPage(true);
  };

  openPage(false);

  for (let i = 0; i < count; i += 1) {
    ensure(rowH);
    const left = leftRows[i] || { values: [] };
    const right = rightRows[i] || { values: [] };
    if (left.banner != null) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6.2);
      doc.rect(startX, y, width, rowH);
      doc.text(clipText(doc, left.banner, width - 2), startX + 1.2, y + 3.5);
    } else {
      paintCells(doc, startX, y, width, columns, left.values, rowH, !!left.bold);
    }
    if (right.banner != null) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6.2);
      doc.rect(rightX, y, width, rowH);
      doc.text(clipText(doc, right.banner, width - 2), rightX + 1.2, y + 3.5);
    } else {
      paintCells(doc, rightX, y, width, columns, right.values, rowH, !!right.bold);
    }
    y += rowH;
    if (i > 0 && i % 250 === 0) {
      onProgress?.(i + 1, count);
      await yieldUi();
    }
  }

  return { y, width: width * 2, startX };
}

export const drawColumnHead = (doc, y, x, columns, headH = 7) => {
  const width = columns.reduce((sum, col) => sum + col.w, 0);
  doc.setFillColor(243, 244, 246);
  doc.rect(x, y, width, headH, "F");
  doc.setDrawColor(0);
  doc.rect(x, y, width, headH);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(6);
  let cursor = x;
  columns.forEach((col) => {
    doc.line(cursor, y, cursor, y + headH);
    const text = clipText(doc, col.title, col.w - 1.2);
    const textX =
      col.align === "right"
        ? cursor + col.w - 0.7
        : col.align === "center"
          ? cursor + col.w / 2
          : cursor + 0.7;
    doc.text(text, textX, y + 4.4, {
      align: col.align === "left" ? "left" : col.align,
    });
    cursor += col.w;
  });
  doc.line(x + width, y, x + width, y + headH);
  return y + headH;
};

export const drawDenomPage = (doc, meta, denomData, t) => {
  doc.addPage();
  let y = drawChrome(doc, meta);
  drawFooter(doc, meta);
  const cols = [
    { title: label(t, "report.cashbook.print.slNo", "Sl. NO."), w: 14, align: "center" },
    { title: label(t, "report.cashbook.print.denomination", "Denomination"), w: 36, align: "center" },
    { title: label(t, "report.cashbook.print.quantity", "Quantity"), w: 24, align: "center" },
    { title: label(t, "report.cashbook.print.value", "Value"), w: 28, align: "center" },
  ];
  const width = cols.reduce((sum, col) => sum + col.w, 0);
  const x = 20;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(label(t, "report.cashbook.physicalDenomination", "Physical Denomination"), x + width / 2, y, {
    align: "center",
  });
  y += 4;
  y = drawColumnHead(doc, y, x, cols);

  const paint = (values, bold = false) => {
    paintCells(doc, x, y, width, cols, values, 5.2, bold);
    y += 5.2;
  };

  (denomData || []).forEach((denom, index) => {
    paint([
      String(index + 1),
      denom?.Denom_Label ?? "",
      denom?.Denom_Balance ?? "",
      denom?.Denom_Value ?? "",
    ]);
  });
  const total = (denomData || []).reduce(
    (sum, current) => sum + parseFloat(current?.Denom_Value || 0),
    0,
  );
  paint(["", label(t, "common.total", "Total"), "", money(total)], true);
};

export const padPair = (left, right) => {
  const count = Math.max(left.length, right.length);
  while (left.length < count) left.push({ values: [] });
  while (right.length < count) right.push({ values: [] });
  return [left, right];
};
