import jsPDF from "jspdf";
import { format } from "date-fns";
import getCookieData from "@/utils/getCookieData";

const money = (value) => {
  if (value == null || value === "") return "";
  const numeric = Number(value);
  return Number.isNaN(numeric) ? String(value) : numeric.toFixed(2);
};

const day = (value) => {
  if (!value) return "";
  const parsed = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(parsed.getTime())) return String(value);
  return format(parsed, "dd-MM-yyyy");
};

const clipText = (doc, text, maxWidth) => {
  const value = String(text ?? "");
  if (!value) return "";
  if (doc.getTextWidth(value) <= maxWidth) return value;
  let end = value.length;
  while (end > 1 && doc.getTextWidth(`${value.slice(0, end)}…`) > maxWidth) {
    end -= 1;
  }
  return `${value.slice(0, end)}…`;
};

const yieldUi = () => new Promise((resolve) => setTimeout(resolve, 0));

const drawPageChrome = (doc, meta) => {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 6;
  let y = 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(String(meta.orgName || ""), pageW / 2, y, { align: "center" });
  y += 4;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  [meta.branchName, meta.address, meta.regNo].filter(Boolean).forEach((line) => {
    doc.text(String(line), pageW / 2, y, { align: "center" });
    y += 3.4;
  });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(meta.title, pageW / 2, y, { align: "center" });
  return y + 4;
};

const drawFooter = (doc, meta) => {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const y = pageH - 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(40);
  doc.text(`Generated By: ${meta.userName || ""}`, 6, y);
  doc.setTextColor(90);
  doc.text("This report is generated by PrioSuite.", pageW / 2, y, {
    align: "center",
  });
  doc.setTextColor(40);
  doc.text(`Generated On: ${meta.stamp}`, pageW - 6, y, { align: "right" });
  doc.setTextColor(0);
};

const label = (t, key, fallback) => {
  if (typeof t !== "function") return fallback;
  const value = t(key);
  return value && value !== key ? value : fallback;
};

const buildColumns = (showData, t) => {
  if (showData === "105") {
    return [
      { title: label(t, "deposit.reports.print.slNo", "SL. NO."), w: 14, align: "center", get: (_r, i) => String(i + 1) },
      { title: label(t, "deposit.reports.print.date", "DATE"), w: 26, align: "center", get: (r) => day(r?.Opening_Date) },
      { title: label(t, "deposit.reports.print.customerName", "CUSTOMER NAME"), w: 46, align: "left", get: (r) => r?.Full_Name },
      { title: label(t, "deposit.reports.print.guardianName", "GUARDIAN NAME"), w: 42, align: "left", get: (r) => r?.Relation_Name },
      { title: label(t, "deposit.reports.print.accountNo", "ACCOUNT NO."), w: 30, align: "center", get: (r) => r?.Account_No },
      { title: label(t, "deposit.reports.print.refAcNo", "REF. AC. NO."), w: 26, align: "center", get: (r) => r?.Ref_Ac_No },
      { title: label(t, "deposit.reports.print.lfNo", "L/F. NO."), w: 20, align: "center", get: (r) => r?.Ledg_Folio },
      { title: label(t, "deposit.reports.print.nominee", "NOMINEE"), w: 44, align: "left", get: (r) => r?.Nominee_Name },
      { title: label(t, "deposit.reports.print.operationMode", "OPERATION MODE"), w: 37, align: "center", get: (r) => r?.Operation_Mode },
    ];
  }

  if (showData === "107") {
    return [
      { title: label(t, "deposit.reports.print.slNo", "SL. NO."), w: 16, align: "center", get: (_r, i) => String(i + 1) },
      { title: label(t, "deposit.reports.print.date", "DATE"), w: 28, align: "center", get: (r) => day(r?.Closing_Date) },
      { title: label(t, "deposit.reports.print.customerName", "CUSTOMER NAME"), w: 52, align: "left", get: (r) => r?.Full_Name },
      { title: label(t, "deposit.reports.print.guardianName", "GUARDIAN NAME"), w: 48, align: "left", get: (r) => r?.Relation_Name },
      { title: label(t, "deposit.reports.print.accountNo", "ACCOUNT NO."), w: 36, align: "center", get: (r) => r?.Account_No },
      { title: label(t, "deposit.reports.print.refAcNo", "REF. AC. NO."), w: 30, align: "center", get: (r) => r?.Ref_Ac_No },
      { title: label(t, "deposit.reports.print.lfNo", "L/F. NO."), w: 24, align: "center", get: (r) => r?.Ledg_Folio },
      { title: label(t, "deposit.reports.print.operationMode", "OPERATION MODE"), w: 51, align: "center", get: (r) => r?.Operation_Mode },
    ];
  }

  if (showData === "109") {
    return [
      { title: label(t, "deposit.reports.print.slNo", "SL. NO."), w: 14, align: "center", get: (_r, i) => String(i + 1) },
      { title: label(t, "deposit.reports.print.date", "DATE"), w: 24, align: "center", get: (r) => day(r?.Adm_Date) },
      { title: label(t, "deposit.reports.print.customerName", "CUSTOMER NAME"), w: 32, align: "left", get: (r) => r?.Member_Type },
      { title: label(t, "deposit.reports.print.accountNo", "ACCOUNT NO."), w: 28, align: "center", get: (r) => r?.Full_Name },
      { title: label(t, "deposit.reports.print.refAcNo", "REF. AC. NO."), w: 24, align: "center", get: (r) => r?.Relation_Name },
      { title: label(t, "deposit.reports.print.lfNo", "L/F. NO."), w: 18, align: "center", get: (r) => r?.Village },
      { title: label(t, "deposit.reports.print.amount", "AMOUNT"), w: 22, align: "right", get: (r) => r?.Ledg_Folio },
      { title: label(t, "deposit.reports.print.narration", "NARRATION"), w: 36, align: "left", get: (r) => r?.Adm_Fees },
    ];
  }

  if (showData === "106") {
    return [
      { title: label(t, "deposit.reports.print.slNo", "SL. NO."), w: 12, align: "center", key: "sl" },
      { title: label(t, "deposit.reports.print.customerName", "CUSTOMER NAME"), w: 40, align: "left", key: "name" },
      { title: label(t, "deposit.reports.print.accountNo", "ACCOUNT NO."), w: 28, align: "center", key: "acc" },
      { title: label(t, "deposit.reports.print.refAcNo", "REF. AC. NO."), w: 22, align: "center", key: "ref" },
      { title: label(t, "deposit.reports.print.lfNo", "L/F. NO."), w: 16, align: "center", key: "lf" },
      { title: label(t, "deposit.reports.print.transMode", "TRANS. MODE"), w: 24, align: "center", key: "type" },
      { title: label(t, "deposit.reports.print.deposit", "DEPOSIT"), w: 28, align: "right", key: "dep" },
      { title: label(t, "deposit.reports.print.withdrawn", "WITHDRAWN"), w: 28, align: "right", key: "wd" },
      { title: label(t, "deposit.reports.print.interest", "INTEREST"), w: 24, align: "right", key: "intt" },
      { title: label(t, "deposit.reports.print.narration", "NARRATION"), w: 63, align: "left", key: "narr" },
    ];
  }

  return [
    { title: t("deposit.reports.print.slNo", "Sl"), w: 10, align: "center", get: (_r, i) => String(i + 1) },
    { title: t("deposit.reports.print.customerName", "Customer"), w: 32, align: "left", get: (r) => r?.Full_Name },
    { title: t("deposit.reports.print.guardianName", "Guardian"), w: 30, align: "left", get: (r) => r?.Relation_Name },
    { title: t("deposit.reports.print.accNo", "A/c"), w: 22, align: "center", get: (r) => r?.Account_No },
    { title: t("deposit.reports.print.refAcNo", "Ref"), w: 16, align: "center", get: (r) => r?.Ref_Ac_No },
    { title: t("deposit.reports.print.lfNo", "LF"), w: 12, align: "center", get: (r) => r?.Ledg_Folio },
    { title: t("deposit.reports.print.openingDate", "Open"), w: 20, align: "center", get: (r) => day(r?.Opening_Date) },
    { title: t("deposit.reports.print.roi", "ROI"), w: 12, align: "center", get: (r) => r?.ROI },
    { title: t("deposit.reports.print.maturityDate", "Mature"), w: 20, align: "center", get: (r) => day(r?.Maturity_Date) },
    { title: t("deposit.reports.print.opening", "Opening"), w: 18, align: "right", get: (r) => money(r?.Opening) },
    { title: t("deposit.reports.print.deposit", "Deposit"), w: 18, align: "right", get: (r) => money(r?.Deposit) },
    { title: t("deposit.reports.print.withdrawn", "Withdrawn"), w: 20, align: "right", get: (r) => money(r?.Withdrwan) },
    { title: t("deposit.reports.print.closing", "Closing"), w: 18, align: "right", get: (r) => money(r?.Closing) },
    { title: t("deposit.reports.print.paidIntt", "Paid Intt"), w: 18, align: "right", get: (r) => money(r?.Paid_Intt) },
    { title: t("deposit.reports.print.dueIntt", "Due Intt"), w: 19, align: "right", get: (r) => money(r?.Due_Intt) },
  ];
};

const flattenTransactions = (groups = []) => {
  const rows = [];
  groups.forEach((group) => {
    if (group?.isGrandTotal) return;
    rows.push({
      kind: "banner",
      text: group?.date ? day(group.date) : "",
    });
    (group?.transactions || []).forEach((txn, index) => {
      rows.push({
        kind: "cells",
        cells: {
          sl: String(index + 1),
          name: txn?.Full_Name || "",
          acc: txn?.Account_No || "",
          ref: txn?.Ref_Ac_No || "",
          lf: txn?.Ledg_Folio || "",
          type: txn?.Trans_Type || "",
          dep: money(txn?.Deposit),
          wd: money(txn?.Withdrwan),
          intt: money(txn?.Interest),
          narr: txn?.Narration || "",
        },
      });
    });
    rows.push({
      kind: "total",
      label: "Sub Total",
      dep: money(group?.subtotalDeposit),
      wd: money(group?.subtotalWithdrawn),
      intt: money(group?.subtotalInterest),
    });
  });

  const grand = groups.find((group) => group?.isGrandTotal);
  if (grand) {
    rows.push({
      kind: "total",
      label: "Grand Total",
      bold: true,
      dep: money(grand.grandTotalDeposit),
      wd: money(grand.grandTotalWithdrawn),
      intt: money(grand.grandTotalInterest),
    });
  }
  return rows;
};

export const downloadDepositReportPdf = async ({
  showData,
  tableData,
  fromDate,
  toDate,
  docTitle,
  t,
  totals,
  onProgress,
}) => {
  const landscape = showData !== "109";
  const doc = new jsPDF({
    orientation: landscape ? "landscape" : "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  const now = new Date();
  const meta = {
    orgName: getCookieData("userOrgName") || "",
    branchName: getCookieData("userBranchName") || "",
    address: getCookieData("userOrgAddress") || "",
    regNo: getCookieData("userOrgRegistration") || "",
    userName: getCookieData("userName") || "",
    stamp: format(now, "dd-MM-yyyy hh:mm:ss a"),
    title: "",
  };

  const range = `${day(fromDate)} To ${day(toDate)}`;
  const titles = {
    "105": `Account Opening Register From ${range}`,
    "106": `Deposit Transaction Register From ${range}`,
    "107": `Account Closing Register From ${range}`,
    "108": `Account Detailed List From ${range}`,
    "109": `Interest Ledger From ${range}`,
  };
  meta.title = titles[showData] || "Deposit Report";

  const columns = buildColumns(showData, t || ((key, fallback) => fallback || key));
  const usable = columns.reduce((sum, col) => sum + col.w, 0);
  const margin = 6;
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const startX = Math.max(margin, (pageW - usable) / 2);
  const rowH = 5.2;
  const headH = 7;

  const rows =
    showData === "106" ? flattenTransactions(tableData) : tableData || [];

  const drawHead = (y) => {
    let x = startX;
    doc.setFillColor(243, 244, 246);
    doc.rect(startX, y, usable, headH, "F");
    doc.setDrawColor(0);
    doc.rect(startX, y, usable, headH);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    columns.forEach((col) => {
      doc.line(x, y, x, y + headH);
      const label = clipText(doc, col.title, col.w - 1.4);
      const textX =
        col.align === "right" ? x + col.w - 0.8 : col.align === "center" ? x + col.w / 2 : x + 0.8;
      doc.text(label, textX, y + 4.4, {
        align: col.align === "left" ? "left" : col.align,
      });
      x += col.w;
    });
    doc.line(startX + usable, y, startX + usable, y + headH);
    return y + headH;
  };

  let y = drawPageChrome(doc, meta);
  y = drawHead(y);
  drawFooter(doc, meta);

  const newPage = () => {
    doc.addPage();
    y = drawPageChrome(doc, meta);
    y = drawHead(y);
    drawFooter(doc, meta);
  };

  const ensureSpace = (height) => {
    if (y + height > pageH - 10) newPage();
  };

  const paintCells = (values, bold = false) => {
    ensureSpace(rowH);
    let x = startX;
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(6.5);
    doc.rect(startX, y, usable, rowH);
    columns.forEach((col, index) => {
      doc.line(x, y, x, y + rowH);
      const raw = values[index] ?? "";
      const text = clipText(doc, raw, col.w - 1.2);
      const textX =
        col.align === "right" ? x + col.w - 0.7 : col.align === "center" ? x + col.w / 2 : x + 0.7;
      doc.text(text, textX, y + 3.5, {
        align: col.align === "left" ? "left" : col.align,
      });
      x += col.w;
    });
    doc.line(startX + usable, y, startX + usable, y + rowH);
    y += rowH;
  };

  for (let i = 0; i < rows.length; i += 1) {
    const row = rows[i];

    if (showData === "106") {
      if (row.kind === "banner") {
        ensureSpace(rowH);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7);
        doc.rect(startX, y, usable, rowH);
        doc.text(String(row.text || ""), startX + 2, y + 3.5);
        y += rowH;
      } else if (row.kind === "total") {
        const values = columns.map((col) => {
          if (col.key === "name") return row.label;
          if (col.key === "dep") return row.dep;
          if (col.key === "wd") return row.wd;
          if (col.key === "intt") return row.intt;
          return "";
        });
        paintCells(values, true);
      } else {
        paintCells(columns.map((col) => row.cells?.[col.key] ?? ""));
      }
    } else {
      paintCells(columns.map((col) => col.get?.(row, i) ?? ""));
    }

    if (i > 0 && i % 250 === 0) {
      onProgress?.(i + 1, rows.length);
      await yieldUi();
    }
  }

  if (showData === "108") {
    paintCells(
      [
        "Total",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        money(totals?.totalOpening),
        money(totals?.totalDeposit),
        money(totals?.totalWithdrawn),
        money(totals?.totalClosing),
        money(totals?.totalPaidIntt),
        money(totals?.totalDueIntt),
      ],
      true,
    );
  } else if (showData === "109" && totals?.totalAmount != null) {
    paintCells(
      ["Total", "", "", "", "", "", "", money(totals.totalAmount)],
      true,
    );
  }

  doc.save(`${docTitle}.pdf`);
};
