# -*- coding: utf-8 -*-
from pathlib import Path
import re
import json

root = Path(__file__).resolve().parents[1] / "components" / "loan"
all_found = set()
for p in sorted(root.rglob("*.jsx")):
    raw = p.read_text(encoding="utf-8")
    lines = [ln for ln in raw.splitlines() if not ln.strip().startswith("//")]
    t = "\n".join(lines)
    for m in re.finditer(
        r'(?:label|placeholder|searchPlaceholder|formLabel|title)="([^"]+)"', t
    ):
        all_found.add(m.group(1))
    for m in re.finditer(r"<h[1-6][^>]*>\s*([^<{]+)\s*</h[1-6]>", t):
        s = m.group(1).strip()
        if s:
            all_found.add(s)
    for m in re.finditer(r"<FormLabel[^>]*>\s*([^<{]+)\s*</FormLabel>", t):
        s = m.group(1).strip()
        if s:
            all_found.add(s)
    for m in re.finditer(r"<DialogTitle[^>]*>\s*([^<{]+)\s*</DialogTitle>", t):
        s = m.group(1).strip()
        if s:
            all_found.add(s)
    for m in re.finditer(r"<DialogHeader[^>]*>\s*([^<{]+)\s*</DialogHeader>", t):
        s = m.group(1).strip()
        if s:
            all_found.add(s)
    for m in re.finditer(r"<TableHead[^>]*>\s*([^<{]+)\s*</TableHead>", t):
        s = m.group(1).strip()
        if s:
            all_found.add(s)
    for m in re.finditer(r'label:\s*"([^"]+)"', t):
        all_found.add(m.group(1))
    for m in re.finditer(
        r'"(Add|Edit|Update|Submit|Save|Cancel|Print|Search|Close|Next|Reset|Clear|Run|Yes|No|Fetch Details|Remove)"',
        t,
    ):
        all_found.add(m.group(1))
    for m in re.finditer(r'toast\.(error|success)\("([^"]+)"', t):
        all_found.add(m.group(2))
    for m in re.finditer(r'toast\.(error|success)\(`([^`]+)`', t):
        all_found.add(m.group(2))
    for m in re.finditer(r"<Button[^>]*>\s*([^<{]+)\s*</Button>", t):
        s = m.group(1).strip()
        if s and not s.startswith("{"):
            all_found.add(s)
    for m in re.finditer(r"<th[^>]*>\s*([^<{]+)\s*</th>", t, re.I):
        s = m.group(1).strip()
        if s:
            all_found.add(s)
    for m in re.finditer(
        r"(Generated By:?|Generated On:?|This report is generated by PrioSuite\.|"
        r"Loan Disburse Register From|Loan Repayment Register From|Loan Detailed List From|"
        r"Grand Total|Subtotal|Sub Total|Total|"
        r"Loan Collection Receipt|Collection Receipt|No records found\.)",
        t,
    ):
        all_found.add(m.group(1))

out = Path(__file__).with_name("_loan_strings.json")
out.write_text(
    json.dumps(sorted(all_found), ensure_ascii=False, indent=2), encoding="utf-8"
)
print("wrote", out, "count", len(all_found))
