# -*- coding: utf-8 -*-
"""Extra scan for loan static strings not caught by extract-loan-strings."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1] / "components" / "loan"
patterns = [
    r'>(Generated By:?\s*)',
    r'>(Generated On:?\s*)',
    r'This report is generated by PrioSuite\.',
    r'Loan Disburse Register From',
    r'Loan Repayment Register From',
    r'Loan Detailed List From',
    r'Grand Total',
    r'Subtotal|Sub Total',
    r'toast\.(error|success)\((?:`|"|\')([^`"\']+)',
    r'options=\{\[[\s\S]*?\]\}',
    r'children:\s*"([^"]+)"',
    r'>\s*(Print|Search|Close|Cancel|Submit|Save|Reset|Next|Add|Remove|Yes|No|Download|Preview)\s*<',
]

for p in sorted(root.rglob("*.jsx")):
    t = p.read_text(encoding="utf-8")
    hits = []
    for pat in patterns:
        for m in re.finditer(pat, t):
            hits.append(m.group(0)[:120].replace("\n", " "))
    if hits:
        print("==", p.relative_to(root).as_posix())
        for h in hits[:30]:
            print(" ", h)
