# -*- coding: utf-8 -*-
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
LOC = ROOT / "i18n" / "locales"

KEYS = {
    "en": {
        "bankReport": "Bank Report",
        "slNo": "Sl No.",
        "opening": "Opening",
        "deposit": "Deposit",
        "withdrawn": "Withdrawn",
        "closing": "Closing",
        "gl": "GL",
        "subtotal": "Subtotal",
        "subTotal": "Sub Total",
        "grandTotal": "Grand Total",
        "searchReportType": "Search report type...",
        "branch": "Branch",
        "selectBranch": "Select branch",
        "searchBranch": "Search branch...",
        "detailedListFrom": "Bank Detailed List From",
        "to": "To",
        "generatedBy": "Generated By :",
        "generatedOn": "Generated On :",
        "reportGeneratedByPrioSuite": "This report is generated by PrioSuite.",
    },
    "hi": {
        "bankReport": "बैंक रिपोर्ट",
        "slNo": "क्रमांक",
        "opening": "प्रारंभिक",
        "deposit": "जमा",
        "withdrawn": "निकासी",
        "closing": "समापन",
        "gl": "GL",
        "subtotal": "उप योग",
        "subTotal": "उप योग",
        "grandTotal": "कुल योग",
        "searchReportType": "रिपोर्ट प्रकार खोजें...",
        "branch": "शाखा",
        "selectBranch": "शाखा चुनें",
        "searchBranch": "शाखा खोजें...",
        "detailedListFrom": "बैंक विस्तृत सूची से",
        "to": "से",
        "generatedBy": "द्वारा जनरेट :",
        "generatedOn": "जनरेट तिथि :",
        "reportGeneratedByPrioSuite": "यह रिपोर्ट PrioSuite द्वारा जनरेट की गई है।",
    },
    "bn": {
        "bankReport": "ব্যাংক রিপোর্ট",
        "slNo": "ক্রমিক নং",
        "opening": "প্রারম্ভিক",
        "deposit": "জমা",
        "withdrawn": "উত্তোলন",
        "closing": "সমাপনী",
        "gl": "GL",
        "subtotal": "উপমোট",
        "subTotal": "উপমোট",
        "grandTotal": "সর্বমোট",
        "searchReportType": "রিপোর্টের ধরন অনুসন্ধান করুন...",
        "branch": "শাখা",
        "selectBranch": "শাখা নির্বাচন করুন",
        "searchBranch": "শাখা অনুসন্ধান করুন...",
        "detailedListFrom": "ব্যাংক বিস্তারিত তালিকা থেকে",
        "to": "থেকে",
        "generatedBy": "তৈরি করেছেন :",
        "generatedOn": "তৈরির তারিখ :",
        "reportGeneratedByPrioSuite": "এই রিপোর্ট PrioSuite দ্বারা তৈরি।",
    },
    "or": {
        "bankReport": "ବ୍ୟାଙ୍କ ରିପୋର୍ଟ",
        "slNo": "କ୍ରମିକ ନମ୍ବର",
        "opening": "ଆରମ୍ଭିକ",
        "deposit": "ଜମା",
        "withdrawn": "ଉଠାଣ",
        "closing": "ବନ୍ଦ",
        "gl": "GL",
        "subtotal": "ଉପ ମୋଟ",
        "subTotal": "ଉପ ମୋଟ",
        "grandTotal": "ସର୍ବମୋଟ",
        "searchReportType": "ରିପୋର୍ଟ ପ୍ରକାର ଖୋଜନ୍ତୁ...",
        "branch": "ଶାଖା",
        "selectBranch": "ଶାଖା ଚୟନ କରନ୍ତୁ",
        "searchBranch": "ଶାଖା ଖୋଜନ୍ତୁ...",
        "detailedListFrom": "ବ୍ୟାଙ୍କ ବିସ୍ତୃତ ତାଲିକା ରୁ",
        "to": "ଠାରୁ",
        "generatedBy": "ତିଆରି କରିଛନ୍ତି :",
        "generatedOn": "ତିଆରି ତାରିଖ :",
        "reportGeneratedByPrioSuite": "ଏହି ରିପୋର୍ଟ PrioSuite ଦ୍ୱାରା ତିଆରି।",
    },
}

PRINT = {
    "en": {
        "slNo": "SL. NO.",
        "bankName": "BANK NAME",
        "accountNo": "ACCOUNT NO.",
        "accountType": "ACCOUNT TYPE",
        "opening": "OPENING",
        "deposit": "DEPOSIT",
        "withdrawn": "WITHDRAWN",
        "closing": "CLOSING",
    },
    "hi": {
        "slNo": "क्रमांक",
        "bankName": "बैंक का नाम",
        "accountNo": "खाता संख्या",
        "accountType": "खाते का प्रकार",
        "opening": "प्रारंभिक",
        "deposit": "जमा",
        "withdrawn": "निकासी",
        "closing": "समापन",
    },
    "bn": {
        "slNo": "ক্রমিক নং",
        "bankName": "ব্যাংকের নাম",
        "accountNo": "অ্যাকাউন্ট নম্বর",
        "accountType": "অ্যাকাউন্টের ধরন",
        "opening": "প্রারম্ভিক",
        "deposit": "জমা",
        "withdrawn": "উত্তোলন",
        "closing": "সমাপনী",
    },
    "or": {
        "slNo": "କ୍ରମିକ ନମ୍ବର",
        "bankName": "ବ୍ୟାଙ୍କ ନାମ",
        "accountNo": "ଆକାଉଣ୍ଟ ନମ୍ବର",
        "accountType": "ଆକାଉଣ୍ଟ ପ୍ରକାର",
        "opening": "ଆରମ୍ଭିକ",
        "deposit": "ଜମା",
        "withdrawn": "ଉଠାଣ",
        "closing": "ବନ୍ଦ",
    },
}


def dump_obj(d: dict, indent=6) -> str:
    sp = " " * indent
    lines = []
    for k, v in d.items():
        lines.append(f"{sp}{k}: {json.dumps(v, ensure_ascii=False)},")
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)


def patch(lang: str):
    path = LOC / f"{lang}.js"
    text = path.read_text(encoding="utf-8")
    bi = text.rfind("\n    bank: {")
    i = text.find("{", bi)
    depth = 0
    end = None
    for j in range(i, len(text)):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                end = j
                break
    chunk = text[i:end]
    missing = {k: v for k, v in KEYS[lang].items() if f"{k}:" not in chunk}
    body = chunk.rstrip()
    if not body.endswith(","):
        body = re.sub(r'(")\s*$', r"\1,", body)

    inserts = []
    if missing:
        inserts.append(
            "".join(
                f"\n      {k}: {json.dumps(v, ensure_ascii=False)},"
                for k, v in missing.items()
            ).rstrip(",")
        )

    if "print: {" not in chunk:
        print_block = (
            ",\n      print: {\n"
            + dump_obj(PRINT[lang], 8)
            + "\n      }"
        )
        inserts.append(print_block)

    if not inserts:
        print(lang, "already")
        return

    new_chunk = body + "".join(inserts) + "\n    "
    text = text[:i] + new_chunk + text[end:]
    path.write_text(text, encoding="utf-8")
    print(lang, "updated", list(missing), "print" if "print: {" not in chunk else "")


for lang in ("en", "hi", "bn", "or"):
    patch(lang)
