# -*- coding: utf-8 -*-
"""Fix loan locale values that wrongly include trailing colons on form/table keys."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
LOC = ROOT / "i18n" / "locales"
LOAN = ROOT / "components" / "loan"

# Base keys that must NOT end with colon (forms / tables)
STRIP = {
    "accountNo": "Account No.",
    "memberName": "Member Name",
    "guardianName": "Guardian Name",
    "memberNo": "Member No.",
    "refAcNo": "Ref. Ac. No.",
    "productName": "Product Name",
    "issueAmount": "Issue Amount",
    "issueDate": "Issue Date",
    "disbAmount": "Disb. Amount",
    "disbDate": "Disb. Date",
    "ledgerFolio": "Ledger Folio",
    "repayMode": "Repay Mode",
    "repayWithin": "Repay Within",
    "maxLoan": "Max Loan",
    "tFPaid": "TF Paid",
    "gFBalance": "GF Balance",
    "outsBal": "Outs. Bal.",
    "cPBal": "CP Bal",
    "cIBal": "CI Bal",
    "oPBal": "OP Bal",
    "oIBal": "OI Bal",
}

# Keep these WITH colon (receipt / generated lines per @text)
KEEP_COLON = {
    "generatedBy": "Generated By:",
    "generatedOn": "Generated On:",
    "receivedMode": "Received Mode :",
    "receivedBy": "Received By :",
    "printedOn": "Printed On :",
}

# Translations for stripped keys (HI/BN/OR) — without trailing colon
STRIP_TR = {
    "hi": {
        "accountNo": "खाता संख्या",
        "memberName": "सदस्य का नाम",
        "guardianName": "अभिभावक का नाम",
        "memberNo": "सदस्य संख्या",
        "refAcNo": "संदर्भ खाता संख्या",
        "productName": "उत्पाद का नाम",
        "issueAmount": "जारी राशि",
        "issueDate": "जारी तिथि",
        "disbAmount": "वितरण राशि",
        "disbDate": "वितरण तिथि",
        "ledgerFolio": "लेजर फोलियो",
        "repayMode": "चुकौती मोड",
        "repayWithin": "चुकौती अवधि",
        "maxLoan": "अधिकतम ऋण",
        "tFPaid": "TF भुगतान",
        "gFBalance": "GF शेष",
        "outsBal": "बकाया शेष",
        "cPBal": "CP शेष",
        "cIBal": "CI शेष",
        "oPBal": "OP शेष",
        "oIBal": "OI शेष",
        "generatedBy": "द्वारा जनरेट:",
        "generatedOn": "जनरेट तिथि:",
        "receivedMode": "प्राप्ति मोड :",
        "receivedBy": "प्राप्तकर्ता :",
        "printedOn": "प्रिंट तिथि :",
    },
    "bn": {
        "accountNo": "অ্যাকাউন্ট নম্বর",
        "memberName": "সদস্যের নাম",
        "guardianName": "অভিভাবকের নাম",
        "memberNo": "সদস্য নম্বর",
        "refAcNo": "রেফারেন্স অ্যাকাউন্ট নম্বর",
        "productName": "পণ্যের নাম",
        "issueAmount": "ইস্যু পরিমাণ",
        "issueDate": "ইস্যু তারিখ",
        "disbAmount": "বিতরণ পরিমাণ",
        "disbDate": "বিতরণ তারিখ",
        "ledgerFolio": "লেজার ফোলিও",
        "repayMode": "পরিশোধ মোড",
        "repayWithin": "পরিশোধের সময়সীমা",
        "maxLoan": "সর্বোচ্চ ঋণ",
        "tFPaid": "TF পরিশোধ",
        "gFBalance": "GF ব্যালেন্স",
        "outsBal": "বকেয়া ব্যালেন্স",
        "cPBal": "CP ব্যালেন্স",
        "cIBal": "CI ব্যালেন্স",
        "oPBal": "OP ব্যালেন্স",
        "oIBal": "OI ব্যালেন্স",
        "generatedBy": "তৈরি করেছেন:",
        "generatedOn": "তৈরির তারিখ:",
        "receivedMode": "প্রাপ্তি মোড :",
        "receivedBy": "গ্রহণকারী :",
        "printedOn": "প্রিন্ট তারিখ :",
    },
    "or": {
        "accountNo": "ଖାତା ନମ୍ବର",
        "memberName": "ସଦସ୍ୟ ନାମ",
        "guardianName": "ଅଭିଭାବକ ନାମ",
        "memberNo": "ସଦସ୍ୟ ନମ୍ବର",
        "refAcNo": "ରେଫରେନ୍ସ ଖାତା ନମ୍ବର",
        "productName": "ଉତ୍ପାଦ ନାମ",
        "issueAmount": "ଇସ୍ୟୁ ରାଶି",
        "issueDate": "ଇସ୍ୟୁ ତାରିଖ",
        "disbAmount": "ବିତରଣ ରାଶି",
        "disbDate": "ବିତରଣ ତାରିଖ",
        "ledgerFolio": "ଲେଜର ଫୋଲିଓ",
        "repayMode": "ପରିଶୋଧ ମୋଡ୍",
        "repayWithin": "ପରିଶୋଧ ସମୟସୀମା",
        "maxLoan": "ସର୍ବାଧିକ ଋଣ",
        "tFPaid": "TF ପରିଶୋଧ",
        "gFBalance": "GF ବାଲାନ୍ସ",
        "outsBal": "ବକେୟା ବାଲାନ୍ସ",
        "cPBal": "CP ବାଲାନ୍ସ",
        "cIBal": "CI ବାଲାନ୍ସ",
        "oPBal": "OP ବାଲାନ୍ସ",
        "oIBal": "OI ବାଲାନ୍ସ",
        "generatedBy": "ତିଆରି କରିଛନ୍ତି:",
        "generatedOn": "ତିଆରି ତାରିଖ:",
        "receivedMode": "ପ୍ରାପ୍ତି ମୋଡ୍ :",
        "receivedBy": "ଗ୍ରହଣକାରୀ :",
        "printedOn": "ପ୍ରିଣ୍ଟ ତାରିଖ :",
    },
}


def set_key(text: str, key: str, value: str) -> str:
    # Only inside loan block
    di = text.rfind("\n    loan: {")
    if di < 0:
        return text
    # find end of loan roughly at memberSearch
    end = text.find("\n    memberSearch:", di)
    if end < 0:
        end = len(text)
    chunk = text[di:end]
    pat = re.compile(rf'(\n\s+{re.escape(key)}:\s*)"(?:\\.|[^"\\])*"')
    if not pat.search(chunk):
        return text
    new_chunk = pat.sub(lambda m: m.group(1) + json_dumps(value), chunk, count=1)
    return text[:di] + new_chunk + text[end:]


def json_dumps(s: str) -> str:
    import json
    return json.dumps(s, ensure_ascii=False)


def ensure_colon_keys(text: str, lang: str) -> str:
    """Ensure *Colon variants exist for print layouts."""
    colon_en = {
        "accountNoColon": "Account No. : ",
        "memberNameColon": "Member Name : ",
        "guardianNameColon": "Guardian Name : ",
        "memberNoColon": "Member No : ",
        "refAcNoColon": "Ref. Ac. No. : ",
        "productNameColon": "Product Name : ",
        "issueAmountColon": "Issue Amount : ",
        "issueDateColon": "Issue Date : ",
        "disbAmountColon": "Disb. Amount : ",
        "disbDateColon": "Disb. Date : ",
        "ledgerFolioColon": "Ledger Folio : ",
        "repayModeColon": "Repay Mode : ",
        "repayWithinColon": "Repay Within : ",
        "maxLoanColon": "Max Loan : ",
        "tFPaidColon": "TF Paid : ",
        "gFBalanceColon": "GF Balance : ",
        "outsBalColon": "Outs. Bal. : ",
        "cPBalColon": "CP Bal : ",
        "cIBalColon": "CI Bal : ",
        "oPBalColon": "OP Bal : ",
        "oIBalColon": "OI Bal : ",
        "generatedByColon": "Generated By: ",
        "generatedOnColon": "Generated On: ",
    }
    # For non-en, append " : " / ": " to translated base if missing
    di = text.rfind("\n    loan: {")
    end = text.find("\n    memberSearch:", di)
    chunk = text[di:end]
    inserts = []
    for k, v in colon_en.items():
        if f"{k}:" in chunk:
            continue
        if lang != "en":
            base = k.replace("Colon", "")
            # try read base from already-updated values later — use EN colon for missing
            v = colon_en[k]
        inserts.append(f',\n        {k}: {json_dumps(v)}')
    if not inserts:
        return text
    # insert before closing of loan — before print: or before last }
    # find `print: {` inside loan and insert before it, else before end
    pi = chunk.find("\n        print: {")
    if pi < 0:
        # before end
        return text[:end] + "".join(inserts) + text[end:]
    abs_pi = di + pi
    return text[:abs_pi] + "".join(inserts) + text[abs_pi:]


def patch_locales():
    for lang in ("en", "hi", "bn", "or"):
        path = LOC / f"{lang}.js"
        text = path.read_text(encoding="utf-8")
        if lang == "en":
            for k, v in STRIP.items():
                text = set_key(text, k, v)
            for k, v in KEEP_COLON.items():
                text = set_key(text, k, v)
        else:
            tr = STRIP_TR[lang]
            for k, v in tr.items():
                text = set_key(text, k, v)
        text = ensure_colon_keys(text, lang)
        path.write_text(text, encoding="utf-8")
        print("locale", lang)


# Preview/print components that need Colon keys for display-with-value rows
PREVIEW_REPLACES = [
    ('t("loan.maxLoan")', 't("loan.maxLoanColon")'),
    ('t("loan.memberNo")', 't("loan.memberNoColon")'),
    ('t("loan.tFPaid")', 't("loan.tFPaidColon")'),
    ('t("loan.gFBalance")', 't("loan.gFBalanceColon")'),
    ('t("loan.outsBal")', 't("loan.outsBalColon")'),
    ('t("loan.cPBal")', 't("loan.cPBalColon")'),
    ('t("loan.cIBal")', 't("loan.cIBalColon")'),
    ('t("loan.oPBal")', 't("loan.oPBalColon")'),
    ('t("loan.oIBal")', 't("loan.oIBalColon")'),
]


def patch_preview_files():
    files = [
        LOAN / "guarantorDetails" / "index.jsx",
        LOAN / "guarantorDetails" / "GuarantorDetailsPreview.jsx",
        LOAN / "generateSchedule" / "GenerateSchedulePreview.jsx",
        LOAN / "accountStatement" / "PreviewModal.jsx",
    ]
    # In these files, print-style rows using base keys for labels-with-values
    # should use Colon variants. Careful: table heads must stay base.
    for path in files:
        t = path.read_text(encoding="utf-8")
        orig = t
        # Only replace inside font-semibold text-nowrap paragraphs (print labels)
        def repl_p(m):
            inner = m.group(0)
            for a, b in [
                ('t("loan.accountNo")', 't("loan.accountNoColon")'),
                ('t("loan.memberName")', 't("loan.memberNameColon")'),
                ('t("loan.guardianName")', 't("loan.guardianNameColon")'),
                ('t("loan.memberNo")', 't("loan.memberNoColon")'),
                ('t("loan.refAcNo")', 't("loan.refAcNoColon")'),
                ('t("loan.productName")', 't("loan.productNameColon")'),
                ('t("loan.issueAmount")', 't("loan.issueAmountColon")'),
                ('t("loan.issueDate")', 't("loan.issueDateColon")'),
                ('t("loan.disbAmount")', 't("loan.disbAmountColon")'),
                ('t("loan.disbDate")', 't("loan.disbDateColon")'),
                ('t("loan.ledgerFolio")', 't("loan.ledgerFolioColon")'),
                ('t("loan.repayMode")', 't("loan.repayModeColon")'),
                ('t("loan.repayWithin")', 't("loan.repayWithinColon")'),
                ('t("loan.maxLoan")', 't("loan.maxLoanColon")'),
                ('t("loan.tFPaid")', 't("loan.tFPaidColon")'),
                ('t("loan.gFBalance")', 't("loan.gFBalanceColon")'),
                ('t("loan.outsBal")', 't("loan.outsBalColon")'),
                ('t("loan.cPBal")', 't("loan.cPBalColon")'),
                ('t("loan.cIBal")', 't("loan.cIBalColon")'),
                ('t("loan.oPBal")', 't("loan.oPBalColon")'),
                ('t("loan.oIBal")', 't("loan.oIBalColon")'),
            ]:
                inner = inner.replace(a, b)
            return inner

        t = re.sub(
            r'<p className="font-semibold text-nowrap">\{t\("loan\.[^"]+"\)\}</p>',
            repl_p,
            t,
        )
        if t != orig:
            path.write_text(t, encoding="utf-8")
            print("preview", path.relative_to(LOAN))


def main():
    patch_locales()
    patch_preview_files()
    print("done")


if __name__ == "__main__":
    main()
