# -*- coding: utf-8 -*-
"""Fix cashbook locale merge mistakes."""
from pathlib import Path
import re

LOC = Path(__file__).resolve().parents[1] / "i18n" / "locales"

VOUCHER_EXTRA = {
    "en": {"voucherNo": "Voucher No.", "refVcNo": "Ref. Vc. No"},
    "hi": {"voucherNo": "वाउचर संख्या", "refVcNo": "संदर्भ वाउचर संख्या"},
    "bn": {"voucherNo": "ভাউচার নম্বর", "refVcNo": "রেফ. ভাউচার নম্বর"},
    "or": {"voucherNo": "ଭାଉଚର୍ ନମ୍ବର", "refVcNo": "ରେଫ୍. ଭାଉଚର୍ ନମ୍ବର"},
}

COMMON_NEED = {
    "en": {
        "total": "Total",
        "generatedBy": "Generated By",
        "generatedOn": "Generated On",
        "sl": "Sl.",
    },
    "hi": {
        "total": "कुल",
        "generatedBy": "द्वारा निर्मित",
        "generatedOn": "निर्मित दिनांक",
        "sl": "क्र.",
    },
    "bn": {
        "total": "মোট",
        "generatedBy": "প্রস্তুত করেছেন",
        "generatedOn": "তৈরির তারিখ",
        "sl": "ক্র.",
    },
    "or": {
        "total": "ମୋଟ",
        "generatedBy": "ପ୍ରସ୍ତୁତକର୍ତ୍ତା",
        "generatedOn": "ପ୍ରସ୍ତୁତ ତାରିଖ",
        "sl": "କ୍ର.",
    },
}


def fix_lang(lang: str) -> None:
    path = LOC / f"{lang}.js"
    text = path.read_text(encoding="utf-8")

    # Remove wrongly inserted keys from provision
    text2 = re.sub(
        r',\n      voucherNo: "[^"]*",\n      refVcNo: "[^"]*"\n\n    \},\n    adjustmentVoucher:',
        "\n    },\n    adjustmentVoucher:",
        text,
    )
    if text2 == text:
        # try without blank line
        text2 = re.sub(
            r',\n      voucherNo: "[^"]*",\n      refVcNo: "[^"]*"\n    \},\n    adjustmentVoucher:',
            "\n    },\n    adjustmentVoucher:",
            text,
        )
    text = text2

    # Add voucherNo/refVcNo into voucher object (before its closing, before provision)
    vm = re.search(r"(\n    voucher: \{)([\s\S]*?)(\n    \},\n    provision:)", text)
    if not vm:
        raise SystemExit(f"{lang}: voucher block not found")
    body = vm.group(2)
    adds = []
    for k, v in VOUCHER_EXTRA[lang].items():
        if re.search(rf"\n      {k}:", body):
            continue
        esc = v.replace("\\", "\\\\").replace('"', '\\"')
        adds.append(f'      {k}: "{esc}"')
    if adds:
        body = body.rstrip()
        if body and not body.endswith(","):
            body += ","
        body = body + "\n" + ",\n".join(adds) + "\n"
        text = text[: vm.start(2)] + body + text[vm.end(2) :]
        print(f"{lang}: fixed voucher keys")
    else:
        print(f"{lang}: voucher keys already ok")

    # Add missing bank-era common keys: match LAST common before bank
    # Find all `    common: {` then take the one whose close is followed by bank
    cm = None
    for m in re.finditer(r"\n    common: \{", text):
        rest = text[m.end() :]
        close = re.search(r"\n    \},\n    bank:", rest)
        if close and close.start() < 5000:  # bank-era common is small
            cm = (m.end(), m.end() + close.start())
            break
        # Prefer the occurrence immediately before bank
    # Better: search backwards from bank
    bank = text.find("\n    bank: {")
    if bank < 0:
        raise SystemExit(f"{lang}: bank not found")
    # find preceding `    common: {`
    common_start = text.rfind("\n    common: {", 0, bank)
    if common_start < 0:
        raise SystemExit(f"{lang}: common before bank not found")
    body_start = common_start + len("\n    common: {")
    body_end = bank  # includes `\n    },`
    # trim to just inside common
    close_m = re.search(r"\n    \},$", text[body_start:bank], re.M)
    # body is from body_start to the `},` before bank
    pre = text[body_start:bank]
    # pre ends with `\n    },`
    inner_end = pre.rfind("\n    },")
    body = pre[:inner_end]
    adds = []
    for k, v in COMMON_NEED[lang].items():
        if re.search(rf"\n      {k}:", body):
            continue
        esc = v.replace("\\", "\\\\").replace('"', '\\"')
        adds.append(f'      {k}: "{esc}"')
    if adds:
        body = body.rstrip()
        if body and not body.endswith(","):
            body += ","
        # also ensure ledgerName line has comma
        body = body + "\n" + ",\n".join(adds) + "\n"
        text = text[:body_start] + body + pre[inner_end:] + text[bank:]
        print(f"{lang}: added common keys { [a.split(':')[0].strip() for a in adds] }")
    else:
        print(f"{lang}: common keys already ok")

    # trailing comma cleanup
    text = text.replace(",,", ",")
    path.write_text(text, encoding="utf-8")


def main():
    for lang in ("en", "hi", "bn", "or"):
        fix_lang(lang)


if __name__ == "__main__":
    main()
