# -*- coding: utf-8 -*-
"""Add borrowings report keys."""
from pathlib import Path
import json
import re

LOC = Path(__file__).resolve().parents[1] / "i18n" / "locales"

BOR_EXTRA = {
    "en": {
        "borrowingsReport": "Borrowings Report",
        "slNo": "Sl No.",
        "openingDate": "Opening Date",
        "prnRefund": "Prn. Refund",
        "inttRefund": "Intt. Refund",
        "outsBal": "Outs. Bal",
        "provisionIntt": "Provision Intt.",
        "detailedListFrom": "Borrowings Detailed List From",
        "to": "To",
        "subTotal": "Sub Total",
        "grandTotal": "Grand Total",
        "generatedBy": "Generated By :",
        "generatedOn": "Generated On :",
        "reportGeneratedByPrioSuite": "This report is generated by PrioSuite.",
        "print": {
            "slNo": "SL. NO.",
            "openingDate": "OPENING DATE",
            "productName": "PRODUCT NAME",
            "bankName": "BANK NAME",
            "accountNo": "ACCOUNT NO.",
            "disburse": "DISBURSE",
            "prnRefund": "PRN. REFUND",
            "inttRefund": "INTT. REFUND",
            "outsBal": "OUTS. BAL.",
            "provIntt": "PROV. INTT.",
            "dueDate": "DUE DATE",
        },
    },
    "hi": {
        "borrowingsReport": "उधार रिपोर्ट",
        "slNo": "क्रमांक",
        "openingDate": "प्रारंभिक तारीख",
        "prnRefund": "मूलधन वापसी",
        "inttRefund": "ब्याज वापसी",
        "outsBal": "बकाया शेष",
        "provisionIntt": "प्रावधान ब्याज",
        "detailedListFrom": "उधार विस्तृत सूची से",
        "to": "तक",
        "subTotal": "उप योग",
        "grandTotal": "कुल योग",
        "generatedBy": "द्वारा जनरेट :",
        "generatedOn": "जनरेट किया गया :",
        "reportGeneratedByPrioSuite": "यह रिपोर्ट PrioSuite द्वारा जनरेट की गई है।",
        "print": {
            "slNo": "क्रमांक",
            "openingDate": "प्रारंभिक तारीख",
            "productName": "उत्पाद का नाम",
            "bankName": "बैंक का नाम",
            "accountNo": "खाता संख्या",
            "disburse": "वितरण",
            "prnRefund": "मूलधन वापसी",
            "inttRefund": "ब्याज वापसी",
            "outsBal": "बकाया शेष",
            "provIntt": "प्रावधान ब्याज",
            "dueDate": "नियत तारीख",
        },
    },
    "bn": {
        "borrowingsReport": "ঋণ রিপোর্ট",
        "slNo": "ক্রমিক নং",
        "openingDate": "প্রারম্ভিক তারিখ",
        "prnRefund": "মূলধন ফেরত",
        "inttRefund": "সুদ ফেরত",
        "outsBal": "বকেয়া ব্যালেন্স",
        "provisionIntt": "প্রভিশন সুদ",
        "detailedListFrom": "ঋণ বিস্তারিত তালিকা থেকে",
        "to": "পর্যন্ত",
        "subTotal": "উপমোট",
        "grandTotal": "সর্বমোট",
        "generatedBy": "জেনারেট করেছেন :",
        "generatedOn": "জেনারেট হয়েছে :",
        "reportGeneratedByPrioSuite": "এই রিপোর্ট PrioSuite দ্বারা তৈরি।",
        "print": {
            "slNo": "ক্রমিক",
            "openingDate": "প্রারম্ভিক তারিখ",
            "productName": "পণ্যের নাম",
            "bankName": "ব্যাংকের নাম",
            "accountNo": "অ্যাকাউন্ট নম্বর",
            "disburse": "বিতরণ",
            "prnRefund": "মূলধন ফেরত",
            "inttRefund": "সুদ ফেরত",
            "outsBal": "বকেয়া ব্যালেন্স",
            "provIntt": "প্রভিশন সুদ",
            "dueDate": "নির্ধারিত তারিখ",
        },
    },
    "or": {
        "borrowingsReport": "ଋଣ ରିପୋର୍ଟ",
        "slNo": "କ୍ରମିକ ନମ୍ବର",
        "openingDate": "ଆରମ୍ଭିକ ତାରିଖ",
        "prnRefund": "ମୂଳଧନ ଫେରସ୍ତ",
        "inttRefund": "ସୁଧ ଫେରସ୍ତ",
        "outsBal": "ବକେୟା ବାଲାନ୍ସ",
        "provisionIntt": "ପ୍ରୋଭିଜନ ସୁଧ",
        "detailedListFrom": "ଋଣ ବିସ୍ତୃତ ତାଲିକା ରୁ",
        "to": "ପର୍ଯ୍ୟନ୍ତ",
        "subTotal": "ଉପ ମୋଟ",
        "grandTotal": "ସର୍ବମୋଟ",
        "generatedBy": "ଜେନେରେଟ କରିଛନ୍ତି :",
        "generatedOn": "ଜେନେରେଟ ହୋଇଛି :",
        "reportGeneratedByPrioSuite": "ଏହି ରିପୋର୍ଟ PrioSuite ଦ୍ୱାରା ତିଆରି।",
        "print": {
            "slNo": "କ୍ରମିକ",
            "openingDate": "ଆରମ୍ଭିକ ତାରିଖ",
            "productName": "ଉତ୍ପାଦ ନାମ",
            "bankName": "ବ୍ୟାଙ୍କ ନାମ",
            "accountNo": "ଆକାଉଣ୍ଟ ନମ୍ବର",
            "disburse": "ବଣ୍ଟନ",
            "prnRefund": "ମୂଳଧନ ଫେରସ୍ତ",
            "inttRefund": "ସୁଧ ଫେରସ୍ତ",
            "outsBal": "ବକେୟା ବାଲାନ୍ସ",
            "provIntt": "ପ୍ରୋଭିଜନ ସୁଧ",
            "dueDate": "ନିର୍ଦ୍ଧାରିତ ତାରିଖ",
        },
    },
}


def dump_value(v, indent):
    if isinstance(v, dict):
        lines = ["{"]
        items = list(v.items())
        for i, (k, val) in enumerate(items):
            comma = "," if i < len(items) - 1 else ""
            lines.append(
                " " * (indent + 2)
                + f"{k}: {json.dumps(val, ensure_ascii=False)}{comma}"
            )
        lines.append(" " * indent + "}")
        return "\n".join(lines)
    return json.dumps(v, ensure_ascii=False)


for name in ["en", "hi", "bn", "or"]:
    p = LOC / f"{name}.js"
    t = p.read_text(encoding="utf-8")
    m = re.search(r"\n    borrowings: \{", t)
    if not m:
        raise SystemExit(f"{name}: borrowings missing")
    idx = m.start() + 1
    brace = 0
    i = t.find("{", idx)
    for j in range(i, len(t)):
        if t[j] == "{":
            brace += 1
        elif t[j] == "}":
            brace -= 1
            if brace == 0:
                end_brace = j
                break
    end = end_brace + 1
    had_comma = end < len(t) and t[end] == ","
    if had_comma:
        end += 1
    section = t[idx:end]
    body_start = section.find("{") + 1
    brace = 0
    for j, ch in enumerate(section):
        if ch == "{":
            brace += 1
        elif ch == "}":
            brace -= 1
            if brace == 0:
                body = section[body_start:j]
                break
    body = body.rstrip()
    if body.endswith("}"):
        body += ","
    elif not body.endswith(",") and not body.endswith("{"):
        lines = body.split("\n")
        if lines[-1].strip() and not lines[-1].rstrip().endswith(","):
            lines[-1] = lines[-1] + ","
        body = "\n".join(lines)
    body += "\n"
    added = []
    for k, v in BOR_EXTRA[name].items():
        if k == "print":
            if re.search(r"^\s{6}print:\s*\{", body, re.M):
                continue
            body += f"      print: {dump_value(v, 6)},\n"
            added.append("print")
            continue
        if re.search(rf"^\s{{6}}{k}:", body, re.M):
            continue
        body += f"      {k}: {json.dumps(v, ensure_ascii=False)},\n"
        added.append(k)
    new_section = (
        "    borrowings: {\n"
        + body.rstrip().rstrip(",")
        + "\n    }"
        + ("," if had_comma else "")
    )
    t = t[:idx] + new_section + t[end:]
    while ",," in t:
        t = t.replace(",,", ",")
    p.write_text(t, encoding="utf-8")
    print(name, "borrowings+", added)
