# -*- coding: utf-8 -*-
"""Insert top-level report.daybook keys into en/hi/bn/or locales."""
from pathlib import Path
import re

LOC = Path(__file__).resolve().parents[1] / "i18n" / "locales"


def js_obj(d, indent=6):
    pad = " " * indent
    lines = []
    items = list(d.items())
    for i, (k, v) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        if isinstance(v, dict):
            lines.append(f"{pad}{k}: {{")
            lines.append(js_obj(v, indent + 2))
            lines.append(f"{pad}}}{comma}")
        else:
            esc = str(v).replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{pad}{k}: "{esc}"{comma}')
    return "\n".join(lines)


DAYBOOK = {
    "en": {
        "daybookReport": "Daybook Report",
        "nothingToDownload": "Nothing to download. Please generate the report first.",
        "noDaybookData": "No daybook data to download.",
        "failedToCapturePdf": "Failed to capture report for PDF.",
        "pdfDownloaded": "PDF downloaded",
        "failedToDownloadPdf": "Failed to download PDF",
        "vNo": "V. NO.",
        "particulars": "PARTICULARS",
        "receipts": "RECEIPTS",
        "payments": "PAYMENTS",
        "cash": "CASH",
        "transfer": "TRANSFER",
        "totalUpper": "TOTAL",
        "total": "Total",
        "openingBalance": "Opening Balance",
        "closingBalance": "Closing Balance",
        "grandTotal": "Grand Total",
        "closingCashBalanceInWord": "Closing Cash Balance in Word :",
        "physicalDenomination": "Physical Denomination",
        "listOfVouchersForTheDayOn": "List Of Vouchers For The Day On",
        "sl": "Sl.",
        "voucherNo": "Voucher No.",
        "transactionType": "Transanction Type",
        "receiptsLabel": "Receipts",
        "narration": "Narration",
        "previous": "Previous",
        "next": "Next",
        "printBtn": "Print",
        "voucherType": "Voucher Type",
        "refVcNo": "Ref. Vc. No",
        "voucherDate": "Voucher Date",
        "headOfAccount": "Head Of Account",
        "drAmount": "Dr. Amount",
        "crAmount": "Cr. Amount",
        "daybookAsOn": "Daybook As On",
        "closingBalanceInWords": "Closing Balance In Words:",
        "zero": "Zero",
        "generatedBy": "Generated By :",
        "generatedOn": "Generated On :",
        "reportGeneratedByPrioSuite": "This report is generated by PrioSuite.",
        "generatedByPrioSuite": "This is generated by PrioSuite.",
        "slNo": "Sl. NO.",
        "denomination": "Denomination",
        "quantity": "Quantity",
        "value": "Value",
        "print": {
            "sl": "SL.",
            "headOfAccount": "HEAD OF ACCOUNT",
            "drAmount": "DR. AMOUNT",
            "crAmount": "CR. AMOUNT",
            "vNo": "V. NO.",
            "particulars": "PARTICULARS",
            "receipts": "RECEIPTS",
            "payments": "PAYMENTS",
            "cash": "CASH",
            "transfer": "TRANSFER",
            "total": "TOTAL",
            "slNo": "Sl. NO.",
            "denomination": "Denomination",
            "quantity": "Quantity",
            "value": "Value",
        },
    },
    "hi": {
        "daybookReport": "डेबुक रिपोर्ट",
        "nothingToDownload": "डाउनलोड करने के लिए कुछ नहीं है। कृपया पहले रिपोर्ट बनाएँ।",
        "noDaybookData": "डाउनलोड करने के लिए कोई डेबुक डेटा नहीं है।",
        "failedToCapturePdf": "PDF के लिए रिपोर्ट कैप्चर करने में विफल।",
        "pdfDownloaded": "PDF डाउनलोड हो गया",
        "failedToDownloadPdf": "PDF डाउनलोड करने में विफल",
        "vNo": "वा. सं.",
        "particulars": "विवरण",
        "receipts": "प्राप्तियाँ",
        "payments": "भुगतान",
        "cash": "नकद",
        "transfer": "ट्रांसफर",
        "totalUpper": "कुल",
        "total": "कुल",
        "openingBalance": "प्रारंभिक शेष",
        "closingBalance": "अंतिम शेष",
        "grandTotal": "कुल योग",
        "closingCashBalanceInWord": "अंतिम नकद शेष शब्दों में :",
        "physicalDenomination": "भौतिक मूल्यवर्ग",
        "listOfVouchersForTheDayOn": "दिन के वाउचर की सूची",
        "sl": "क्र.",
        "voucherNo": "वाउचर संख्या",
        "transactionType": "लेनदेन प्रकार",
        "receiptsLabel": "प्राप्तियाँ",
        "narration": "विवरण",
        "previous": "पिछला",
        "next": "अगला",
        "printBtn": "प्रिंट",
        "voucherType": "वाउचर प्रकार",
        "refVcNo": "संदर्भ वाउचर संख्या",
        "voucherDate": "वाउचर दिनांक",
        "headOfAccount": "खाते का शीर्ष",
        "drAmount": "डेबिट राशि",
        "crAmount": "क्रेडिट राशि",
        "daybookAsOn": "डेबुक दिनांक",
        "closingBalanceInWords": "अंतिम शेष शब्दों में:",
        "zero": "शून्य",
        "generatedBy": "द्वारा निर्मित :",
        "generatedOn": "निर्मित दिनांक :",
        "reportGeneratedByPrioSuite": "यह रिपोर्ट PrioSuite द्वारा तैयार की गई है।",
        "generatedByPrioSuite": "यह रिपोर्ट PrioSuite द्वारा तैयार की गई है।",
        "slNo": "क्रमांक",
        "denomination": "मूल्यवर्ग",
        "quantity": "मात्रा",
        "value": "मूल्य",
        "print": {
            "sl": "क्रमांक",
            "headOfAccount": "खाते का शीर्ष",
            "drAmount": "डेबिट राशि",
            "crAmount": "क्रेडिट राशि",
            "vNo": "वा. सं.",
            "particulars": "विवरण",
            "receipts": "प्राप्तियाँ",
            "payments": "भुगतान",
            "cash": "नकद",
            "transfer": "ट्रांसफर",
            "total": "कुल",
            "slNo": "क्रमांक",
            "denomination": "मूल्यवर्ग",
            "quantity": "मात्रा",
            "value": "मूल्य",
        },
    },
    "bn": {
        "daybookReport": "ডেবুক রিপোর্ট",
        "nothingToDownload": "ডাউনলোড করার কিছু নেই। অনুগ্রহ করে আগে রিপোর্ট তৈরি করুন।",
        "noDaybookData": "ডাউনলোডের জন্য কোনো ডেবুক ডেটা নেই।",
        "failedToCapturePdf": "PDF-এর জন্য রিপোর্ট ক্যাপচার করতে ব্যর্থ।",
        "pdfDownloaded": "PDF ডাউনলোড হয়েছে",
        "failedToDownloadPdf": "PDF ডাউনলোড করতে ব্যর্থ",
        "vNo": "ভা. নং",
        "particulars": "বিবরণ",
        "receipts": "প্রাপ্তি",
        "payments": "পরিশোধ",
        "cash": "নগদ",
        "transfer": "ট্রান্সফার",
        "totalUpper": "মোট",
        "total": "মোট",
        "openingBalance": "প্রারম্ভিক ব্যালেন্স",
        "closingBalance": "সমাপনী ব্যালেন্স",
        "grandTotal": "সর্বমোট",
        "closingCashBalanceInWord": "সমাপনী নগদ ব্যালেন্স কথায় :",
        "physicalDenomination": "ভৌত ডিনোমিনেশন",
        "listOfVouchersForTheDayOn": "দিনের ভাউচার তালিকা",
        "sl": "ক্র.",
        "voucherNo": "ভাউচার নম্বর",
        "transactionType": "লেনদেনের ধরন",
        "receiptsLabel": "প্রাপ্তি",
        "narration": "বিবরণ",
        "previous": "পূর্ববর্তী",
        "next": "পরবর্তী",
        "printBtn": "প্রিন্ট",
        "voucherType": "ভাউচারের ধরন",
        "refVcNo": "রেফ. ভাউচার নম্বর",
        "voucherDate": "ভাউচারের তারিখ",
        "headOfAccount": "অ্যাকাউন্টের শিরোনাম",
        "drAmount": "ডেবিট পরিমাণ",
        "crAmount": "ক্রেডিট পরিমাণ",
        "daybookAsOn": "ডেবুক তারিখ",
        "closingBalanceInWords": "সমাপনী ব্যালেন্স কথায়:",
        "zero": "শূন্য",
        "generatedBy": "প্রস্তুত করেছেন :",
        "generatedOn": "তৈরির তারিখ :",
        "reportGeneratedByPrioSuite": "এই রিপোর্টটি PrioSuite দ্বারা তৈরি করা হয়েছে।",
        "generatedByPrioSuite": "এই রিপোর্টটি PrioSuite দ্বারা তৈরি করা হয়েছে।",
        "slNo": "ক্রমিক নং",
        "denomination": "ডিনোমিনেশন",
        "quantity": "পরিমাণ",
        "value": "মূল্য",
        "print": {
            "sl": "ক্রমিক",
            "headOfAccount": "অ্যাকাউন্টের শিরোনাম",
            "drAmount": "ডেবিট পরিমাণ",
            "crAmount": "ক্রেডিট পরিমাণ",
            "vNo": "ভা. নং",
            "particulars": "বিবরণ",
            "receipts": "প্রাপ্তি",
            "payments": "পরিশোধ",
            "cash": "নগদ",
            "transfer": "ট্রান্সফার",
            "total": "মোট",
            "slNo": "ক্রমিক নং",
            "denomination": "ডিনোমিনেশন",
            "quantity": "পরিমাণ",
            "value": "মূল্য",
        },
    },
    "or": {
        "daybookReport": "ଡେବୁକ୍ ରିପୋର୍ଟ",
        "nothingToDownload": "ଡାଉନଲୋଡ୍ କରିବାକୁ କିଛି ନାହିଁ। ଦୟାକରି ପ୍ରଥମେ ରିପୋର୍ଟ ତିଆରି କରନ୍ତୁ।",
        "noDaybookData": "ଡାଉନଲୋଡ୍ ପାଇଁ କୌଣସି ଡେବୁକ୍ ତଥ୍ୟ ନାହିଁ।",
        "failedToCapturePdf": "PDF ପାଇଁ ରିପୋର୍ଟ କ୍ୟାପଚର୍ କରିବାରେ ବିଫଳ।",
        "pdfDownloaded": "PDF ଡାଉନଲୋଡ୍ ହୋଇଛି",
        "failedToDownloadPdf": "PDF ଡାଉନଲୋଡ୍ କରିବାରେ ବିଫଳ",
        "vNo": "ଭା. ନଂ",
        "particulars": "ବିବରଣୀ",
        "receipts": "ପ୍ରାପ୍ତି",
        "payments": "ପ୍ରଦାନ",
        "cash": "ନଗଦ",
        "transfer": "ଟ୍ରାନ୍ସଫର୍",
        "totalUpper": "ମୋଟ",
        "total": "ମୋଟ",
        "openingBalance": "ପ୍ରାରମ୍ଭିକ ବାଲାନ୍ସ",
        "closingBalance": "ସମାପନୀ ବାଲାନ୍ସ",
        "grandTotal": "ସର୍ବମୋଟ",
        "closingCashBalanceInWord": "ସମାପନୀ ନଗଦ ବାଲାନ୍ସ ଶବ୍ଦରେ :",
        "physicalDenomination": "ଭୌତିକ ଡିନୋମିନେସନ୍",
        "listOfVouchersForTheDayOn": "ଦିନର ଭାଉଚର୍ ତାଲିକା",
        "sl": "କ୍ର.",
        "voucherNo": "ଭାଉଚର୍ ନମ୍ବର",
        "transactionType": "କାରବାର ପ୍ରକାର",
        "receiptsLabel": "ପ୍ରାପ୍ତି",
        "narration": "ବିବରଣୀ",
        "previous": "ପୂର୍ବ",
        "next": "ପର",
        "printBtn": "ପ୍ରିଣ୍ଟ",
        "voucherType": "ଭାଉଚର୍ ପ୍ରକାର",
        "refVcNo": "ରେଫ୍. ଭାଉଚର୍ ନମ୍ବର",
        "voucherDate": "ଭାଉଚର୍ ତାରିଖ",
        "headOfAccount": "ଆକାଉଣ୍ଟ ଶୀର୍ଷ",
        "drAmount": "ଡେବିଟ୍ ରାଶି",
        "crAmount": "କ୍ରେଡିଟ୍ ରାଶି",
        "daybookAsOn": "ଡେବୁକ୍ ତାରିଖ",
        "closingBalanceInWords": "ସମାପନୀ ବାଲାନ୍ସ ଶବ୍ଦରେ:",
        "zero": "ଶୂନ୍ୟ",
        "generatedBy": "ପ୍ରସ୍ତୁତକର୍ତ୍ତା :",
        "generatedOn": "ପ୍ରସ୍ତୁତ ତାରିଖ :",
        "reportGeneratedByPrioSuite": "ଏହି ରିପୋର୍ଟ PrioSuite ଦ୍ୱାରା ପ୍ରସ୍ତୁତ କରାଯାଇଛି।",
        "generatedByPrioSuite": "ଏହି ରିପୋର୍ଟ PrioSuite ଦ୍ୱାରା ପ୍ରସ୍ତୁତ କରାଯାଇଛି।",
        "slNo": "କ୍ରମିକ ନଂ",
        "denomination": "ଡିନୋମିନେସନ୍",
        "quantity": "ପରିମାଣ",
        "value": "ମୂଲ୍ୟ",
        "print": {
            "sl": "କ୍ରମିକ",
            "headOfAccount": "ଆକାଉଣ୍ଟ ଶୀର୍ଷ",
            "drAmount": "ଡେବିଟ୍ ରାଶି",
            "crAmount": "କ୍ରେଡିଟ୍ ରାଶି",
            "vNo": "ଭା. ନଂ",
            "particulars": "ବିବରଣୀ",
            "receipts": "ପ୍ରାପ୍ତି",
            "payments": "ପ୍ରଦାନ",
            "cash": "ନଗଦ",
            "transfer": "ଟ୍ରାନ୍ସଫର୍",
            "total": "ମୋଟ",
            "slNo": "କ୍ରମିକ ନଂ",
            "denomination": "ଡିନୋମିନେସନ୍",
            "quantity": "ପରିମାଣ",
            "value": "ମୂଲ୍ୟ",
        },
    },
}


def insert_report(lang: str) -> None:
    path = LOC / f"{lang}.js"
    text = path.read_text(encoding="utf-8")
    # Top-level report only (4-space indent under translation)
    if re.search(r"\n    report:\s*\{", text):
        print(f"{lang}: top-level report already present, skip")
        return

    block = (
        "    report: {\n"
        "      daybook: {\n"
        + js_obj(DAYBOOK[lang], indent=8)
        + "\n      }\n"
        "    },\n"
    )

    # Insert before final closing of translation object after borrowings
    m = re.search(r"(    borrowings:\s*\{[\s\S]*?\n    \},\n)(  \},\n\};)", text)
    if not m:
        raise SystemExit(f"{lang}: could not find borrowings end anchor")

    text = text[: m.start(2)] + block + text[m.start(2) :]
    path.write_text(text, encoding="utf-8")
    print(f"{lang}: inserted report.daybook")


def main():
    for lang in ("en", "hi", "bn", "or"):
        insert_report(lang)


if __name__ == "__main__":
    main()
