# -*- coding: utf-8 -*-
"""Add investment report + missing common keys."""
from pathlib import Path
import json
import re

LOC = Path(__file__).resolve().parents[1] / "i18n" / "locales"

INV_EXTRA = {
    "en": {
        "investmentReport": "Investment Report",
        "slNo": "Sl No.",
        "invest": "Invest",
        "roi": "ROI",
        "provIntt": "Prov. Intt.",
        "detailedListFrom": "Investment Detailed List From",
        "to": "To",
        "subTotal": "Sub Total",
        "grandTotal": "Grand Total",
        "generatedBy": "Generated By :",
        "generatedOn": "Generated On :",
        "reportGeneratedByPrioSuite": "This report is generated by PrioSuite.",
        "print": {
            "slNo": "SL. NO.",
            "openingDate": "OPENING DATE",
            "bankName": "BANK NAME",
            "accountNo": "ACCOUNT NO.",
            "accountType": "ACCOUNT TYPE",
            "invest": "INVEST",
            "roi": "ROI",
            "matureDate": "MATURE DATE",
            "provIntt": "PROV. INTT.",
        },
    },
    "hi": {
        "investmentReport": "निवेश रिपोर्ट",
        "slNo": "क्रमांक",
        "invest": "निवेश",
        "roi": "ब्याज दर",
        "provIntt": "प्रावधान ब्याज",
        "detailedListFrom": "निवेश विस्तृत सूची से",
        "to": "तक",
        "subTotal": "उप योग",
        "grandTotal": "कुल योग",
        "generatedBy": "द्वारा जनरेट :",
        "generatedOn": "जनरेट किया गया :",
        "reportGeneratedByPrioSuite": "यह रिपोर्ट PrioSuite द्वारा जनरेट की गई है।",
        "print": {
            "slNo": "क्रमांक",
            "openingDate": "प्रारंभिक तिथि",
            "bankName": "बैंक का नाम",
            "accountNo": "खाता संख्या",
            "accountType": "खाते का प्रकार",
            "invest": "निवेश",
            "roi": "ब्याज दर",
            "matureDate": "परिपक्वता तिथि",
            "provIntt": "प्रावधान ब्याज",
        },
    },
    "bn": {
        "investmentReport": "বিনিয়োগ রিপোর্ট",
        "slNo": "ক্রমিক",
        "invest": "বিনিয়োগ",
        "roi": "সুদের হার",
        "provIntt": "প্রভিশন সুদ",
        "detailedListFrom": "বিনিয়োগ বিস্তারিত তালিকা থেকে",
        "to": "পর্যন্ত",
        "subTotal": "উপমোট",
        "grandTotal": "সর্বমোট",
        "generatedBy": "জেনারেট করেছেন :",
        "generatedOn": "জেনারেট হয়েছে :",
        "reportGeneratedByPrioSuite": "এই রিপোর্ট PrioSuite দ্বারা তৈরি।",
        "print": {
            "slNo": "ক্রমিক",
            "openingDate": "খোলার তারিখ",
            "bankName": "ব্যাংকের নাম",
            "accountNo": "অ্যাকাউন্ট নম্বর",
            "accountType": "অ্যাকাউন্টের ধরন",
            "invest": "বিনিয়োগ",
            "roi": "সুদের হার",
            "matureDate": "মেয়াদপূর্তির তারিখ",
            "provIntt": "প্রভিশন সুদ",
        },
    },
    "or": {
        "investmentReport": "ନିବେଶ ରିପୋର୍ଟ",
        "slNo": "କ୍ରମିକ",
        "invest": "ନିବେଶ",
        "roi": "ସୁଧ ହାର",
        "provIntt": "ପ୍ରୋଭିଜନ ସୁଧ",
        "detailedListFrom": "ନିବେଶ ବିସ୍ତୃତ ତାଲିକା ରୁ",
        "to": "ପର୍ଯ୍ୟନ୍ତ",
        "subTotal": "ଉପ ମୋଟ",
        "grandTotal": "ସର୍ବମୋଟ",
        "generatedBy": "ଜେନେରେଟ କରିଛନ୍ତି :",
        "generatedOn": "ଜେନେରେଟ ହୋଇଛି :",
        "reportGeneratedByPrioSuite": "ଏହି ରିପୋର୍ଟ PrioSuite ଦ୍ୱାରା ତିଆରି।",
        "print": {
            "slNo": "କ୍ରମିକ",
            "openingDate": "ଆରମ୍ଭିକ ତାରିଖ",
            "bankName": "ବ୍ୟାଙ୍କ ନାମ",
            "accountNo": "ଆକାଉଣ୍ଟ ନମ୍ବର",
            "accountType": "ଆକାଉଣ୍ଟ ପ୍ରକାର",
            "invest": "ନିବେଶ",
            "roi": "ସୁଧ ହାର",
            "matureDate": "ପରିପକ୍ୱତା ତାରିଖ",
            "provIntt": "ପ୍ରୋଭିଜନ ସୁଧ",
        },
    },
}

COMMON_EXTRA = {
    "en": {
        "fromDate": "From Date",
        "toDate": "To Date",
        "reportType": "Report Type",
        "selectReportType": "Select report type",
        "searchReportType": "Search report type...",
        "selectBranch": "Select branch",
        "searchBranch": "Search branch...",
        "subtotal": "Subtotal",
        "grandTotal": "Grand Total",
        "accountType": "Account Type",
    },
    "hi": {
        "fromDate": "तिथि से",
        "toDate": "तिथि तक",
        "reportType": "रिपोर्ट प्रकार",
        "selectReportType": "रिपोर्ट प्रकार चुनें",
        "searchReportType": "रिपोर्ट प्रकार खोजें...",
        "selectBranch": "शाखा चुनें",
        "searchBranch": "शाखा खोजें...",
        "subtotal": "उप योग",
        "grandTotal": "कुल योग",
        "accountType": "खाते का प्रकार",
    },
    "bn": {
        "fromDate": "তারিখ থেকে",
        "toDate": "তারিখ পর্যন্ত",
        "reportType": "রিপোর্টের ধরন",
        "selectReportType": "রিপোর্টের ধরন নির্বাচন করুন",
        "searchReportType": "রিপোর্টের ধরন অনুসন্ধান করুন...",
        "selectBranch": "শাখা নির্বাচন করুন",
        "searchBranch": "শাখা অনুসন্ধান করুন...",
        "subtotal": "উপমোট",
        "grandTotal": "সর্বমোট",
        "accountType": "অ্যাকাউন্টের ধরন",
    },
    "or": {
        "fromDate": "ତାରିଖରୁ",
        "toDate": "ତାରିଖ ପର୍ଯ୍ୟନ୍ତ",
        "reportType": "ରିପୋର୍ଟ ପ୍ରକାର",
        "selectReportType": "ରିପୋର୍ଟ ପ୍ରକାର ଚୟନ କରନ୍ତୁ",
        "searchReportType": "ରିପୋର୍ଟ ପ୍ରକାର ଖୋଜନ୍ତୁ...",
        "selectBranch": "ଶାଖା ଚୟନ କରନ୍ତୁ",
        "searchBranch": "ଶାଖା ଖୋଜନ୍ତୁ...",
        "subtotal": "ଉପ ମୋଟ",
        "grandTotal": "ସର୍ବମୋଟ",
        "accountType": "ଆକାଉଣ୍ଟ ପ୍ରକାର",
    },
}


def dump_value(v, indent):
    if isinstance(v, dict):
        lines = ["{"]
        items = list(v.items())
        for i, (k, val) in enumerate(items):
            comma = "," if i < len(items) - 1 else ""
            lines.append(
                " " * (indent + 2)
                + f"{k}: {json.dumps(val, ensure_ascii=False)}{comma}"
            )
        lines.append(" " * indent + "}")
        return "\n".join(lines)
    return json.dumps(v, ensure_ascii=False)


for name in ["en", "hi", "bn", "or"]:
    p = LOC / f"{name}.js"
    t = p.read_text(encoding="utf-8")

    # common inside before bank
    idx = t.rfind("    common: {")
    end = t.find("\n    bank:", idx)
    section = t[idx:end]
    close = section.rfind("\n    },")
    before = section[:close].rstrip()
    if not before.endswith(","):
        lines = before.split("\n")
        if lines[-1].strip() and not lines[-1].rstrip().endswith(","):
            lines[-1] = lines[-1] + ","
        before = "\n".join(lines)
    before += "\n"
    added_c = []
    for k, v in COMMON_EXTRA[name].items():
        if re.search(rf"^\s{{6}}{k}:", before, re.M):
            continue
        before += f"      {k}: {json.dumps(v, ensure_ascii=False)},\n"
        added_c.append(k)
    t = t[:idx] + before + "    }," + t[end:]
    print(name, "common+", added_c)

    # investment
    m = re.search(r"\n    investment: \{", t)
    idx = m.start() + 1
    brace = 0
    i = t.find("{", idx)
    for j in range(i, len(t)):
        if t[j] == "{":
            brace += 1
        elif t[j] == "}":
            brace -= 1
            if brace == 0:
                end_brace = j
                break
    end = end_brace + 1
    had_comma = end < len(t) and t[end] == ","
    if had_comma:
        end += 1
    section = t[idx:end]
    close = section.rfind("}")
    # if print already nested near end, still insert flat keys before final }
    # Find outermost closing - section ends with print? or plain }
    before = section[:close].rstrip()
    # If last part is nested print closing, the rfind } finds innermost of print
    # Better: strip trailing `}` and optional comma from section end properly via brace from start
    # Rebuild: take content between first { and matching }
    body_start = section.find("{") + 1
    # Find matching end for investment object from body_start-1
    brace = 0
    for j, ch in enumerate(section):
        if ch == "{":
            brace += 1
        elif ch == "}":
            brace -= 1
            if brace == 0:
                body = section[body_start:j]
                break
    body = body.rstrip()
    if not body.endswith(",") and not body.endswith("{"):
        # ensure comma after last prop
        # if ends with } (nested print), add comma after that }
        if body.endswith("}"):
            body = body + ","
        else:
            lines = body.split("\n")
            if lines[-1].strip() and not lines[-1].rstrip().endswith(","):
                lines[-1] = lines[-1] + ","
            body = "\n".join(lines)
    body += "\n"
    added_i = []
    for k, v in INV_EXTRA[name].items():
        if k == "print":
            if re.search(r"^\s{6}print:\s*\{", body, re.M):
                continue
            body += f"      print: {dump_value(v, 6)},\n"
            added_i.append("print")
            continue
        if re.search(rf"^\s{{6}}{k}:", body, re.M):
            continue
        body += f"      {k}: {json.dumps(v, ensure_ascii=False)},\n"
        added_i.append(k)
    new_section = "    investment: {\n" + body.rstrip().rstrip(",") + "\n    }" + ("," if had_comma else "")
    t = t[:idx] + new_section + t[end:]
    while ",," in t:
        t = t.replace(",,", ",")
    p.write_text(t, encoding="utf-8")
    print(name, "investment+", added_i)
