# -*- coding: utf-8 -*-
"""Loan flat-namespace locale data (en/hi/bn/or)."""
from __future__ import annotations

import re
import json
from pathlib import Path

# Exact English UI string -> key (flat under loan.*) or ("print", key) for ALL-CAPS
STRING_TO_KEY: dict[str, str | tuple[str, str]] = {}

# Manual overrides (preferred names from task + collisions)
OVERRIDES: dict[str, str | tuple[str, str]] = {
    "Loan Report": "loanReport",
    "From Date": "fromDate",
    "To Date": "toDate",
    "Loan Product": "loanProduct",
    "Select loan product": "selectLoanProduct",
    "Search loan product...": "searchLoanProduct",
    "Report Type": "reportType",
    "Select report type": "selectReportType",
    "Search report type...": "searchReportType",
    "Branch": "branch",
    "Select branch": "selectBranch",
    "Search branch...": "searchBranch",
    "Customer Name": "customerName",
    "Guardian Name": "guardianName",
    "Gurdian Name": "gurdianName",
    "Account No.": "accountNo",
    "Account No": "accountNoShort",
    "Ref. Ac. No.": "refAcNo",
    "Date": "date",
    "Sl No.": "slNo",
    "Sl. No.": "slNoDot",
    "Sl": "sl",
    "SL": "slUpper",
    "Disburse": "disburse",
    "Share": "share",
    "Ins. Amt.": "insAmt",
    "Mis. Amt.": "misAmt",
    "Net Disburse": "netDisburse",
    "Trans. Mode": "transMode",
    "Principal": "principal",
    "Interest": "interest",
    "Amount": "amount",
    "Action": "action",
    "Repayment": "repayment",
    "Outstanding": "outstanding",
    "Outs. Interest": "outsInterest",
    "Current": "current",
    "Overdue": "overdue",
    "Opening": "opening",
    "Loan Date": "loanDate",
    "Subtotal": "subtotal",
    "Sub Total": "subTotal",
    "Total": "total",
    "Grand Total": "grandTotal",
    "Generated By": "generatedBy",
    "Generated By:": "generatedByColon",
    "Generated On": "generatedOn",
    "Generated On:": "generatedOnColon",
    "This report is generated by PrioSuite.": "reportGeneratedByPrioSuite",
    "Loan Disburse Register From": "loanDisburseRegisterFrom",
    "Loan Repayment Register From": "loanRepaymentRegisterFrom",
    "Loan Detailed List From": "loanDetailedListFrom",
    "Nothing to download. Please generate the report first.": "nothingToDownload",
    "No loan report data to download.": "noLoanReportData",
    "Failed to capture report for PDF.": "failedToCaptureReport",
    "PDF downloaded": "pdfDownloaded",
    "Failed to download PDF": "failedToDownloadPdf",
    # print headers
    "SL. NO.": ("print", "slNo"),
    "DATE": ("print", "date"),
    "CUSTOMER NAME": ("print", "customerName"),
    "GUARDIAN NAME": ("print", "guardianName"),
    "ACCOUNT NO.": ("print", "accountNo"),
    "REF. AC. NO.": ("print", "refAcNo"),
    "DISBURSE": ("print", "disburse"),
    "SHARE": ("print", "share"),
    "INS. AMT.": ("print", "insAmt"),
    "MIS. AMT.": ("print", "misAmt"),
    "NET DISBURSE": ("print", "netDisburse"),
    "TRANS. MODE": ("print", "transMode"),
    "PRINCIPAL": ("print", "principal"),
    "INTEREST": ("print", "interest"),
    "AMOUNT": ("print", "amount"),
    "NAME": ("print", "name"),
    "MEMBER NO.": ("print", "memberNo"),
    "ISSUE DATE": ("print", "issueDate"),
    "ISSUE AMOUNT": ("print", "issueAmount"),
    "SCHEME": ("print", "scheme"),
    "SCHEME NAME": ("print", "schemeName"),
    "OUTSTANDING BALANCE": ("print", "outstandingBalance"),
    "OUTS. BAL.": ("print", "outsBal"),
    "CP BAL": ("print", "cpBal"),
    "CI BAL": ("print", "ciBal"),
    "OP BAL": ("print", "opBal"),
    "OI BAL": ("print", "oiBal"),
    "CP BAL.": ("print", "cpBalDot"),
    "CI BAL.": ("print", "ciBalDot"),
    "OP BAL.": ("print", "opBalDot"),
    "OI BAL.": ("print", "oiBalDot"),
    "INST. DUE": ("print", "instDue"),
    "PARTICULAR": ("print", "particular"),
    "TRANS. DATE": ("print", "transDate"),
    "DISB. AMOUNT": ("print", "disbAmount"),
    "CURR. PRN. PAID": ("print", "currPrnPaid"),
    "CURR. INTT. PAID": ("print", "currInttPaid"),
    "OD. PRN. PAID": ("print", "odPrnPaid"),
    "OD. INTT. PAID": ("print", "odInttPaid"),
    "CURR. OUTS.": ("print", "currOuts"),
    "OD. OUTS.": ("print", "odOuts"),
    "DUE INTT.": ("print", "dueIntt"),
    "DUE MONTH": ("print", "dueMonth"),
    "START DATE": ("print", "startDate"),
    "FINAL REPAY DATE": ("print", "finalRepayDate"),
    "OD PRINCIPAL": ("print", "odPrincipal"),
    "OD INTEREST": ("print", "odInterest"),
    "INSTALMENT NO.": ("print", "instalmentNo"),
    "DUE DATE": ("print", "dueDate"),
    "BALANCE": ("print", "balance"),
    "TOTAL INSTALMENT AMOUNT": ("print", "totalInstalmentAmount"),
}


def to_camel(s: str) -> str:
    s = s.strip()
    # placeholders
    if s.lower().startswith("enter "):
        rest = s[6:]
        parts = re.findall(r"[A-Za-z0-9]+", rest)
        if not parts:
            return "enter"
        return "enter" + "".join(p[:1].upper() + p[1:] for p in parts)
    if s.lower().startswith("select "):
        rest = s[7:]
        parts = re.findall(r"[A-Za-z0-9]+", rest)
        return "select" + "".join(p[:1].upper() + p[1:] for p in parts)
    if s.lower().startswith("search "):
        rest = s[7:].rstrip(".")
        parts = re.findall(r"[A-Za-z0-9]+", rest)
        return "search" + "".join(p[:1].upper() + p[1:] for p in parts)
    parts = re.findall(r"[A-Za-z0-9]+", s)
    if not parts:
        return "key"
    first = parts[0]
    first = first[:1].lower() + first[1:]
    return first + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def build_string_map(strings: list[str]) -> dict[str, str | tuple[str, str]]:
    used: dict[str, str] = {}  # flat key -> eng
    print_used: dict[str, str] = {}
    result: dict[str, str | tuple[str, str]] = {}
    skip = {"#", "0.00"}
    for eng in strings:
        if eng in skip:
            continue
        if "\n" in eng or "setIsOpen" in eng or "generatePDF" in eng or "setOpen" in eng or "setShow" in eng or "setDelete" in eng or "setSecurity" in eng:
            continue
        if eng in OVERRIDES:
            result[eng] = OVERRIDES[eng]
            continue
        # ALL CAPS-ish print headers (mostly uppercase letters)
        letters = re.sub(r"[^A-Za-z]", "", eng)
        if letters and letters == letters.upper() and len(eng) > 1 and eng not in (
            "ROI",
            "ECS Account",
            "EMI Amount",
            "CIF No.",
            "CIF. No.",
            "OD Interest",
            "OD Principal",
        ):
            key = to_camel(eng.lower().replace(".", " "))
            # ensure unique in print
            base = key
            i = 2
            while key in print_used and print_used[key] != eng:
                key = f"{base}{i}"
                i += 1
            print_used[key] = eng
            result[eng] = ("print", key)
            continue
        key = to_camel(eng)
        base = key
        i = 2
        while key in used and used[key] != eng:
            key = f"{base}{i}"
            i += 1
        used[key] = eng
        result[eng] = key
    return result


def load_strings() -> list[str]:
    p = Path(__file__).with_name("_loan_strings.json")
    return json.loads(p.read_text(encoding="utf-8"))


def build_en_tree(string_map: dict[str, str | tuple[str, str]]) -> dict:
    tree: dict = {"print": {}}
    for eng, key in string_map.items():
        if isinstance(key, tuple):
            tree["print"][key[1]] = eng
        else:
            tree[key] = eng
    # ensure toast key exists even if not in dump
    tree.setdefault("failedToDownloadPdf", "Failed to download PDF")
    tree.setdefault("loanRepaymentRegisterFrom", "Loan Repayment Register From")
    return tree


# Hindi / Bengali / Odia translations for every English string
# Missing entries fall back to English (should be rare after fill).
TR_HI: dict[str, str] = {}
TR_BN: dict[str, str] = {}
TR_OR: dict[str, str] = {}


def _seed_translations():
    """Populate TR_* for all known English UI strings."""
    pairs = [
        ("Loan Report", "ऋण रिपोर्ट", "ঋণ রিপোর্ট", "ଋଣ ରିପୋର୍ଟ"),
        ("From Date", "से तिथि", "থেকে তারিখ", "ଠାରୁ ତାରିଖ"),
        ("To Date", "तक तिथि", "পর্যন্ত তারিখ", "ପର୍ଯ୍ୟନ୍ତ ତାରିଖ"),
        ("Loan Product", "ऋण उत्पाद", "ঋণ পণ্য", "ଋଣ ଉତ୍ପାଦ"),
        ("Select loan product", "ऋण उत्पाद चुनें", "ঋণ পণ্য নির্বাচন করুন", "ଋଣ ଉତ୍ପାଦ ବାଛନ୍ତୁ"),
        ("Search loan product...", "ऋण उत्पाद खोजें...", "ঋণ পণ্য খুঁজুন...", "ଋଣ ଉତ୍ପାଦ ଖୋଜନ୍ତୁ..."),
        ("Report Type", "रिपोर्ट प्रकार", "রিপোর্টের ধরন", "ରିପୋର୍ଟ ପ୍ରକାର"),
        ("Select report type", "रिपोर्ट प्रकार चुनें", "রিপোর্টের ধরন নির্বাচন করুন", "ରିପୋର୍ଟ ପ୍ରକାର ବାଛନ୍ତୁ"),
        ("Search report type...", "रिपोर्ट प्रकार खोजें...", "রিপোর্টের ধরন খুঁজুন...", "ରିପୋର୍ଟ ପ୍ରକାର ଖୋଜନ୍ତୁ..."),
        ("Branch", "शाखा", "শাখা", "ଶାଖା"),
        ("Select branch", "शाखा चुनें", "শাখা নির্বাচন করুন", "ଶାଖା ବାଛନ୍ତୁ"),
        ("Search branch...", "शाखा खोजें...", "শাখা খুঁজুন...", "ଶାଖା ଖୋଜନ୍ତୁ..."),
        ("Customer Name", "ग्राहक का नाम", "গ্রাহকের নাম", "ଗ୍ରାହକଙ୍କ ନାମ"),
        ("Guardian Name", "अभिभावक का नाम", "অভিভাবকের নাম", "ଅଭିଭାବକଙ୍କ ନାମ"),
        ("Gurdian Name", "अभिभावक का नाम", "অভিভাবকের নাম", "ଅଭିଭାବକଙ୍କ ନାମ"),
        ("Account No.", "खाता संख्या", "অ্যাকাউন্ট নং", "ଖାତା ନଂ"),
        ("Account No", "खाता संख्या", "অ্যাকাউন্ট নং", "ଖାତା ନଂ"),
        ("Ref. Ac. No.", "संदर्भ खाता संख्या", "রেফ. অ্যাকাউন্ট নং", "ରେଫ୍ ଖାତା ନଂ"),
        ("Date", "तिथि", "তারিখ", "ତାରିଖ"),
        ("Sl No.", "क्रमांक", "ক্রমিক নং", "କ୍ରମିକ ନଂ"),
        ("Sl. No.", "क्रमांक", "ক্রমিক নং", "କ୍ରମିକ ନଂ"),
        ("Sl", "क्र.", "ক্র.", "କ୍ର."),
        ("Disburse", "वितरण", "বিতরণ", "ବିତରଣ"),
        ("Share", "शेयर", "শেয়ার", "ସେୟାର"),
        ("Ins. Amt.", "बीमा राशि", "বীমা পরিমাণ", "ବୀମା ରାଶି"),
        ("Mis. Amt.", "विविध राशि", "বিবিধ পরিমাণ", "ବିବିଧ ରାଶି"),
        ("Net Disburse", "शुद्ध वितरण", "নেট বিতরণ", "ନେଟ୍ ବିତରଣ"),
        ("Trans. Mode", "लेनदेन मोड", "লেনদেনের মোড", "ଲେନଦେନ ମୋଡ୍"),
        ("Principal", "मूलधन", "আসল", "ମୂଳଧନ"),
        ("Interest", "ब्याज", "সুদ", "ସୁଧ"),
        ("Amount", "राशि", "পরিমাণ", "ରାଶି"),
        ("Action", "कार्रवाई", "কার্যক্রম", "କାର୍ଯ୍ୟ"),
        ("Repayment", "पुनर्भुगतान", "পরিশোধ", "ପରିଶୋଧ"),
        ("Outstanding", "बकाया", "বকেয়া", "ବକେୟା"),
        ("Outs. Interest", "बकाया ब्याज", "বকেয়া সুদ", "ବକେୟା ସୁଧ"),
        ("Current", "वर्तमान", "বর্তমান", "ବର୍ତ୍ତମାନ"),
        ("Overdue", "अतिदेय", "ওভারডিউ", "ଅତିଦେୟ"),
        ("Opening", "प्रारंभिक", "প্রারম্ভিক", "ପ୍ରାରମ୍ଭିକ"),
        ("Loan Date", "ऋण तिथि", "ঋণের তারিখ", "ଋଣ ତାରିଖ"),
        ("Subtotal", "उप-योग", "উপমোট", "ଉପମୋଟ"),
        ("Sub Total", "उप-योग", "উপমোট", "ଉପମୋଟ"),
        ("Total", "कुल", "মোট", "ମୋଟ"),
        ("Grand Total", "कुल योग", "সর্বমোট", "ସର୍ବମୋଟ"),
        ("Generated By:", "द्वारा बनाया गया:", "তৈরি করেছেন:", "ତିଆରି କରିଛନ୍ତି:"),
        ("Generated By", "द्वारा बनाया गया", "তৈরি করেছেন", "ତିଆରି କରିଛନ୍ତି"),
        ("Generated On:", "बनाने की तिथि:", "তৈরির তারিখ:", "ତିଆରି ତାରିଖ:"),
        ("Generated On", "बनाने की तिथि", "তৈরির তারিখ", "ତିଆରି ତାରିଖ"),
        ("This report is generated by PrioSuite.", "यह रिपोर्ट PrioSuite द्वारा बनाई गई है।", "এই রিপোর্ট PrioSuite দ্বারা তৈরি।", "ଏହି ରିପୋର୍ଟ PrioSuite ଦ୍ୱାରା ତିଆରି।"),
        ("Loan Disburse Register From", "ऋण वितरण रजिस्टर से", "ঋণ বিতরণ রেজিস্টার থেকে", "ଋଣ ବିତରଣ ରେଜିଷ୍ଟରରୁ"),
        ("Loan Repayment Register From", "ऋण पुनर्भुगतान रजिस्टर से", "ঋণ পরিশোধ রেজিস্টার থেকে", "ଋଣ ପରିଶୋଧ ରେଜିଷ୍ଟରରୁ"),
        ("Loan Detailed List From", "ऋण विस्तृत सूची से", "ঋণ বিস্তারিত তালিকা থেকে", "ଋଣ ବିସ୍ତୃତ ତାଲିକାରୁ"),
        ("Nothing to download. Please generate the report first.", "डाउनलोड करने के लिए कुछ नहीं। पहले रिपोर्ट बनाएं।", "ডাউনলোড করার কিছু নেই। আগে রিপোর্ট তৈরি করুন।", "ଡାଉନଲୋଡ୍ କରିବାକୁ କିଛି ନାହିଁ। ପ୍ରଥମେ ରିପୋର୍ଟ ତିଆରି କରନ୍ତୁ।"),
        ("No loan report data to download.", "डाउनलोड के लिए ऋण रिपोर्ट डेटा नहीं।", "ডাউনলোডের জন্য ঋণ রিপোর্ট ডেটা নেই।", "ଡାଉନଲୋଡ୍ ପାଇଁ ଋଣ ରିପୋର୍ଟ ତଥ୍ୟ ନାହିଁ।"),
        ("Failed to capture report for PDF.", "PDF के लिए रिपोर्ट कैप्चर विफल।", "PDF-এর জন্য রিপোর্ট ক্যাপচার ব্যর্থ।", "PDF ପାଇଁ ରିପୋର୍ଟ କ୍ୟାପଚର ବିଫଳ।"),
        ("PDF downloaded", "PDF डाउनलोड हो गया", "PDF ডাউনলোড হয়েছে", "PDF ଡାଉନଲୋଡ୍ ହେଲା"),
        ("Failed to download PDF", "PDF डाउनलोड विफल", "PDF ডাউনলোড ব্যর্থ", "PDF ଡାଉନଲୋଡ୍ ବିଫଳ"),
        ("Account Statement", "खाता विवरण", "অ্যাকাউন্ট স্টেটমেন্ট", "ଖାତା ବିବରଣୀ"),
        ("Defaulter List", "डिफॉल्टर सूची", "ডিফল্টার তালিকা", "ଡିଫଲ୍ଟର ତାଲିକା"),
        ("Defaulters List", "डिफॉल्टर सूची", "ডিফল্টার তালিকা", "ଡିଫଲ୍ଟର ତାଲିକା"),
        ("Final Repay List", "अंतिम भुगतान सूची", "চূড়ান্ত পরিশোধ তালিকা", "ଚୂଡ଼ାନ୍ତ ପରିଶୋଧ ତାଲିକା"),
        ("Loan Disburse", "ऋण वितरण", "ঋণ বিতরণ", "ଋଣ ବିତରଣ"),
        ("Generate Schedule", "अनुसूची बनाएं", "সময়সূচি তৈরি করুন", "ସମୟସୂଚୀ ତିଆରି କରନ୍ତୁ"),
        ("Loan Repayment Schedule", "ऋण पुनर्भुगतान अनुसूची", "ঋণ পরিশোধ সময়সূচি", "ଋଣ ପରିଶୋଧ ସମୟସୂଚୀ"),
        ("Guarantor Details", "गारंटर विवरण", "জামিনদারের বিবরণ", "ଜାମିନଦାର ବିବରଣୀ"),
        ("Guarantor Release", "गारंटर रिहाई", "জামিনদার মুক্তি", "ଜାମିନଦାର ମୁକ୍ତି"),
        ("New Application", "नया आवेदन", "নতুন আবেদন", "ନୂତନ ଆବେଦନ"),
        ("Passbook Print", "पासबुक प्रिंट", "পাসবুক প্রিন্ট", "ପାସବୁକ୍ ପ୍ରିଣ୍ଟ"),
        ("Loan Repayment", "ऋण पुनर्भुगतान", "ঋণ পরিশোধ", "ଋଣ ପରିଶୋଧ"),
        ("Collection Receipt", "संग्रह रसीद", "সংগ্রহ রসিদ", "ସଂଗ୍ରହ ରସିଦ"),
        ("Loan Collection Receipt", "ऋण संग्रह रसीद", "ঋণ সংগ্রহ রসিদ", "ଋଣ ସଂଗ୍ରହ ରସିଦ"),
        ("Search", "खोजें", "অনুসন্ধান", "ଖୋଜନ୍ତୁ"),
        ("Cancel", "रद्द करें", "বাতিল", "ବାତିଲ୍"),
        ("Print", "प्रिंट", "প্রিন্ট", "ପ୍ରିଣ୍ଟ"),
        ("Save", "सहेजें", "সংরক্ষণ", "ସଂରକ୍ଷଣ"),
        ("Add", "जोड़ें", "যোগ করুন", "ଯୋଗ କରନ୍ତୁ"),
        ("Next", "आगे", "পরবর্তী", "ପରବର୍ତ୍ତୀ"),
        ("Yes", "हाँ", "হ্যাঁ", "ହଁ"),
        ("No", "नहीं", "না", "ନା"),
        ("Close", "बंद करें", "বন্ধ করুন", "ବନ୍ଦ କରନ୍ତୁ"),
        ("Cash", "नकद", "নগদ", "ନଗଦ"),
        ("Bank", "बैंक", "ব্যাংক", "ବ୍ୟାଙ୍କ"),
        ("Savings", "बचत", "সঞ্চয়", "ସଞ୍ଚୟ"),
        ("Member Name", "सदस्य का नाम", "সদস্যের নাম", "ସଦସ୍ୟଙ୍କ ନାମ"),
        ("Member No.", "सदस्य संख्या", "সদস্য নং", "ସଦସ୍ୟ ନଂ"),
        ("Member No", "सदस्य संख्या", "সদস্য নং", "ସଦସ୍ୟ ନଂ"),
        ("Mobile No.", "मोबाइल नंबर", "মোবাইল নং", "ମୋବାଇଲ୍ ନଂ"),
        ("Address", "पता", "ঠিকানা", "ଠିକଣା"),
        ("Name", "नाम", "নাম", "ନାମ"),
        ("Balance", "शेष", "ব্যালেন্স", "ବାଲାନ୍ସ"),
        ("Product Name", "उत्पाद नाम", "পণ্যের নাম", "ଉତ୍ପାଦ ନାମ"),
        ("Product Type", "उत्पाद प्रकार", "পণ্যের ধরন", "ଉତ୍ପାଦ ପ୍ରକାର"),
        ("Product", "उत्পাদ", "পণ্য", "ଉତ୍ପାଦ"),
        ("ROI", "ब्याज दर", "সুদের হার", "ସୁଧ ହାର"),
        ("As On Date", "तिथि तक", "তারিখ অনুযায়ী", "ତାରିଖ ଅନୁଯାୟୀ"),
        ("From Month", "से माह", "থেকে মাস", "ଠାରୁ ମାସ"),
        ("To Month", "तक माह", "পর্যন্ত মাস", "ପର୍ଯ୍ୟନ୍ତ ମାସ"),
        ("View Type", "दृश्य प्रकार", "দেখার ধরন", "ଦେଖିବା ପ୍ରକାର"),
        ("With Guarantor", "गारंटर के साथ", "জামিনদারসহ", "ଜାମିନଦାର ସହିତ"),
        ("Without Guarantor", "गारंटर के बिना", "জামিনদার ছাড়া", "ଜାମିନଦାର ବିନା"),
        ("Front Page", "मुख पृष्ठ", "প্রথম পৃষ্ঠা", "ପ୍ରଥମ ପୃଷ୍ଠା"),
        ("Transaction Page", "लेनदेन पृष्ठ", "লেনদেনের পৃষ্ঠা", "ଲେନଦେନ ପୃଷ୍ଠା"),
        ("Line", "पंक्ति", "লাইন", "ଲାଇନ୍"),
        ("Enter line", "पंक्ति दर्ज करें", "লাইন লিখুন", "ଲାଇନ୍ ଲେଖନ୍ତୁ"),
        ("Search Account", "खाता खोजें", "অ্যাকাউন্ট খুঁজুন", "ଖାତା ଖୋଜନ୍ତୁ"),
        ("Search Members", "सदस्य खोजें", "সদস্য খুঁজুন", "ସଦସ୍ୟ ଖୋଜନ୍ତୁ"),
        ("Account Details", "खाता विवरण", "অ্যাকাউন্ট বিবরণ", "ଖାତା ବିବରଣୀ"),
        ("Transaction Details", "लेनदेन विवरण", "লেনদেনের বিবরণ", "ଲେନଦେନ ବିବରଣୀ"),
        ("Transanction Block", "लेनदेन ब्लॉक", "লেনদেন ব্লক", "ଲେନଦେନ ବ୍ଲକ୍"),
        ("Application Block", "आवेदन ब्लॉक", "আবেদন ব্লক", "ଆବେଦନ ବ୍ଲକ୍"),
        ("Disburse Block", "वितरण ब्लॉक", "বিতরণ ব্লক", "ବିତରଣ ବ୍ଲକ୍"),
        ("Basic Info Block", "मूल जानकारी ब्लॉक", "মৌলিক তথ্য ব্লক", "ମୌଳିକ ତଥ୍ୟ ବ୍ଲକ୍"),
        ("Application Info Block", "आवेदन जानकारी ब्लॉक", "আবেদন তথ্য ব্লক", "ଆବେଦନ ତଥ୍ୟ ବ୍ଲକ୍"),
        ("No records found.", "कोई रिकॉर्ड नहीं मिला।", "কোনো রেকর্ড পাওয়া যায়নি।", "କୌଣସି ରେକର୍ଡ ମିଳିଲା ନାହିଁ।"),
        ("Please enter name", "कृपया नाम दर्ज करें", "অনুগ্রহ করে নাম লিখুন", "ଦୟାକରି ନାମ ଲେଖନ୍ତୁ"),
        ("You Cannot Add Same Customer As Joint Holder!", "आप उसी ग्राहक को संयुक्त धारक नहीं जोड़ सकते!", "আপনি একই গ্রাহককে যৌথ ধারক হিসেবে যোগ করতে পারবেন না!", "ଆପଣ ସମାନ ଗ୍ରାହକଙ୍କୁ ଯୌଥ ଧାରକ ଭାବେ ଯୋଗ କରିପାରିବେ ନାହିଁ!"),
        ("This member is already added as a joint holder!", "यह सदस्य पहले से संयुक्त धारक है!", "এই সদস্য ইতিমধ্যে যৌথ ধারক!", "ଏହି ସଦସ୍ୟ ପୂର୍ବରୁ ଯୌଥ ଧାରକ!"),
        ("A member with this Customer Number already exists!", "इस ग्राहक संख्या वाला सदस्य पहले से मौजूद है!", "এই গ্রাহক নম্বরের সদস্য ইতিমধ্যে আছে!", "ଏହି ଗ୍ରାହକ ନମ୍ବରର ସଦସ୍ୟ ପୂର୍ବରୁ ଅଛନ୍ତି!"),
        ("Failed to process deductions", "कटौती प्रक्रिया विफल", "কর্তন প্রক্রিয়া ব্যর্থ", "କଟତି ପ୍ରକ୍ରିୟା ବିଫଳ"),
        ("Please All Field is required", "कृपया सभी फ़ील्ड आवश्यक हैं", "অনুগ্রহ করে সব ক্ষেত্র আবশ্যক", "ଦୟାକରି ସମସ୍ତ କ୍ଷେତ୍ର ଆବଶ୍ୟକ"),
        ("Are you sure you want to release the guarantor?", "क्या आप गारंटर को रिहा करना चाहते हैं?", "আপনি কি জামিনদারকে মুক্ত করতে চান?", "ଆପଣ ଜାମିନଦାରଙ୍କୁ ମୁକ୍ତ କରିବାକୁ ଚାହାଁନ୍ତି କି?"),
        ("Self", "स्वयं", "নিজে", "ନିଜେ"),
        ("External", "बाहरी", "বাহ্যিক", "ବାହ୍ୟ"),
        ("Internal", "आंतरिक", "অভ্যন্তরীণ", "ଆଭ୍ୟନ୍ତରୀଣ"),
        ("Individual Customer", "व्यक्तिगत ग्राहक", "ব্যক্তিগত গ্রাহক", "ବ୍ୟକ୍ତିଗତ ଗ୍ରାହକ"),
        ("Security Based", "सुरक्षा आधारित", "নিরাপত্তা ভিত্তিক", "ସୁରକ୍ଷା ଭିତ୍ତିକ"),
        ("Guarantor Based", "गारंटर आधारित", "জামিনদার ভিত্তিক", "ଜାମିନଦାର ଭିତ୍ତିକ"),
        ("Project Based", "परियोजना आधारित", "প্রকল্প ভিত্তিক", "ପ୍ରକଳ୍ପ ଭିତ୍ତିକ"),
        ("Group Based", "समूह आधारित", "গ্রুপ ভিত্তিক", "ଗୋଷ୍ଠୀ ଭିତ୍ତିକ"),
        ("Joint - Either or Survivor", "संयुक्त - कोई भी या उत्तरजीवी", "যৌথ - যেকোনো বা উত্তরজীবী", "ଯୌଥ - ଯେକୌଣସି କିମ୍ବା ଉତ୍ତରଜୀବୀ"),
        ("Joint - Former or Survivor", "संयुक्त - पूर्व या उत्तरजीवी", "যৌথ - পূর্ববর্তী বা উত্তরজীবী", "ଯୌଥ - ପୂର୍ବ କିମ୍ବା ଉତ୍ତରଜୀବୀ"),
        ("Select bank", "बैंक चुनें", "ব্যাংক নির্বাচন করুন", "ବ୍ୟାଙ୍କ ବାଛନ୍ତୁ"),
        ("Search bank...", "बैंक खोजें...", "ব্যাংক খুঁজুন...", "ବ୍ୟାଙ୍କ ଖୋଜନ୍ତୁ..."),
        ("Select savings", "बचत चुनें", "সঞ্চয় নির্বাচন করুন", "ସଞ୍ଚୟ ବାଛନ୍ତୁ"),
        ("Search savings...", "बचत खोजें...", "সঞ্চয় খুঁজুন...", "ସଞ୍ଚୟ ଖୋଜନ୍ତୁ..."),
        ("Select transanction mode", "लेनदेन मोड चुनें", "লেনদেনের মোড নির্বাচন করুন", "ଲେନଦେନ ମୋଡ୍ ବାଛନ୍ତୁ"),
        ("Enter account no.", "खाता संख्या दर्ज करें", "অ্যাকাউন্ট নং লিখুন", "ଖାତା ନଂ ଲେଖନ୍ତୁ"),
        ("Enter member name", "सदस्य नाम दर्ज करें", "সদস্যের নাম লিখুন", "ସଦସ୍ୟ ନାମ ଲେଖନ୍ତୁ"),
        ("Enter gurdian name", "अभिभावक नाम दर्ज करें", "অভিভাবকের নাম লিখুন", "ଅଭିଭାବକ ନାମ ଲେଖନ୍ତୁ"),
        ("Enter address", "पता दर्ज करें", "ঠিকানা লিখুন", "ଠିକଣା ଲେଖନ୍ତୁ"),
        ("Enter mobile no.", "मोबाइल नंबर दर्ज करें", "মোবাইল নং লিখুন", "ମୋବାଇଲ୍ ନଂ ଲେଖନ୍ତୁ"),
        ("Enter member no.", "सदस्य संख्या दर्ज करें", "সদস্য নং লিখুন", "ସଦସ୍ୟ ନଂ ଲେଖନ୍ତୁ"),
        ("Enter from month", "से माह दर्ज करें", "থেকে মাস লিখুন", "ଠାରୁ ମାସ ଲେଖନ୍ତୁ"),
        ("Enter to month", "तक माह दर्ज करें", "পর্যন্ত মাস লিখুন", "ପର୍ଯ୍ୟନ୍ତ ମାସ ଲେଖନ୍ତୁ"),
        ("Search by enter member no.", "सदस्य संख्या से खोजें", "সদস্য নং দিয়ে খুঁজুন", "ସଦସ୍ୟ ନଂ ଦ୍ୱାରା ଖୋଜନ୍ତୁ"),
        ("Search by enter name", "नाम से खोजें", "নাম দিয়ে খুঁজুন", "ନାମ ଦ୍ୱାରା ଖୋଜନ୍ତୁ"),
        ("Search by enter member name", "सदस्य नाम से खोजें", "সদস্যের নাম দিয়ে খুঁজুন", "ସଦସ୍ୟ ନାମ ଦ୍ୱାରା ଖୋଜନ୍ତୁ"),
        ("Search by member name", "सदस्य नाम से खोजें", "সদস্যের নাম দিয়ে খুঁজুন", "ସଦସ୍ୟ ନାମ ଦ୍ୱାରା ଖୋଜନ୍ତୁ"),
        ("Confirm", "पुष्टि करें", "নিশ্চিত করুন", "ନିଶ୍ଚିତ କରନ୍ତୁ"),
        ("Remove", "हटाएं", "সরান", "ହଟାନ୍ତୁ"),
        ("Done", "पूर्ण", "সম্পন্ন", "ସମ୍ପନ୍ନ"),
        ("Reset", "रीसेट", "রিসেট", "ରିସେଟ୍"),
        ("Clear", "साफ़ करें", "মুছুন", "ସଫା କରନ୍ତୁ"),
        ("Submit", "जमा करें", "জমা দিন", "ଦାଖଲ କରନ୍ତୁ"),
        ("Update", "अपडेट", "আপডেট", "ଅପଡେଟ୍"),
        ("Edit", "संपादित करें", "সম্পাদনা", "ସମ୍ପାଦନା"),
        ("Run", "चलाएं", "চালান", "ଚଲାନ୍ତୁ"),
        ("Fetch Details", "विवरण लाएं", "বিবরণ আনুন", "ବିବରଣୀ ଆଣନ୍ତୁ"),
    ]
    for eng, hi, bn, od in pairs:
        TR_HI[eng] = hi
        TR_BN[eng] = bn
        TR_OR[eng] = od

    # Bulk common form labels (EN kept exact; translate meaningfully)
    more = {
        "Account Balance": ("खाता शेष", "অ্যাকাউন্ট ব্যালেন্স", "ଖାତା ବାଲାନ୍ସ"),
        "Account Holder Name": ("खाताधारक का नाम", "অ্যাকাউন্টধারীর নাম", "ଖାତାଧାରୀଙ୍କ ନାମ"),
        "Account Name": ("खाता नाम", "অ্যাকাউন্টের নাম", "ଖାତା ନାମ"),
        "Account Type": ("खाता प्रकार", "অ্যাকাউন্টের ধরন", "ଖାତା ପ୍ରକାର"),
        "Applicant Name": ("आवेदक का नाम", "আবেদনকারীর নাম", "ଆବେଦନକାରୀଙ୍କ ନାମ"),
        "Application Amount": ("आवेदन राशि", "আবেদনের পরিমাণ", "ଆବେଦନ ରାଶି"),
        "Application Date": ("आवेदन तिथि", "আবেদনের তারিখ", "ଆବେଦନ ତାରିଖ"),
        "Application No": ("आवेदन संख्या", "আবেদন নং", "ଆବେଦନ ନଂ"),
        "Application No.": ("आवेदन संख्या", "আবেদন নং", "ଆବେଦନ ନଂ"),
        "Available Balance": ("उपलब्ध शेष", "উপলব্ধ ব্যালেন্স", "ଉପଲବ୍ଧ ବାଲାନ୍ସ"),
        "Bond No.": ("बॉन्ड संख्या", "বন্ড নং", "ବଣ୍ଡ ନଂ"),
        "Branch Name": ("शाखा नाम", "শাখার নাম", "ଶାଖା ନାମ"),
        "CIF No.": ("CIF संख्या", "CIF নং", "CIF ନଂ"),
        "CIF. No.": ("CIF संख्या", "CIF নং", "CIF ନଂ"),
        "Certificate No": ("प्रमाणपत्र संख्या", "সার্টিফিকেট নং", "ସାର୍ଟିଫିକେଟ୍ ନଂ"),
        "Certificate No.": ("प्रमाणपत्र संख्या", "সার্টিফিকেট নং", "ସାର୍ଟିଫିକେଟ୍ ନଂ"),
        "Certificate Type": ("प्रमाणपत्र प्रकार", "সার্টিফিকেটের ধরন", "ସାର୍ଟିଫିକେଟ୍ ପ୍ରକାର"),
        "Charge Name": ("शुल्क नाम", "চার্জের নাম", "ଚାର୍ଜ ନାମ"),
        "Co Owner Name": ("सह-स्वामी का नाम", "সহ-মালিকের নাম", "ସହ-ମାଲିକଙ୍କ ନାମ"),
        "Co Owner Name (If Any)": ("सह-स्वामी का नाम (यदि हो)", "সহ-মালিকের নাম (যদি থাকে)", "ସହ-ମାଲିକଙ୍କ ନାମ (ଯଦି ଥାଏ)"),
        "Curr. Intt. Paid": ("वर्तमान ब्याज भुगतान", "বর্তমান সুদ পরিশোধ", "ବର୍ତ୍ତମାନ ସୁଧ ପରିଶୋଧ"),
        "Curr. Outs.": ("वर्तमान बकाया", "বর্তমান বকেয়া", "ବର୍ତ୍ତମାନ ବକେୟା"),
        "Curr. Prn. Paid": ("वर्तमान मूल भुगतान", "বর্তমান আসল পরিশোধ", "ବର୍ତ୍ତମାନ ମୂଳ ପରିଶୋଧ"),
        "Current Amount": ("वर्तमान राशि", "বর্তমান পরিমাণ", "ବର୍ତ୍ତମାନ ରାଶି"),
        "Current Days": ("वर्तमान दिन", "বর্তমান দিন", "ବର୍ତ୍ତମାନ ଦିନ"),
        "Current Interest": ("वर्तमान ब्याज", "বর্তমান সুদ", "ବର୍ତ୍ତମାନ ସୁଧ"),
        "Current Principal": ("वर्तमान मूलधन", "বর্তমান আসল", "ବର୍ତ୍ତମାନ ମୂଳଧନ"),
        "Cust No.": ("ग्राहक संख्या", "গ্রাহক নং", "ଗ୍ରାହକ ନଂ"),
        "Customer Type": ("ग्राहक प्रकार", "গ্রাহকের ধরন", "ଗ୍ରାହକ ପ୍ରକାର"),
        "Deductions": ("कटौतियाँ", "কর্তন", "କଟତି"),
        "Demand Principal": ("मांग मूलधन", "চাহিদা আসল", "ଚାହିଦା ମୂଳଧନ"),
        "Deposit Amount": ("जमा राशि", "আমানতের পরিমাণ", "ଜମା ରାଶି"),
        "Deposit Balance": ("जमा शेष", "আমানত ব্যালেন্স", "ଜମା ବାଲାନ୍ସ"),
        "Deposit Date": ("जमा तिथि", "আমানতের তারিখ", "ଜମା ତାରିଖ"),
        "Deposit/Certificate Security Details": ("जमा/प्रमाणपत्र सुरक्षा विवरण", "আমানত/সার্টিফিকেট জামানত বিবরণ", "ଜମା/ସାର୍ଟିଫିକେଟ୍ ସୁରକ୍ଷା ବିବରଣୀ"),
        "Designation": ("पदनाम", "পদবি", "ପଦବୀ"),
        "Details": ("विवरण", "বিবরণ", "ବିବରଣୀ"),
        "Disb. Amount": ("वितरण राशि", "বিতরণের পরিমাণ", "ବିତରଣ ରାଶି"),
        "Disburse Amount": ("वितरण राशि", "বিতরণের পরিমাণ", "ବିତରଣ ରାଶି"),
        "Disburse Date": ("वितरण तिथि", "বিতরণের তারিখ", "ବିତରଣ ତାରିଖ"),
        "Due Date": ("नियत तिथि", "নির্ধারিত তারিখ", "ନିର୍ଦ୍ଧାରିତ ତାରିଖ"),
        "Due Intt.": ("देय ब्याज", "বকেয়া সুদ", "ଦେୟ ସୁଧ"),
        "Due Month": ("देय माह", "বকেয়া মাস", "ଦେୟ ମାସ"),
        "Duration Unit": ("अवधि इकाई", "সময়কাল একক", "ଅବଧି ଏକକ"),
        "ECS Account": ("ECS खाता", "ECS অ্যাকাউন্ট", "ECS ଖାତା"),
        "EMI Amount": ("EMI राशि", "EMI পরিমাণ", "EMI ରାଶି"),
        "Final Repay Date": ("अंतिम भुगतान तिथि", "চূড়ান্ত পরিশোধের তারিখ", "ଚୂଡ଼ାନ୍ତ ପରିଶୋଧ ତାରିଖ"),
        "Final Repayment Date": ("अंतिम पुनर्भुगतान तिथि", "চূড়ান্ত পরিশোধের তারিখ", "ଚୂଡ଼ାନ୍ତ ପରିଶୋଧ ତାରିଖ"),
        "Full Name": ("पूरा नाम", "পূর্ণ নাম", "ପୂର୍ଣ୍ଣ ନାମ"),
        "Guarantor / Security Details": ("गारंटर / सुरक्षा विवरण", "জামিনদার / জামানত বিবরণ", "ଜାମିନଦାର / ସୁରକ୍ଷା ବିବରଣୀ"),
        "Guarantor Name": ("गारंटर का नाम", "জামিনদারের নাম", "ଜାମିନଦାରଙ୍କ ନାମ"),
        "Hypothecation": ("बंधक", "বন্ধক", "ବନ୍ଧକ"),
        "Hypothicated Value": ("बंधक मूल्य", "বন্ধক মূল্য", "ବନ୍ଧକ ମୂଲ୍ୟ"),
        "Income Generated": ("अर्जित आय", "অর্জিত আয়", "ଅର୍ଜିତ ଆୟ"),
        "Installment Amount": ("किस्त राशि", "কিস্তির পরিমাণ", "କିସ୍ତି ରାଶି"),
        "Instalment No.": ("किस्त संख्या", "কিস্তি নং", "କିସ୍ତି ନଂ"),
        "Internal Deposit Security": ("आंतरिक जमा सुरक्षा", "অভ্যন্তরীণ আমানত জামানত", "ଆଭ୍ୟନ୍ତରୀଣ ଜମା ସୁରକ୍ଷା"),
        "Is Avail ECS": ("ECS उपलब्ध है", "ECS উপলব্ধ", "ECS ଉପଲବ୍ଧ"),
        "Issue Amount": ("जारी राशि", "ইস্যু পরিমাণ", "ଇସ୍ୟୁ ରାଶି"),
        "Issue Date": ("जारी तिथि", "ইস্যুর তারিখ", "ଇସ୍ୟୁ ତାରିଖ"),
        "Item Brand": ("वस्तु ब्रांड", "আইটেম ব্র্যান্ড", "ଆଇଟମ୍ ବ୍ରାଣ୍ଡ"),
        "Item Cost": ("वस्तु लागत", "আইটেম খরচ", "ଆଇଟମ୍ ଖର୍ଚ୍ଚ"),
        "Item Details": ("वस्तु विवरण", "আইটেম বিবরণ", "ଆଇଟମ୍ ବିବରଣୀ"),
        "Item Name": ("वस्तु नाम", "আইটেমের নাম", "ଆଇଟମ୍ ନାମ"),
        "Joining Date": ("जॉइनिंग तिथि", "যোগদানের তারিখ", "ଯୋଗଦାନ ତାରିଖ"),
        "Joint Holder's Details": ("संयुक्त धारक विवरण", "যৌথ ধারকের বিবরণ", "ଯୌଥ ଧାରକ ବିବରଣୀ"),
        "Land Offered As Security (In Acre)": ("सुरक्षा के रूप में भूमि (एकड़ में)", "জামানত হিসেবে জমি (একরে)", "ସୁରକ୍ଷା ଭାବେ ଜମି (ଏକରରେ)"),
        "Last Repay Date": ("अंतिम भुगतान तिथि", "শেষ পরিশোধের তারিখ", "ଶେଷ ପରିଶୋଧ ତାରିଖ"),
        "Last Repay Interest": ("अंतिम भुगतान ब्याज", "শেষ পরিশোধ সুদ", "ଶେଷ ପରିଶୋଧ ସୁଧ"),
        "Last Repay Principal": ("अंतिम भुगतान मूलधन", "শেষ পরিশোধ আসল", "ଶେଷ ପରିଶୋଧ ମୂଳଧନ"),
        "Latitude": ("अक्षांश", "অক্ষাংশ", "ଅକ୍ଷାଂଶ"),
        "Longitude": ("देशांतर", "দ্রাঘিমাংশ", "ଦ୍ରାଘିମାଂଶ"),
        "Loan Based On": ("ऋण आधारित", "ঋণ ভিত্তিক", "ଋଣ ଭିତ୍ତିକ"),
        "Loan Purpose": ("ऋण उद्देश्य", "ঋণের উদ্দেশ্য", "ଋଣ ଉଦ୍ଦେଶ୍ୟ"),
        "Maturity Amount": ("परिपक्वता राशि", "মেয়াদোত্তীর্ণ পরিমাণ", "ପରିପକ୍ୱତା ରାଶି"),
        "Maturity Date": ("परिपक्वता तिथि", "মেয়াদোত্তীর্ণ তারিখ", "ପରିପକ୍ୱତା ତାରିଖ"),
        "Max Allow": ("अधिकतम अनुमति", "সর্বোচ্চ অনুমোদন", "ସର୍ବାଧିକ ଅନୁମୋଦନ"),
        "Max Loan Amount": ("अधिकतम ऋण राशि", "সর্বোচ্চ ঋণের পরিমাণ", "ସର୍ବାଧିକ ଋଣ ରାଶି"),
        "Max loan amount": ("अधिकतम ऋण राशि", "সর্বোচ্চ ঋণের পরিমাণ", "ସର୍ବାଧିକ ଋଣ ରାଶି"),
        "Member Address": ("सदस्य पता", "সদস্যের ঠিকানা", "ସଦସ୍ୟ ଠିକଣା"),
        "Member Type": ("सदस्य प्रकार", "সদস্যের ধরন", "ସଦସ୍ୟ ପ୍ରକାର"),
        "Mouza": ("मौजा", "মৌজা", "ମୌଜା"),
        "OD Interest": ("अतिदेय ब्याज", "ওভারডিউ সুদ", "ଅତିଦେୟ ସୁଧ"),
        "OD Principal": ("अतिदेय मूलधन", "ওভারডিউ আসল", "ଅତିଦେୟ ମୂଳଧନ"),
        "Od. Intt. Paid": ("अतिदेय ब्याज भुगतान", "ওভারডিউ সুদ পরিশোধ", "ଅତିଦେୟ ସୁଧ ପରିଶୋଧ"),
        "Od. Outs.": ("अतिदेय बकाया", "ওভারডিউ বকেয়া", "ଅତିଦେୟ ବକେୟା"),
        "Od. Prn. Paid": ("अतिदेय मूल भुगतान", "ওভারডিউ আসল পরিশোধ", "ଅତିଦେୟ ମୂଳ ପରିଶୋଧ"),
        "Operation Mode": ("संचालन मोड", "পরিচালনা মোড", "ପରିଚାଳନା ମୋଡ୍"),
        "Other Account": ("अन्य खाता", "অন্য অ্যাকাউন্ট", "ଅନ୍ୟ ଖାତା"),
        "Other Security Details": ("अन्य सुरक्षा विवरण", "অন্যান্য জামানত বিবরণ", "ଅନ୍ୟ ସୁରକ୍ଷା ବିବରଣୀ"),
        "Outstanding Balance": ("बकाया शेष", "বকেয়া ব্যালেন্স", "ବକେୟା ବାଲାନ୍ସ"),
        "Overdue Amount": ("अतिदेय राशि", "ওভারডিউ পরিমাণ", "ଅତିଦେୟ ରାଶି"),
        "Overdue Days": ("अतिदेय दिन", "ওভারডিউ দিন", "ଅତିଦେୟ ଦିନ"),
        "Overdue Interest": ("अतिदेय ब्याज", "ওভারডিউ সুদ", "ଅତିଦେୟ ସୁଧ"),
        "Overdue Principal": ("अतिदेय मूलधन", "ওভারডিউ আসল", "ଅତିଦେୟ ମୂଳଧନ"),
        "Own Account": ("स्वयं का खाता", "নিজের অ্যাকাউন্ট", "ନିଜ ଖାତା"),
        "Own Contribution": ("स्वयं योगदान", "নিজ অবদান", "ନିଜ ଅବଦାନ"),
        "Owner Name": ("स्वामी का नाम", "মালিকের নাম", "ମାଲିକଙ୍କ ନାମ"),
        "Pan No.": ("पैन संख्या", "প্যান নং", "ପ୍ୟାନ୍ ନଂ"),
        "Particular": ("विवरण", "বিবরণ", "ବିବରଣୀ"),
        "Particulars": ("विवरण", "বিবরণ", "ବିବରଣୀ"),
        "Plot No.": ("प्लॉट संख्या", "প্লট নং", "ପ୍ଲଟ୍ ନଂ"),
        "Previous Due Interest": ("पूर्व देय ब्याज", "পূর্ববর্তী বকেয়া সুদ", "ପୂର୍ବ ଦେୟ ସୁଧ"),
        "Project Cost": ("परियोजना लागत", "প্রকল্পের খরচ", "ପ୍ରକଳ୍ପ ଖର୍ଚ୍ଚ"),
        "Project Name": ("परियोजना नाम", "প্রকল্পের নাম", "ପ୍ରକଳ୍ପ ନାମ"),
        "Property Area": ("संपत्ति क्षेत्र", "সম্পত্তির এলাকা", "ସମ୍ପତ୍ତି କ୍ଷେତ୍ର"),
        "Property Details": ("संपत्ति विवरण", "সম্পত্তির বিবরণ", "ସମ୍ପତ୍ତି ବିବରଣୀ"),
        "Property Location": ("संपत्ति स्थान", "সম্পত্তির অবস্থান", "ସମ୍ପତ୍ତି ଅବସ୍ଥାନ"),
        "Property Security Details": ("संपत्ति सुरक्षा विवरण", "সম্পত্তি জামানত বিবরণ", "ସମ୍ପତ୍ତି ସୁରକ୍ଷା ବିବରଣୀ"),
        "Rate Of Interest": ("ब्याज दर", "সুদের হার", "ସୁଧ ହାର"),
        "Ref. Vouch No.": ("संदर्भ वाउचर संख्या", "রেফ. ভাউচার নং", "ରେଫ୍ ଭାଉଚର ନଂ"),
        "Relation": ("संबंध", "সম্পর্ক", "ସମ୍ପର୍କ"),
        "Remove Joint Holder": ("संयुक्त धारक हटाएं", "যৌথ ধারক সরান", "ଯୌଥ ଧାରକ ହଟାନ୍ତୁ"),
        "Repay Mode": ("भुगतान मोड", "পরিশোধ মোড", "ପରିଶୋଧ ମୋଡ୍"),
        "Repayment Mode": ("पुनर्भुगतान मोड", "পরিশোধ মোড", "ପରିଶୋଧ ମୋଡ୍"),
        "Sanction Amount": ("स्वीकृत राशि", "অনুমোদিত পরিমাণ", "ଅନୁମୋଦିତ ରାଶି"),
        "Sanction Date": ("स्वीकृति तिथि", "অনুমোদনের তারিখ", "ଅନୁମୋଦନ ତାରିଖ"),
        "Savings A/C": ("बचत खाता", "সঞ্চয় অ্যাকাউন্ট", "ସଞ୍ଚୟ ଖାତା"),
        "Security Account": ("सुरक्षा खाता", "জামানত অ্যাকাউন্ট", "ସୁରକ୍ଷା ଖାତା"),
        "Security Details": ("सुरक्षा विवरण", "জামানত বিবরণ", "ସୁରକ୍ଷା ବିବରଣୀ"),
        "Security Type": ("सुरक्षा प्रकार", "জামানতের ধরন", "ସୁରକ୍ଷା ପ୍ରକାର"),
        "Security Value": ("सुरक्षा मूल्य", "জামানত মূল্য", "ସୁରକ୍ଷା ମୂଲ୍ୟ"),
        "Share Balance": ("शेयर शेष", "শেয়ার ব্যালেন্স", "ସେୟାର ବାଲାନ୍ସ"),
        "Start Date": ("प्रारंभ तिथि", "শুরুর তারিখ", "ଆରମ୍ଭ ତାରିଖ"),
        "Total Instalment Amount": ("कुल किस्त राशि", "মোট কিস্তির পরিমাণ", "ମୋଟ କିସ୍ତି ରାଶି"),
        "Total Interest": ("कुल ब्याज", "মোট সুদ", "ମୋଟ ସୁଧ"),
        "Total amount in words": ("कुल राशि शब्दों में", "মোট পরিমাণ কথায়", "ମୋଟ ରାଶି ଶବ୍ଦରେ"),
        "Trans. Date": ("लेनदेन तिथि", "লেনদেনের তারিখ", "ଲେନଦେନ ତାରିଖ"),
        "Type Name": ("प्रकार नाम", "ধরনের নাম", "ପ୍ରକାର ନାମ"),
        "Advance Principal": ("अग्रिम मूलधन", "অগ্রিম আসল", "ଅଗ୍ରିମ ମୂଳଧନ"),
        "Receipt Date": ("रसीद तिथि", "রসিদের তারিখ", "ରସିଦ ତାରିଖ"),
        "Receipt No": ("रसीद संख्या", "রসিদ নং", "ରସିଦ ନଂ"),
        "Total Outstanding": ("कुल बकाया", "মোট বকেয়া", "ମୋଟ ବକେୟା"),
        "Pending Inst.": ("लंबित किस्त", "বকেয়া কিস্তি", "ବକେୟା କିସ୍ତି"),
        "Total Rs.": ("कुल रु.", "মোট টাকা", "ମୋଟ ଟଙ୍କା"),
        "Received Mode :": ("प्राप्ति मोड :", "প্রাপ্তি মোড :", "ପ୍ରାପ୍ତି ମୋଡ୍ :"),
        "Received By :": ("प्राप्तकर्ता :", "প্রাপক :", "ପ୍ରାପକ :"),
        "Printed On :": ("मुद्रित तिथि :", "মুদ্রণের তারিখ :", "ମୁଦ୍ରଣ ତାରିଖ :"),
        "Cashier": ("कैशियर", "ক্যাশিয়ার", "କ୍ୟାଶିୟର"),
        "E. & O.E.": ("E. & O.E.", "E. & O.E.", "E. & O.E."),
        "Add.": ("पता", "ঠিকানা", "ଠିକଣା"),
        "Ac. No.": ("खाता सं.", "অ্যাকাউন্ট নং", "ଖାତା ନଂ"),
        "Disb. Date.": ("वितरण तिथि", "বিতরণের তারিখ", "ବିତରଣ ତାରିଖ"),
        "Scheme Name": ("योजना नाम", "স্কিমের নাম", "ଯୋଜନା ନାମ"),
        "Max Loan :": ("अधिकतम ऋण :", "সর্বোচ্চ ঋণ :", "ସର୍ବାଧିକ ଋଣ :"),
        "Member No :": ("सदस्य सं. :", "সদস্য নং :", "ସଦସ୍ୟ ନଂ :"),
        "TF Paid :": ("TF भुगतान :", "TF পরিশোধ :", "TF ପରିଶୋଧ :"),
        "GF Balance :": ("GF शेष :", "GF ব্যালেন্স :", "GF ବାଲାନ୍ସ :"),
        "Account No. :": ("खाता सं. :", "অ্যাকাউন্ট নং :", "ଖାତା ନଂ :"),
        "Scheme Name :": ("योजना नाम :", "স্কিমের নাম :", "ଯୋଜନା ନାମ :"),
        "Issue Date :": ("जारी तिथि :", "ইস্যুর তারিখ :", "ଇସ୍ୟୁ ତାରିଖ :"),
        "Issue Amount :": ("जारी राशि :", "ইস্যু পরিমাণ :", "ଇସ୍ୟୁ ରାଶି :"),
        "Outs. Bal. :": ("बकाया शेष :", "বকেয়া ব্যালেন্স :", "ବକେୟା ବାଲାନ୍ସ :"),
        "CP Bal :": ("CP शेष :", "CP ব্যালেন্স :", "CP ବାଲାନ୍ସ :"),
        "CI Bal :": ("CI शेष :", "CI ব্যালেন্স :", "CI ବାଲାନ୍ସ :"),
        "OP Bal :": ("OP शेष :", "OP ব্যালেন্স :", "OP ବାଲାନ୍ସ :"),
        "OI Bal :": ("OI शेष :", "OI ব্যালেন্স :", "OI ବାଲାନ୍ସ :"),
        "Loan Type - Guarantor": ("ऋण प्रकार - गारंटर", "ঋণের ধরন - জামিনদার", "ଋଣ ପ୍ରକାର - ଜାମିନଦାର"),
        "Loan Type - Own": ("ऋण प्रकार - स्वयं", "ঋণের ধরন - নিজস্ব", "ଋଣ ପ୍ରକାର - ନିଜସ୍ୱ"),
        "Member Name :": ("सदस्य नाम :", "সদস্যের নাম :", "ସଦସ୍ୟ ନାମ :"),
        "Guardian Name :": ("अभिभावक नाम :", "অভিভাবকের নাম :", "ଅଭିଭାବକ ନାମ :"),
        "Address :": ("पता :", "ঠিকানা :", "ଠିକଣା :"),
        "Ref. Ac. No. :": ("संदर्भ खाता :", "রেফ. অ্যাকাউন্ট :", "ରେଫ୍ ଖାତା :"),
        "Ledger Folio :": ("लेजर फोलियो :", "লেজার ফোলিও :", "ଲେଜର ଫୋଲିଓ :"),
        "Disb. Date :": ("वितरण तिथि :", "বিতরণের তারিখ :", "ବିତରଣ ତାରିଖ :"),
        "ROI. :": ("ब्याज दर :", "সুদের হার :", "ସୁଧ ହାର :"),
        "Disb. Amount :": ("वितरण राशि :", "বিতরণের পরিমাণ :", "ବିତରଣ ରାଶି :"),
        "Repay Within :": ("भुगतान अवधि :", "পরিশোধের মধ্যে :", "ପରିଶୋଧ ମଧ୍ୟରେ :"),
        "Repay Mode :": ("भुगतान मोड :", "পরিশোধ মোড :", "ପରିଶୋଧ ମୋଡ୍ :"),
        "Product Name :": ("उत्पाद नाम :", "পণ্যের নাম :", "ଉତ୍ପାଦ ନାମ :"),
        "View Ledger": ("लेजर देखें", "লেজার দেখুন", "ଲେଜର ଦେଖନ୍ତୁ"),
        "Did you print successfully ?": ("क्या प्रिंट सफल रहा?", "প্রিন্ট সফল হয়েছে?", "ପ୍ରିଣ୍ଟ ସଫଳ ହେଲା କି?"),
        "MANAGER": ("प्रबंधक", "ম্যানেজার", "ମ୍ୟାନେଜର"),
        "External Security Type": ("बाहरी सुरक्षा प्रकार", "বাহ্যিক জামানতের ধরন", "ବାହ୍ୟ ସୁରକ୍ଷା ପ୍ରକାର"),
        "Select account": ("खाता चुनें", "অ্যাকাউন্ট নির্বাচন করুন", "ଖାତା ବାଛନ୍ତୁ"),
        "Select loan purpose": ("ऋण उद्देश्य चुनें", "ঋণের উদ্দেশ্য নির্বাচন করুন", "ଋଣ ଉଦ୍ଦେଶ୍ୟ ବାଛନ୍ତୁ"),
        "Select mode": ("मोड चुनें", "মোড নির্বাচন করুন", "ମୋଡ୍ ବାଛନ୍ତୁ"),
        "Select product": ("उत्पाद चुनें", "পণ্য নির্বাচন করুন", "ଉତ୍ପାଦ ବାଛନ୍ତୁ"),
        "Select product type": ("उत्पाद प्रकार चुनें", "পণ্যের ধরন নির্বাচন করুন", "ଉତ୍ପାଦ ପ୍ରକାର ବାଛନ୍ତୁ"),
        "Select security type": ("सुरक्षा प्रकार चुनें", "জামানতের ধরন নির্বাচন করুন", "ସୁରକ୍ଷା ପ୍ରକାର ବାଛନ୍ତୁ"),
        "Select unit": ("इकाई चुनें", "একক নির্বাচন করুন", "ଏକକ ବାଛନ୍ତୁ"),
        "Search type...": ("प्रकार खोजें...", "ধরন খুঁজুন...", "ପ୍ରକାର ଖୋଜନ୍ତୁ..."),
        "Search...": ("खोजें...", "খুঁজুন...", "ଖୋଜନ୍ତୁ..."),
        "Generated By :": ("द्वारा बनाया गया :", "তৈরি করেছেন :", "ତିଆରି କରିଛନ୍ତି :"),
        "Generated On :": ("बनाने की तिथि :", "তৈরির তারিখ :", "ତିଆରି ତାରିଖ :"),
    }
    for eng, (hi, bn, od) in more.items():
        TR_HI.setdefault(eng, hi)
        TR_BN.setdefault(eng, bn)
        TR_OR.setdefault(eng, od)

    # Enter / Select placeholders — generate from label translations when possible
    enter_map = {
        "Enter Mouza Dag & Khatian No": ("मौजा दाग और खतियान संख्या दर्ज करें", "মৌজা দাগ ও খতিয়ান নং লিখুন", "ମୌଜା ଦାଗ ଓ ଖତିଆନ ନଂ ଲେଖନ୍ତୁ"),
        "Enter ROI": ("ब्याज दर दर्ज करें", "সুদের হার লিখুন", "ସୁଧ ହାର ଲେଖନ୍ତୁ"),
        "Enter Registration Number Etc": ("पंजीकरण संख्या आदि दर्ज करें", "নিবন্ধন নম্বর ইত্যাদি লিখুন", "ପଞ୍ଜୀକରଣ ନମ୍ବର ଇତ୍ୟାଦି ଲେଖନ୍ତୁ"),
        "Enter account type": ("खाता प्रकार दर्ज करें", "অ্যাকাউন্টের ধরন লিখুন", "ଖାତା ପ୍ରକାର ଲେଖନ୍ତୁ"),
        "Enter amount": ("राशि दर्ज करें", "পরিমাণ লিখুন", "ରାଶି ଲେଖନ୍ତୁ"),
        "Enter application date": ("आवेदन तिथि दर्ज करें", "আবেদনের তারিখ লিখুন", "ଆବେଦନ ତାରିଖ ଲେଖନ୍ତୁ"),
        "Enter application no.": ("आवेदन संख्या दर्ज करें", "আবেদন নং লিখুন", "ଆବେଦନ ନଂ ଲେଖନ୍ତୁ"),
        "Enter balance": ("शेष दर्ज करें", "ব্যালেন্স লিখুন", "ବାଲାନ୍ସ ଲେଖନ୍ତୁ"),
        "Enter bond no.": ("बॉन्ड संख्या दर्ज करें", "বন্ড নং লিখুন", "ବଣ୍ଡ ନଂ ଲେଖନ୍ତୁ"),
        "Enter certificate no.": ("प्रमाणपत्र संख्या दर्ज करें", "সার্টিফিকেট নং লিখুন", "ସାର୍ଟିଫିକେଟ୍ ନଂ ଲେଖନ୍ତୁ"),
        "Enter certificate type": ("प्रमाणपत्र प्रकार दर्ज करें", "সার্টিফিকেটের ধরন লিখুন", "ସାର୍ଟିଫିକେଟ୍ ପ୍ରକାର ଲେଖନ୍ତୁ"),
        "Enter co owner name": ("सह-स्वामी नाम दर्ज करें", "সহ-মালিকের নাম লিখুন", "ସହ-ମାଲିକ ନାମ ଲେଖନ୍ତୁ"),
        "Enter current amount": ("वर्तमान राशि दर्ज करें", "বর্তমান পরিমাণ লিখুন", "ବର୍ତ୍ତମାନ ରାଶି ଲେଖନ୍ତୁ"),
        "Enter current days": ("वर्तमान दिन दर्ज करें", "বর্তমান দিন লিখুন", "ବର୍ତ୍ତମାନ ଦିନ ଲେଖନ୍ତୁ"),
        "Enter current interest": ("वर्तमान ब्याज दर्ज करें", "বর্তমান সুদ লিখুন", "ବର୍ତ୍ତମାନ ସୁଧ ଲେଖନ୍ତୁ"),
        "Enter demand principal": ("मांग मूलधन दर्ज करें", "চাহিদা আসল লিখুন", "ଚାହିଦା ମୂଳଧନ ଲେଖନ୍ତୁ"),
        "Enter deposit amount": ("जमा राशि दर्ज करें", "আমানতের পরিমাণ লিখুন", "ଜମା ରାଶି ଲେଖନ୍ତୁ"),
        "Enter deposit balance": ("जमा शेष दर्ज करें", "আমানত ব্যালেন্স লিখুন", "ଜମା ବାଲାନ୍ସ ଲେଖନ୍ତୁ"),
        "Enter details": ("विवरण दर्ज करें", "বিবরণ লিখুন", "ବିବରଣୀ ଲେଖନ୍ତୁ"),
        "Enter disburse amount": ("वितरण राशि दर्ज करें", "বিতরণের পরিমাণ লিখুন", "ବିତରଣ ରାଶି ଲେଖନ୍ତୁ"),
        "Enter disburse date": ("वितरण तिथि दर्ज करें", "বিতরণের তারিখ লিখুন", "ବିତରଣ ତାରିଖ ଲେଖନ୍ତୁ"),
        "Enter duration": ("अवधि दर्ज करें", "সময়কাল লিখুন", "ଅବଧି ଲେଖନ୍ତୁ"),
        "Enter final repay date": ("अंतिम भुगतान तिथि दर्ज करें", "চূড়ান্ত পরিশোধের তারিখ লিখুন", "ଚୂଡ଼ାନ୍ତ ପରିଶୋଧ ତାରିଖ ଲେଖନ୍ତୁ"),
        "Enter installment amount": ("किस्त राशि दर्ज करें", "কিস্তির পরিমাণ লিখুন", "କିସ୍ତି ରାଶି ଲେଖନ୍ତୁ"),
        "Enter interest amount": ("ब्याज राशि दर्ज करें", "সুদের পরিমাণ লিখুন", "ସୁଧ ରାଶି ଲେଖନ୍ତୁ"),
        "Enter item brand": ("वस्तु ब्रांड दर्ज करें", "আইটেম ব্র্যান্ড লিখুন", "ଆଇଟମ୍ ବ୍ରାଣ୍ଡ ଲେଖନ୍ତୁ"),
        "Enter item cost": ("वस्तु लागत दर्ज करें", "আইটেম খরচ লিখুন", "ଆଇଟମ୍ ଖର୍ଚ୍ଚ ଲେଖନ୍ତୁ"),
        "Enter item name": ("वस्तु नाम दर्ज करें", "আইটেমের নাম লিখুন", "ଆଇଟମ୍ ନାମ ଲେଖନ୍ତୁ"),
        "Enter last repay date": ("अंतिम भुगतान तिथि दर्ज करें", "শেষ পরিশোধের তারিখ লিখুন", "ଶେଷ ପରିଶୋଧ ତାରିଖ ଲେଖନ୍ତୁ"),
        "Enter last repay interest": ("अंतिम भुगतान ब्याज दर्ज करें", "শেষ পরিশোধ সুদ লিখুন", "ଶେଷ ପରିଶୋଧ ସୁଧ ଲେଖନ୍ତୁ"),
        "Enter last repay principal": ("अंतिम भुगतान मूलधन दर्ज करें", "শেষ পরিশোধ আসল লিখুন", "ଶେଷ ପରିଶୋଧ ମୂଳଧନ ଲେଖନ୍ତୁ"),
        "Enter latitude": ("अक्षांश दर्ज करें", "অক্ষাংশ লিখুন", "ଅକ୍ଷାଂଶ ଲେଖନ୍ତୁ"),
        "Enter longitude": ("देशांतर दर्ज करें", "দ্রাঘিমাংশ লিখুন", "ଦ୍ରାଘିମାଂଶ ଲେଖନ୍ତୁ"),
        "Enter maturity amount": ("परिपक्वता राशि दर्ज करें", "মেয়াদোত্তীর্ণ পরিমাণ লিখুন", "ପରିପକ୍ୱତା ରାଶି ଲେଖନ୍ତୁ"),
        "Enter max allow": ("अधिकतम अनुमति दर्ज करें", "সর্বোচ্চ অনুমোদন লিখুন", "ସର୍ବାଧିକ ଅନୁମୋଦନ ଲେଖନ୍ତୁ"),
        "Enter member address": ("सदस्य पता दर्ज करें", "সদস্যের ঠিকানা লিখুন", "ସଦସ୍ୟ ଠିକଣା ଲେଖନ୍ତୁ"),
        "Enter name": ("नाम दर्ज करें", "নাম লিখুন", "ନାମ ଲେଖନ୍ତୁ"),
        "Enter outstanding balance": ("बकाया शेष दर्ज करें", "বকেয়া ব্যালেন্স লিখুন", "ବକେୟା ବାଲାନ୍ସ ଲେଖନ୍ତୁ"),
        "Enter overdue amount": ("अतिदेय राशि दर्ज करें", "ওভারডিউ পরিমাণ লিখুন", "ଅତିଦେୟ ରାଶି ଲେଖନ୍ତୁ"),
        "Enter overdue days": ("अतिदेय दिन दर्ज करें", "ওভারডিউ দিন লিখুন", "ଅତିଦେୟ ଦିନ ଲେଖନ୍ତୁ"),
        "Enter overdue interest": ("अतिदेय ब्याज दर्ज करें", "ওভারডিউ সুদ লিখুন", "ଅତିଦେୟ ସୁଧ ଲେଖନ୍ତୁ"),
        "Enter own contribution": ("स्वयं योगदान दर्ज करें", "নিজ অবদান লিখুন", "ନିଜ ଅବଦାନ ଲେଖନ୍ତୁ"),
        "Enter owner name": ("स्वामी नाम दर्ज करें", "মালিকের নাম লিখুন", "ମାଲିକ ନାମ ଲେଖନ୍ତୁ"),
        "Enter pan no.": ("पैन संख्या दर्ज करें", "প্যান নং লিখুন", "ପ୍ୟାନ୍ ନଂ ଲେଖନ୍ତୁ"),
        "Enter previous due interest": ("पूर्व देय ब्याज दर्ज करें", "পূর্ববর্তী বকেয়া সুদ লিখুন", "ପୂର୍ବ ଦେୟ ସୁଧ ଲେଖନ୍ତୁ"),
        "Enter principal amount": ("मूलधन दर्ज करें", "আসল পরিমাণ লিখুন", "ମୂଳଧନ ଲେଖନ୍ତୁ"),
        "Enter project Hypothicated Value": ("परियोजना बंधक मूल्य दर्ज करें", "প্রকল্প বন্ধক মূল্য লিখুন", "ପ୍ରକଳ୍ପ ବନ୍ଧକ ମୂଲ୍ୟ ଲେଖନ୍ତୁ"),
        "Enter project Income Generated": ("परियोजना आय दर्ज करें", "প্রকল্পের আয় লিখুন", "ପ୍ରକଳ୍ପ ଆୟ ଲେଖନ୍ତୁ"),
        "Enter project Land Offered As Security (In Acre)": ("परियोजना भूमि (एकड़) दर्ज करें", "প্রকল্পের জমি (একর) লিখুন", "ପ୍ରକଳ୍ପ ଜମି (ଏକର) ଲେଖନ୍ତୁ"),
        "Enter project cost": ("परियोजना लागत दर्ज करें", "প্রকল্পের খরচ লিখুন", "ପ୍ରକଳ୍ପ ଖର୍ଚ୍ଚ ଲେଖନ୍ତୁ"),
        "Enter project mouza": ("परियोजना मौजा दर्ज करें", "প্রকল্পের মৌজা লিখুন", "ପ୍ରକଳ୍ପ ମୌଜା ଲେଖନ୍ତୁ"),
        "Enter project name": ("परियोजना नाम दर्ज करें", "প্রকল্পের নাম লিখুন", "ପ୍ରକଳ୍ପ ନାମ ଲେଖନ୍ତୁ"),
        "Enter project own contribution": ("परियोजना स्वयं योगदान दर्ज करें", "প্রকল্প নিজ অবদান লিখুন", "ପ୍ରକଳ୍ପ ନିଜ ଅବଦାନ ଲେଖନ୍ତୁ"),
        "Enter project plot no.": ("परियोजना प्लॉट संख्या दर्ज करें", "প্রকল্পের প্লট নং লিখুন", "ପ୍ରକଳ୍ପ ପ୍ଲଟ୍ ନଂ ଲେଖନ୍ତୁ"),
        "Enter property area": ("संपत्ति क्षेत्र दर्ज करें", "সম্পত্তির এলাকা লিখুন", "ସମ୍ପତ୍ତି କ୍ଷେତ୍ର ଲେଖନ୍ତୁ"),
        "Enter property location": ("संपत्ति स्थान दर्ज करें", "সম্পত্তির অবস্থান লিখুন", "ସମ୍ପତ୍ତି ଅବସ୍ଥାନ ଲେଖନ୍ତୁ"),
        "Enter rate of interest": ("ब्याज दर दर्ज करें", "সুদের হার লিখুন", "ସୁଧ ହାର ଲେଖନ୍ତୁ"),
        "Enter ref. vouch no.": ("संदर्भ वाउचर संख्या दर्ज करें", "রেফ. ভাউচার নং লিখুন", "ରେଫ୍ ଭାଉଚର ନଂ ଲେଖନ୍ତୁ"),
        "Enter repay mode": ("भुगतान मोड दर्ज करें", "পরিশোধ মোড লিখুন", "ପରିଶୋଧ ମୋଡ୍ ଲେଖନ୍ତୁ"),
        "Enter sanction amount": ("स्वीकृत राशि दर्ज करें", "অনুমোদিত পরিমাণ লিখুন", "ଅନୁମୋଦିତ ରାଶି ଲେଖନ୍ତୁ"),
        "Enter sanction date": ("स्वीकृति तिथि दर्ज करें", "অনুমোদনের তারিখ লিখুন", "ଅନୁମୋଦନ ତାରିଖ ଲେଖନ୍ତୁ"),
        "Enter security value": ("सुरक्षा मूल्य दर्ज करें", "জামানত মূল্য লিখুন", "ସୁରକ୍ଷା ମୂଲ୍ୟ ଲେଖନ୍ତୁ"),
        "Enter share balance": ("शेयर शेष दर्ज करें", "শেয়ার ব্যালেন্স লিখুন", "ସେୟାର ବାଲାନ୍ସ ଲେଖନ୍ତୁ"),
        "Enter total amount": ("कुल राशि दर्ज करें", "মোট পরিমাণ লিখুন", "ମୋଟ ରାଶି ଲେଖନ୍ତୁ"),
        "Enter total interest": ("कुल ब्याज दर्ज करें", "মোট সুদ লিখুন", "ମୋଟ ସୁଧ ଲେଖନ୍ତୁ"),
        "Enter type name": ("प्रकार नाम दर्ज करें", "ধরনের নাম লিখুন", "ପ୍ରକାର ନାମ ଲେଖନ୍ତୁ"),
    }
    for eng, (hi, bn, od) in enter_map.items():
        TR_HI.setdefault(eng, hi)
        TR_BN.setdefault(eng, bn)
        TR_OR.setdefault(eng, od)

    # Print ALL-CAPS — keep style but translate meaning where sensible; many banking reports keep EN headers.
    # Provide translated uppercase-ish equivalents for local languages.
    print_tr = {
        "SL. NO.": ("क्रमांक", "ক্রমিক নং", "କ୍ରମିକ ନଂ"),
        "DATE": ("तिथि", "তারিখ", "ତାରିଖ"),
        "CUSTOMER NAME": ("ग्राहक नाम", "গ্রাহকের নাম", "ଗ୍ରାହକ ନାମ"),
        "GUARDIAN NAME": ("अभिभावक नाम", "অভিভাবকের নাম", "ଅଭିଭାବକ ନାମ"),
        "ACCOUNT NO.": ("खाता संख्या", "অ্যাকাউন্ট নং", "ଖାତା ନଂ"),
        "REF. AC. NO.": ("संदर्भ खाता", "রেফ. অ্যাকাউন্ট", "ରେଫ୍ ଖାତା"),
        "DISBURSE": ("वितरण", "বিতরণ", "ବିତରଣ"),
        "SHARE": ("शेयर", "শেয়ার", "ସେୟାର"),
        "INS. AMT.": ("बीमा राशि", "বীমা পরিমাণ", "ବୀମା ରାଶି"),
        "MIS. AMT.": ("विविध राशि", "বিবিধ পরিমাণ", "ବିବିଧ ରାଶି"),
        "NET DISBURSE": ("शुद्ध वितरण", "নেট বিতরণ", "ନେଟ୍ ବିତରଣ"),
        "TRANS. MODE": ("लेनदेन मोड", "লেনদেনের মোড", "ଲେନଦେନ ମୋଡ୍"),
        "PRINCIPAL": ("मूलधन", "আসল", "ମୂଳଧନ"),
        "INTEREST": ("ब्याज", "সুদ", "ସୁଧ"),
        "AMOUNT": ("राशि", "পরিমাণ", "ରାଶି"),
        "NAME": ("नाम", "নাম", "ନାମ"),
        "MEMBER NO.": ("सदस्य संख्या", "সদস্য নং", "ସଦସ୍ୟ ନଂ"),
        "ISSUE DATE": ("जारी तिथि", "ইস্যুর তারিখ", "ଇସ୍ୟୁ ତାରିଖ"),
        "ISSUE AMOUNT": ("जारी राशि", "ইস্যু পরিমাণ", "ଇସ୍ୟୁ ରାଶି"),
        "SCHEME": ("योजना", "স্কিম", "ଯୋଜନା"),
        "SCHEME NAME": ("योजना नाम", "স্কিমের নাম", "ଯୋଜନା ନାମ"),
        "OUTSTANDING BALANCE": ("बकाया शेष", "বকেয়া ব্যালেন্স", "ବକେୟା ବାଲାନ୍ସ"),
        "OUTS. BAL.": ("बकाया शेष", "বকেয়া ব্যালেন্স", "ବକେୟା ବାଲାନ୍ସ"),
        "CP BAL": ("CP शेष", "CP ব্যালেন্স", "CP ବାଲାନ୍ସ"),
        "CI BAL": ("CI शेष", "CI ব্যালেন্স", "CI ବାଲାନ୍ସ"),
        "OP BAL": ("OP शेष", "OP ব্যালেন্স", "OP ବାଲାନ୍ସ"),
        "OI BAL": ("OI शेष", "OI ব্যালেন্স", "OI ବାଲାନ୍ସ"),
        "CP BAL.": ("CP शेष", "CP ব্যালেন্স", "CP ବାଲାନ୍ସ"),
        "CI BAL.": ("CI शेष", "CI ব্যালেন্স", "CI ବାଲାନ୍ସ"),
        "OP BAL.": ("OP शेष", "OP ব্যালেন্স", "OP ବାଲାନ୍ସ"),
        "OI BAL.": ("OI शेष", "OI ব্যালেন্স", "OI ବାଲାନ୍ସ"),
        "INST. DUE": ("देय किस्त", "বকেয়া কিস্তি", "ଦେୟ କିସ୍ତି"),
        "PARTICULAR": ("विवरण", "বিবরণ", "ବିବରଣୀ"),
        "TRANS. DATE": ("लेनदेन तिथि", "লেনদেনের তারিখ", "ଲେନଦେନ ତାରିଖ"),
        "DISB. AMOUNT": ("वितरण राशि", "বিতরণের পরিমাণ", "ବିତରଣ ରାଶି"),
        "CURR. PRN. PAID": ("वर्तमान मूल भुगतान", "বর্তমান আসল পরিশোধ", "ବର୍ତ୍ତମାନ ମୂଳ ପରିଶୋଧ"),
        "CURR. INTT. PAID": ("वर्तमान ब्याज भुगतान", "বর্তমান সুদ পরিশোধ", "ବର୍ତ୍ତମାନ ସୁଧ ପରିଶୋଧ"),
        "OD. PRN. PAID": ("अतिदेय मूल भुगतान", "ওভারডিউ আসল পরিশোধ", "ଅତିଦେୟ ମୂଳ ପରିଶୋଧ"),
        "OD. INTT. PAID": ("अतिदेय ब्याज भुगतान", "ওভারডিউ সুদ পরিশোধ", "ଅତିଦେୟ ସୁଧ ପରିଶୋଧ"),
        "CURR. OUTS.": ("वर्तमान बकाया", "বর্তমান বকেয়া", "ବର୍ତ୍ତମାନ ବକେୟା"),
        "OD. OUTS.": ("अतिदेय बकाया", "ওভারডিউ বকেয়া", "ଅତିଦେୟ ବକେୟା"),
        "DUE INTT.": ("देय ब्याज", "বকেয়া সুদ", "ଦେୟ ସୁଧ"),
        "DUE MONTH": ("देय माह", "বকেয়া মাস", "ଦେୟ ମାସ"),
        "START DATE": ("प्रारंभ तिथि", "শুরুর তারিখ", "ଆରମ୍ଭ ତାରିଖ"),
        "FINAL REPAY DATE": ("अंतिम भुगतान तिथि", "চূড়ান্ত পরিশোধের তারিখ", "ଚୂଡ଼ାନ୍ତ ପରିଶୋଧ ତାରିଖ"),
        "OD PRINCIPAL": ("अतिदेय मूलधन", "ওভারডিউ আসল", "ଅତିଦେୟ ମୂଳଧନ"),
        "OD INTEREST": ("अतिदेय ब्याज", "ওভারডিউ সুদ", "ଅତିଦେୟ ସୁଧ"),
        "INSTALMENT NO.": ("किस्त संख्या", "কিস্তি নং", "କିସ୍ତି ନଂ"),
        "DUE DATE": ("नियत तिथि", "নির্ধারিত তারিখ", "ନିର୍ଦ୍ଧାରିତ ତାରିଖ"),
        "BALANCE": ("शेष", "ব্যালেন্স", "ବାଲାନ୍ସ"),
        "TOTAL INSTALMENT AMOUNT": ("कुल किस्त राशि", "মোট কিস্তির পরিমাণ", "ମୋଟ କିସ୍ତି ରାଶି"),
    }
    for eng, (hi, bn, od) in print_tr.items():
        TR_HI.setdefault(eng, hi)
        TR_BN.setdefault(eng, bn)
        TR_OR.setdefault(eng, od)


_seed_translations()


def translate_tree(en_tree: dict, lang: str) -> dict:
    tr = {"hi": TR_HI, "bn": TR_BN, "or": TR_OR}[lang]

    def walk(node):
        if isinstance(node, dict):
            return {k: walk(v) for k, v in node.items()}
        if isinstance(node, str):
            return tr.get(node, node)
        return node

    return walk(en_tree)


def get_maps():
    strings = load_strings()
    smap = build_string_map(strings)
    # Extra strings found in CollectionReceipt / labels with colons etc.
    extras = [
        "Current Principal",
        "Advance Principal",
        "Receipt Date",
        "Receipt No",
        "Total Outstanding",
        "Pending Inst.",
        "Total Rs.",
        "Received Mode :",
        "Received By :",
        "Printed On :",
        "Cashier",
        "E. & O.E.",
        "Add.",
        "Ac. No.",
        "Disb. Date.",
        "Scheme Name",
        "Max Loan :",
        "Member No :",
        "TF Paid :",
        "GF Balance :",
        "Account No. :",
        "Scheme Name :",
        "Issue Date :",
        "Issue Amount :",
        "Outs. Bal. :",
        "CP Bal :",
        "CI Bal :",
        "OP Bal :",
        "OI Bal :",
        "Loan Type - Guarantor",
        "Loan Type - Own",
        "Member Name :",
        "Guardian Name :",
        "Address :",
        "Ref. Ac. No. :",
        "Ledger Folio :",
        "Disb. Date :",
        "ROI. :",
        "Disb. Amount :",
        "Repay Within :",
        "Repay Mode :",
        "Product Name :",
        "View Ledger",
        "Did you print successfully ?",
        "MANAGER",
        "Generated By :",
        "Generated On :",
        "Done",
        "Confirm",
        "Remove",
        "(Rupees",
        "Only)",
        "Branch -",
        "Address -",
        "Scheme Name -",
        "Name",
    ]
    for e in extras:
        if e not in smap and e not in ("#", "0.00"):
            if e in OVERRIDES:
                smap[e] = OVERRIDES[e]
            else:
                letters = re.sub(r"[^A-Za-z]", "", e)
                if letters and letters == letters.upper() and len(e) > 1:
                    smap[e] = ("print", to_camel(e.lower().replace(".", " ")))
                else:
                    smap[e] = to_camel(e)
    en = build_en_tree(smap)
    return smap, {
        "en": en,
        "hi": translate_tree(en, "hi"),
        "bn": translate_tree(en, "bn"),
        "or": translate_tree(en, "or"),
    }


def t_path(key: str | tuple[str, str]) -> str:
    if isinstance(key, tuple):
        return f"loan.print.{key[1]}"
    return f"loan.{key}"
