# -*- coding: utf-8 -*-
"""Normalize polluted loan locale values (strip wrong colons/dashes; restore print caps)."""
from pathlib import Path
import re
import json

ROOT = Path(__file__).resolve().parents[1]
LOC = ROOT / "i18n" / "locales"

# Correct EN top-level loan values (forms/tables/buttons)
EN_FIX = {
    "accountNo": "Account No.",
    "memberName": "Member Name",
    "guardianName": "Guardian Name",
    "gurdianName": "Gurdian Name",
    "memberNo": "Member No.",
    "refAcNo": "Ref. Ac. No.",
    "productName": "Product Name",
    "issueAmount": "Issue Amount",
    "issueDate": "Issue Date",
    "disbAmount": "Disb. Amount",
    "disbDate": "Disb. Date",
    "ledgerFolio": "Ledger Folio",
    "repayMode": "Repay Mode",
    "repayWithin": "Repay Within",
    "maxLoan": "Max Loan",
    "tFPaid": "TF Paid",
    "gFBalance": "GF Balance",
    "outsBal": "Outs. Bal.",
    "cPBal": "CP Bal",
    "cIBal": "CI Bal",
    "oPBal": "OP Bal",
    "oIBal": "OI Bal",
    "add": "Add",
    "address": "Address",
    "branch": "Branch",
    "generatedBy": "Generated By:",
    "generatedOn": "Generated On:",
    "receivedMode": "Received Mode :",
    "receivedBy": "Received By :",
    "printedOn": "Printed On :",
    "roi": "ROI",
}

PRINT_FIX = {
    "accountNo": "ACCOUNT NO.",
    "guardianName": "GUARDIAN NAME",
    "memberNo": "MEMBER NO.",
    "refAcNo": "REF. AC. NO.",
    "issueAmount": "ISSUE AMOUNT",
    "issueDate": "ISSUE DATE",
    "disbAmount": "DISB. AMOUNT",
    "outsBal": "OUTS. BAL.",
    "schemeName": "SCHEME NAME",
    "outstandingBalance": "OUTSTANDING BALANCE",
    "roi": "ROI.",
}

HI_FIX = {
    "accountNo": "खाता संख्या",
    "memberName": "सदस्य का नाम",
    "guardianName": "अभिभावक का नाम",
    "gurdianName": "अभिभावक का नाम",
    "memberNo": "सदस्य संख्या",
    "refAcNo": "संदर्भ खाता संख्या",
    "productName": "उत्पाद का नाम",
    "issueAmount": "जारी राशि",
    "issueDate": "जारी तिथि",
    "disbAmount": "वितरण राशि",
    "disbDate": "वितरण तिथि",
    "ledgerFolio": "लेजर फोलियो",
    "repayMode": "चुकौती मोड",
    "repayWithin": "चुकौती अवधि",
    "maxLoan": "अधिकतम ऋण",
    "tFPaid": "TF भुगतान",
    "gFBalance": "GF शेष",
    "outsBal": "बकाया शेष",
    "cPBal": "CP शेष",
    "cIBal": "CI शेष",
    "oPBal": "OP शेष",
    "oIBal": "OI शेष",
    "add": "जोड़ें",
    "address": "पता",
    "branch": "शाखा",
    "generatedBy": "द्वारा जनरेट:",
    "generatedOn": "जनरेट तिथि:",
    "receivedMode": "प्राप्ति मोड :",
    "receivedBy": "प्राप्तकर्ता :",
    "printedOn": "प्रिंट तिथि :",
    "roi": "ROI",
}

BN_FIX = {
    "accountNo": "অ্যাকাউন্ট নম্বর",
    "memberName": "সদস্যের নাম",
    "guardianName": "অভিভাবকের নাম",
    "gurdianName": "অভিভাবকের নাম",
    "memberNo": "সদস্য নম্বর",
    "refAcNo": "রেফারেন্স অ্যাকাউন্ট নম্বর",
    "productName": "পণ্যের নাম",
    "issueAmount": "ইস্যু পরিমাণ",
    "issueDate": "ইস্যু তারিখ",
    "disbAmount": "বিতরণ পরিমাণ",
    "disbDate": "বিতরণ তারিখ",
    "ledgerFolio": "লেজার ফোলিও",
    "repayMode": "পরিশোধ মোড",
    "repayWithin": "পরিশোধের সময়সীমা",
    "maxLoan": "সর্বোচ্চ ঋণ",
    "tFPaid": "TF পরিশোধ",
    "gFBalance": "GF ব্যালেন্স",
    "outsBal": "বকেয়া ব্যালেন্স",
    "cPBal": "CP ব্যালেন্স",
    "cIBal": "CI ব্যালেন্স",
    "oPBal": "OP ব্যালেন্স",
    "oIBal": "OI ব্যালেন্স",
    "add": "যোগ করুন",
    "address": "ঠিকানা",
    "branch": "শাখা",
    "generatedBy": "তৈরি করেছেন:",
    "generatedOn": "তৈরির তারিখ:",
    "receivedMode": "প্রাপ্তি মোড :",
    "receivedBy": "গ্রহণকারী :",
    "printedOn": "প্রিন্ট তারিখ :",
    "roi": "ROI",
}

OR_FIX = {
    "accountNo": "ଖାତା ନମ୍ବର",
    "memberName": "ସଦସ୍ୟ ନାମ",
    "guardianName": "ଅଭିଭାବକ ନାମ",
    "gurdianName": "ଅଭିଭାବକ ନାମ",
    "memberNo": "ସଦସ୍ୟ ନମ୍ବର",
    "refAcNo": "ରେଫରେନ୍ସ ଖାତା ନମ୍ବର",
    "productName": "ଉତ୍ପାଦ ନାମ",
    "issueAmount": "ଇସ୍ୟୁ ରାଶି",
    "issueDate": "ଇସ୍ୟୁ ତାରିଖ",
    "disbAmount": "ବିତରଣ ରାଶି",
    "disbDate": "ବିତରଣ ତାରିଖ",
    "ledgerFolio": "ଲେଜର ଫୋଲିଓ",
    "repayMode": "ପରିଶୋଧ ମୋଡ୍",
    "repayWithin": "ପରିଶୋଧ ସମୟସୀମା",
    "maxLoan": "ସର୍ବାଧିକ ଋଣ",
    "tFPaid": "TF ପରିଶୋଧ",
    "gFBalance": "GF ବାଲାନ୍ସ",
    "outsBal": "ବକେୟା ବାଲାନ୍ସ",
    "cPBal": "CP ବାଲାନ୍ସ",
    "cIBal": "CI ବାଲାନ୍ସ",
    "oPBal": "OP ବାଲାନ୍ସ",
    "oIBal": "OI ବାଲାନ୍ସ",
    "add": "ଯୋଡନ୍ତୁ",
    "address": "ଠିକଣା",
    "branch": "ଶାଖା",
    "generatedBy": "ତିଆରି କରିଛନ୍ତି:",
    "generatedOn": "ତିଆରି ତାରିଖ:",
    "receivedMode": "ପ୍ରାପ୍ତି ମୋଡ୍ :",
    "receivedBy": "ଗ୍ରହଣକାରୀ :",
    "printedOn": "ପ୍ରିଣ୍ଟ ତାରିଖ :",
    "roi": "ROI",
}


def replace_in_object_block(block: str, fixes: dict) -> str:
    for k, v in fixes.items():
        block = re.sub(
            rf'(\n\s+{re.escape(k)}:\s*)"(?:\\.|[^"\\])*"',
            lambda m, val=v: m.group(1) + json.dumps(val, ensure_ascii=False),
            block,
            count=1,
        )
    return block


def patch_file(lang: str):
    path = LOC / f"{lang}.js"
    text = path.read_text(encoding="utf-8")
    di = text.rfind("\n    loan: {")
    end = text.find("\n    memberSearch:", di)
    if end < 0:
        raise SystemExit(f"memberSearch not found in {lang}")
    loan = text[di:end]

    # Split print nested object and rest
    pi = loan.find("\n        print: {")
    if pi < 0:
        raise SystemExit("print missing")
    # find end of print object
    i = loan.find("{", pi)
    depth = 0
    pe = None
    for j in range(i, len(loan)):
        if loan[j] == "{":
            depth += 1
        elif loan[j] == "}":
            depth -= 1
            if depth == 0:
                pe = j + 1
                break
    print_block = loan[pi:pe]
    before = loan[:pi]
    after = loan[pe:]

    print_block = replace_in_object_block(print_block, PRINT_FIX)

    fixes = {"en": EN_FIX, "hi": HI_FIX, "bn": BN_FIX, "or": OR_FIX}[lang]
    # Fix keys in before+after (top-level), not inside print
    after = replace_in_object_block(after, fixes)
    # Also fix any polluted keys that appear before print (colon keys area is fine)
    before = replace_in_object_block(before, fixes)

    new_loan = before + print_block + after
    text = text[:di] + new_loan + text[end:]
    path.write_text(text, encoding="utf-8")
    print(lang, "normalized")


def main():
    for lang in ("en", "hi", "bn", "or"):
        patch_file(lang)


if __name__ == "__main__":
    main()
