# -*- coding: utf-8 -*-
"""Membership i18n wire phase 2: previews + feature screens."""
from pathlib import Path
import re
import importlib.util

# reuse helpers from phase1 module
spec = importlib.util.spec_from_file_location(
    "wire_m", Path(__file__).with_name("wire-membership-i18n.py")
)
# Don't exec phase1 (it wires). Copy helpers inline instead.

ROOT = Path(__file__).resolve().parents[1] / "components" / "membership"
IMPORT = 'import { useTranslation } from "react-i18next";\n'


def ensure_import(text: str) -> str:
    if "react-i18next" in text:
        return text
    if text.lstrip().startswith('"use client"'):
        nl = text.find("\n")
        return text[: nl + 1] + IMPORT + text[nl + 1 :]
    return IMPORT + text


def ensure_hook_after_arrow(text: str, name_token: str) -> str:
    patterns = [
        rf"const {re.escape(name_token)} = \(\{{",
        rf"const {re.escape(name_token)} = \(",
    ]
    idx = -1
    for pat in patterns:
        m = re.search(pat, text)
        if m:
            idx = m.start()
            break
    if idx < 0:
        raise SystemExit(f"component not found: {name_token}")
    arrow = text.find("=>", idx)
    brace = text.find("{", arrow)
    window = text[brace : brace + 80]
    if "useTranslation()" in window:
        return text
    return text[: brace + 1] + "\n  const { t } = useTranslation();\n" + text[brace + 1 :]


def apply(text, reps, name):
    for a, b in reps:
        if a not in text:
            print(f"WARN {name}: missing {a[:90]!r}")
        text = text.replace(a, b)
    return text


def wire_file(rel, component, reps):
    path = ROOT / rel
    text = path.read_text(encoding="utf-8")
    text = ensure_import(text)
    text = ensure_hook_after_arrow(text, component)
    text = apply(text, reps, rel)
    path.write_text(text, encoding="utf-8")
    print("OK", rel)


def th(label, key):
    return (f">{label}</TableHead>", f'>{{t("{key}")}}</TableHead>')


def lab(label, key):
    return (f'label="{label}"', f'label={{t("{key}")}}')


def ph(label, key):
    return (f'placeholder="{label}"', f'placeholder={{t("{key}")}}')


def sph(label, key):
    return (f'searchPlaceholder="{label}"', f'searchPlaceholder={{t("{key}")}}')


def fl(label, key):
    return (f'formLabel="{label}"', f'formLabel={{t("{key}")}}')


PRINT_HEADERS = [
    th("SL. NO.", "membership.reports.print.slNo"),
    th("DATE", "membership.reports.print.date"),
    th("MEMBER TYPE", "membership.reports.print.memberType"),
    th("CUSTOMER NAME", "membership.reports.print.customerName"),
    th("GUARDIAN NAME", "membership.reports.print.guardianName"),
    th("VILLAGE", "membership.reports.print.village"),
    th("L/F. NO.", "membership.reports.print.lfNo"),
]

# ---------- Previews ----------
wire_file(
    "report/DetailedListPreview.jsx",
    "DetailedListPreview",
    PRINT_HEADERS
    + [
        th("OPENING", "membership.reports.print.opening"),
        th("ISSUE", "membership.reports.print.issue"),
        th("RELEASE", "membership.reports.print.release"),
        th("CLOSING", "membership.reports.print.closing"),
        th("DIV. BAL.", "membership.reports.print.divBal"),
        (
            'Share Detailed List From{" "}',
            '{t("membership.reports.preview.detailedListFrom")}{" "}',
        ),
        (
            '{fromDate && format(fromDate, "dd-MM-yyyy")} To{" "}',
            '{fromDate && format(fromDate, "dd-MM-yyyy")} {t("membership.reports.preview.to")}{" "}',
        ),
        (">Total\n", '>{t("common.total")}\n'),
        (
            "Generated By: {userName}",
            '{t("membership.reports.preview.generatedBy")} {userName}',
        ),
        (
            "Generated On: {currentDate} {currentTime}",
            '{t("membership.reports.preview.generatedOn")} {currentDate} {currentTime}',
        ),
        (
            "This report is generated by PrioSuite.",
            '{t("membership.reports.preview.footerNote")}',
        ),
    ],
)

wire_file(
    "report/DividendListPreview.jsx",
    "DividendListPreview",
    PRINT_HEADERS
    + [
        th("BALANCE", "membership.reports.print.balance"),
        (
            'Share Dividend List From{" "}',
            '{t("membership.reports.preview.dividendListFrom")}{" "}',
        ),
        (
            '{fromDate && format(fromDate, "dd-MM-yyyy")} To{" "}',
            '{fromDate && format(fromDate, "dd-MM-yyyy")} {t("membership.reports.preview.to")}{" "}',
        ),
        (">Total\n", '>{t("common.total")}\n'),
        (
            "Generated By: {userName}",
            '{t("membership.reports.preview.generatedBy")} {userName}',
        ),
        (
            "Generated On: {currentDate} {currentTime}",
            '{t("membership.reports.preview.generatedOn")} {currentDate} {currentTime}',
        ),
        (
            "This report is generated by PrioSuite.",
            '{t("membership.reports.preview.footerNote")}',
        ),
    ],
)

wire_file(
    "report/MemberRegisterPreview.jsx",
    "MemberRegisterPreview",
    PRINT_HEADERS
    + [
        th("ADM. FEES", "membership.reports.print.admFees"),
        (
            'Share Member Register From{" "}',
            '{t("membership.reports.preview.memberRegisterFrom")}{" "}',
        ),
        (
            '{fromDate && format(fromDate, "dd-MM-yyyy")} To{" "}',
            '{fromDate && format(fromDate, "dd-MM-yyyy")} {t("membership.reports.preview.to")}{" "}',
        ),
        (">Total\n", '>{t("common.total")}\n'),
        (
            "Generated By: {userName}",
            '{t("membership.reports.preview.generatedBy")} {userName}',
        ),
        (
            "Generated On: {currentDate} {currentTime}",
            '{t("membership.reports.preview.generatedOn")} {currentDate} {currentTime}',
        ),
        (
            "This report is generated by PrioSuite.",
            '{t("membership.reports.preview.footerNote")}',
        ),
    ],
)

wire_file(
    "report/WithdrawnRegisterPreview.jsx",
    "WithdrawnRegisterPreview",
    PRINT_HEADERS
    + [
        th("AMOUNT", "membership.reports.print.amount"),
        (
            'Share Withdrawn Register From{" "}',
            '{t("membership.reports.preview.withdrawnRegisterFrom")}{" "}',
        ),
        (
            '{fromDate && format(fromDate, "dd-MM-yyyy")} To{" "}',
            '{fromDate && format(fromDate, "dd-MM-yyyy")} {t("membership.reports.preview.to")}{" "}',
        ),
        (">Total\n", '>{t("common.total")}\n'),
        (
            "Generated By: {userName}",
            '{t("membership.reports.preview.generatedBy")} {userName}',
        ),
        (
            "Generated On: {currentDate} {currentTime}",
            '{t("membership.reports.preview.generatedOn")} {currentDate} {currentTime}',
        ),
        (
            "This report is generated by PrioSuite.",
            '{t("membership.reports.preview.footerNote")}',
        ),
    ],
)

wire_file(
    "report/TransactionRegisterPreview.jsx",
    "TransactionRegisterPreview",
    [
        th("SL. NO.", "membership.reports.print.slNo"),
        th("MEMBER TYPE", "membership.reports.print.memberType"),
        th("CUSTOMER NAME", "membership.reports.print.customerName"),
        th("GUARDIAN NAME", "membership.reports.print.guardianName"),
        th("VILLAGE", "membership.reports.print.village"),
        th("L/F. NO.", "membership.reports.print.lfNo"),
        th("TRANS. MODE", "membership.reports.print.transMode"),
        th("NO. OF SHARE", "membership.reports.print.noOfShare"),
        th("ISSUE", "membership.reports.print.issue"),
        th("RELEASE", "membership.reports.print.release"),
        (
            'Share Transaction Register From{" "}',
            '{t("membership.reports.preview.transactionRegisterFrom")}{" "}',
        ),
        (
            '{fromDate && format(fromDate, "dd-MM-yyyy")} To{" "}',
            '{fromDate && format(fromDate, "dd-MM-yyyy")} {t("membership.reports.preview.to")}{" "}',
        ),
        (
            "                      Sub Total\n",
            '                      {t("common.subtotal")}\n',
        ),
        (
            "                      Grand Total\n",
            '                      {t("common.grandTotal")}\n',
        ),
        (
            "Generated By : {userName}",
            '{t("membership.reports.preview.generatedBySpaced")} {userName}',
        ),
        (
            "Generated On : {currentDate} {currentTime}",
            '{t("membership.reports.preview.generatedOnSpaced")} {currentDate} {currentTime}',
        ),
        (
            "This report is generated by PrioSuite.",
            '{t("membership.reports.preview.footerNote")}',
        ),
    ],
)

print("previews done")
