# -*- coding: utf-8 -*-
"""Safely wire components/loan/** with react-i18next (no substring corruption)."""
from __future__ import annotations

from pathlib import Path
import re
import importlib.util

ROOT = Path(__file__).resolve().parents[1] / "components" / "loan"
IMPORT = 'import { useTranslation } from "react-i18next";\n'
HOOK = "  const { t } = useTranslation();\n"

spec = importlib.util.spec_from_file_location(
    "loan_i18n_data", Path(__file__).with_name("loan_i18n_data.py")
)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

smap, _ = mod.get_maps()


def t_call(eng: str) -> str:
    return f't("{mod.t_path(smap[eng])}")'


def t_jsx(eng: str) -> str:
    return f'{{{t_call(eng)}}}'


def ensure_import(text: str) -> str:
    if "react-i18next" in text:
        return text
    m = re.search(r'"use client";\s*\n', text)
    if m:
        return text[: m.end()] + "\n" + IMPORT + text[m.end() :]
    if text.lstrip().startswith("import "):
        return IMPORT + text
    return IMPORT + text


def ensure_hook(text: str, names: list[str] | None = None) -> str:
    pattern = r"const\s+([A-Z]\w*)\s*=\s*\((?:\{[\s\S]*?\}|[^)]*)\)\s*=>\s*\{"
    matches = list(re.finditer(pattern, text))
    if not matches:
        print("  WARN: no component for hook")
        return text
    targets = names or [m.group(1) for m in matches]
    for name in targets:
        for m in list(re.finditer(pattern, text)):
            if m.group(1) != name:
                continue
            at = m.end()
            if "useTranslation()" in text[at : at + 100]:
                break
            text = text[:at] + "\n" + HOOK + text[at:]
            break
    return text


def replace_quoted_attrs(text: str) -> str:
    attrs = ("label", "placeholder", "searchPlaceholder", "formLabel", "title")
    for eng in sorted(smap.keys(), key=len, reverse=True):
        te = t_call(eng)
        for attr in attrs:
            old = f'{attr}="{eng}"'
            new = f"{attr}={{{te}}}"
            text = text.replace(old, new)
        # object property label: "..."  (not optionLabelKey etc)
        old = f'label: "{eng}"'
        new = f"label: {te}"
        text = text.replace(old, new)
        old = f'emptyText = "{eng}"'
        new = f"emptyText = {te}"
        text = text.replace(old, new)
    return text


TAG_NAMES = (
    "h1",
    "h2",
    "h3",
    "h4",
    "FormLabel",
    "DialogTitle",
    "DialogDescription",
    "DialogHeader",
    "TableHead",
    "TableCell",
    "Label",
    "th",
    "p",
    "span",
)


def replace_between_tags(text: str) -> str:
    for eng in sorted(smap.keys(), key=len, reverse=True):
        te = t_jsx(eng)
        for tag in TAG_NAMES:
            # exact text node only (no nested tags)
            pat = rf"(<{tag}\b[^>]*>)\s*{re.escape(eng)}\s*(</{tag}>)"
            flags = re.I if tag == "th" else 0
            text = re.sub(pat, rf"\1{te}\2", text, flags=flags)
    return text


def replace_toasts(text: str) -> str:
    for eng in sorted(smap.keys(), key=len, reverse=True):
        te = t_call(eng)
        for kind in ("error", "success"):
            text = text.replace(f'toast.{kind}("{eng}"', f"toast.{kind}({te}")
            text = text.replace(f"toast.{kind}(`{eng}`", f"toast.{kind}({te}")
    return text


def replace_button_children(text: str) -> str:
    buttons = [
        "Add",
        "Edit",
        "Update",
        "Submit",
        "Save",
        "Cancel",
        "Print",
        "Search",
        "Close",
        "Next",
        "Reset",
        "Clear",
        "Run",
        "Yes",
        "No",
        "Fetch Details",
        "Remove",
        "Confirm",
        "Done",
    ]
    for eng in buttons:
        if eng not in smap:
            continue
        te = t_jsx(eng)
        # only as sole text child of a tag: >Add< or >\n  Add\n<
        text = re.sub(
            rf"(>)\s*{re.escape(eng)}\s*(<)",
            rf"\1{te}\2",
            text,
        )
        # ClipLoader ternary: : ("Save") or : "Save"
        text = text.replace(f': "{eng}"', f": {t_call(eng)}")
        text = text.replace(f':\n                      "{eng}"', f":\n                      {t_call(eng)}")
        text = text.replace(f':\n                        "{eng}"', f":\n                        {t_call(eng)}")
        text = text.replace(f':\n                            "{eng}"', f":\n                            {t_call(eng)}")
    return text


# Phrases safe for whole-string replace only when appearing as JSX text / string literals
SAFE_PHRASE_REPLACES = [
    "This report is generated by PrioSuite.",
    "Loan Disburse Register From",
    "Loan Repayment Register From",
    "Loan Detailed List From",
    "Did you print successfully ?",
    "Are you sure you want to release the guarantor?",
    "Loan Type - Guarantor",
    "Loan Type - Own",
    "No records found.",
    "View Ledger",
]


def replace_safe_phrases(text: str) -> str:
    for eng in sorted(SAFE_PHRASE_REPLACES, key=len, reverse=True):
        if eng not in smap:
            continue
        te = t_jsx(eng)
        # JSX text: >phrase< or whitespace-wrapped
        text = re.sub(
            rf"(>)\s*{re.escape(eng)}\s*(<)",
            rf"\1{te}\2",
            text,
        )
        # standalone on its own line inside JSX
        text = re.sub(
            rf"^(\s*){re.escape(eng)}(\s*)$",
            rf"\1{te}\2",
            text,
            flags=re.M,
        )
        # string literal for heading values
        text = text.replace(f'"{eng}"', t_call(eng))
    return text


FOOTER_PHRASES = [
    ("Generated By:", "generatedByColon"),
    ("Generated By :", None),  # use smap
    ("Generated On:", "generatedOnColon"),
    ("Generated On :", None),
]


def replace_generated_by(text: str) -> str:
    pairs = [
        ("Generated By:", smap.get("Generated By:")),
        ("Generated By :", smap.get("Generated By :") or smap.get("Generated By:")),
        ("Generated On:", smap.get("Generated On:")),
        ("Generated On :", smap.get("Generated On :") or smap.get("Generated On:")),
    ]
    for eng, key in pairs:
        if not key:
            continue
        te = t_jsx(eng) if eng in smap else f'{{t("{mod.t_path(key)}")}}'
        # only in JSX text nodes like >Generated By: {user
        text = text.replace(f">{eng} ", f">{te} ")
        text = text.replace(f">{eng}{{", f">{te}{{")
    return text


COLLECTION_LABELS = [
    "Loan Collection Receipt",
    "Collection Receipt",
    "Current Principal",
    "Overdue Principal",
    "Advance Principal",
    "Current Interest",
    "Overdue Interest",
    "Total Outstanding",
    "Pending Inst.",
    "Total Rs.",
    "Receipt Date",
    "Receipt No",
    "Particulars",
    "Cashier",
    "E. & O.E.",
    "Add.",
    "Ac. No.",
    "Disb. Date.",
    "Scheme Name",
    "Received Mode :",
    "Received By :",
    "Printed On :",
    "MANAGER",
]


def replace_exact_jsx_text_nodes(text: str, phrases: list[str]) -> str:
    for eng in sorted(phrases, key=len, reverse=True):
        if eng not in smap:
            continue
        te = t_jsx(eng)
        text = re.sub(
            rf"(>)\s*{re.escape(eng)}\s*(<)",
            rf"\1{te}\2",
            text,
        )
        # multiline indented text node
        text = re.sub(
            rf"^(\s+){re.escape(eng)}(\s*)$",
            rf"\1{te}\2",
            text,
            flags=re.M,
        )
    return text


COLON_LABELS = [
    "Member Name :",
    "Guardian Name :",
    "Address :",
    "Account No. :",
    "Ref. Ac. No. :",
    "Ledger Folio :",
    "Disb. Date :",
    "ROI. :",
    "Disb. Amount :",
    "Repay Within :",
    "Repay Mode :",
    "Product Name :",
    "Max Loan :",
    "Member No :",
    "TF Paid :",
    "GF Balance :",
    "Scheme Name :",
    "Issue Date :",
    "Issue Amount :",
    "Outs. Bal. :",
    "CP Bal :",
    "CI Bal :",
    "OP Bal :",
    "OI Bal :",
]


def replace_colon_label_nodes(text: str) -> str:
    for eng in sorted(COLON_LABELS, key=len, reverse=True):
        # keys may be without trailing space in smap
        key_eng = eng if eng in smap else eng.rstrip()
        if key_eng not in smap and eng not in smap:
            # try with trailing space variants
            candidates = [eng, eng.rstrip(), eng + " ", eng.rstrip() + " "]
            key_eng = next((c for c in candidates if c in smap), None)
            if not key_eng:
                continue
        te = t_jsx(key_eng if key_eng in smap else eng)
        text = re.sub(
            rf"(>)\s*{re.escape(eng)}\s*(<)",
            rf"\1{te}\2",
            text,
        )
    return text


def process_file(path: Path, also: list[str] | None = None):
    text = path.read_text(encoding="utf-8")
    text = ensure_import(text)
    names = [m.group(1) for m in re.finditer(r"const\s+([A-Z]\w*)\s*=\s*\(", text)]
    text = ensure_hook(text, also or names)
    text = replace_quoted_attrs(text)
    text = replace_between_tags(text)
    text = replace_toasts(text)
    text = replace_button_children(text)
    text = replace_safe_phrases(text)
    text = replace_generated_by(text)
    text = replace_exact_jsx_text_nodes(text, COLLECTION_LABELS + SAFE_PHRASE_REPLACES)
    text = replace_colon_label_nodes(text)
    # Subtotal / Grand Total / Total already via TableCell/tags
    # Fix accidental documentTitle stringification — leave documentTitle as plain English
    text = re.sub(
        r'documentTitle:\s*t\("loan\.[^"]+"\)',
        lambda m: m.group(0),  # keep if already t() without quotes — ok
        text,
    )
    if '"{t(' in text or "class{t(" in text or "head{t(" in text:
        print("  WARN corruption markers in", path.name)
    path.write_text(text, encoding="utf-8")
    print("ok", path.relative_to(ROOT).as_posix())


def main():
    for p in sorted(ROOT.rglob("*.jsx")):
        also = None
        if p.name == "index.jsx" and "newApplication" in str(p):
            also = ["ResponsiveTable", "NewApplication"]
        process_file(p, also)


if __name__ == "__main__":
    main()
